### ISSUE TITLE
Add a Total-Records header to delete on plural endpoints

### ISSUE THREAD

**Issue by gabisurita** [Kinto/kinto#1000]
For consistency with GET, now that we support pagination on DELETE.

**Comment by leplatrem** [comment]
Thousand \o/

![](http://i.giphy.com/YTbZzCkRQCEJa.gifhttp://i.giphy.com/YTbZzCkRQCEJa.gif)

**Comment by gabisurita** [comment]
Weeeeeeeee   💯0
