### ISSUE TITLE
Should we be including the entire source for kinto-admin in this repo?

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#1012]
It seems like a compiled output from another project. Can we just build it as part of the distribution for releases instead, or something like that?

**Comment by Natim** [comment]
The kinto-admin JS is considered as being to some static files dependencies of the admin plugin.

If you consider master as being a runnable distribution of Kinto, then we are already doing that.
We update it in master for each release of the kinto-admin.
We can update the static files to there last version by running `make update-kinto-admin`

After using this process for few months I find it really robust, why do you think we should change it?

**Comment by glasserc** [comment]
For the same reason that we don't commit .pyc files to master. These files are not the preferred form for modification or even readable. Verifying a PR that modifies these files is therefore impossible. These files are the output of an automatic process and so keeping them around is just wasted space. It probably wouldn't be such a big deal to me except that the kinto-admin plugin is by far the heaviest thing in a git clone, weighing in at 7MB (out of 7.9MB), so doing a `git pull` is much slower when someone updates these files.

I agree that master should be "runnable", but I don't think that means we need to keep kinto-admin build outputs in source control. We could agree that "runnable" means "runnable without the admin", or we could agree that "runnable" means "runnable with everything in a non-optimized way", or we could agree that "runnable" means "runnable once you execute a build step". Each of these ways could permit kinto-admin build outputs to not be checked in to git, because they don't belong there.

**Comment by Natim** [comment]
I see your point, that something we need to discuss and fix then.

**Comment by leplatrem** [comment]
Runnable means `make serve` just works. We could add a Makefile entry to fix that.

I agree that it is very annoying to have to files (eg. `git grep`)

**Comment by leplatrem** [comment]
I just found that zest.releaser has the notion of hooks:
https://github.com/zestsoftware/zest.releaser/blob/6.8.1/zest/releaser/tests/functional-with-hooks.txt

So that means we could have a release hook that builds the admin before pushing it to pypi. 

From a git clone, a `make` command would be enough.
