### ISSUE TITLE
updated default kinto config breaks docker (kinto server not reacheable from host)

### ISSUE THREAD

**Issue by elelay** [Kinto/kinto#1013]
In e4e70fb, the default listen ip has been changed to 127.0.0.1.
I couldn't manage to export the port using docker, using this command from the [install documentation](http://kinto.readthedocs.io/en/latest/tutorials/install.html#environment-variables):
```
docker run --env-file kinto.env --link kinto_db:db -p 127.0.0.1:8888:8888 --name kinto_web croco/kinto:latest
```
For instance, when I do `curl http://127.0.0.1:8888` from the host I get `Recv failure: Connection reset by peer`.

When I reverted kinto.ini to listen on 0.0.0.0, curl from the host succeeds.

Maybe there is an environment variable to override the `host` entry in the `server:main` section? Then it would be fine, provided an updated documentation...

This is not visible with the published kinto/kinto-server image, since it's still 5.1. I built my own from master because I needed an armhf image.

**Comment by elelay** [comment]
#949 was the rational to change the default config (fails when no network).

**Comment by elelay** [comment]
Contrary to what I said in the description, it's visible in kinto/kinto-server:latest

**Comment by glasserc** [comment]
I'm tempted to classify this as a regression, but I think listening on either 127.0.0.1 or 0.0.0.0 are equally "correct" in the general case. (See [this Pyramid issue](https://github.com/Pylons/pyramid/issues/489#issuecomment-4671393) for some heated discussion on this point.) And it doesn't seem like pserve respects any environment variables about host, and we don't do anything special with those variables. Given that, I think we should update `kinto init` to allow the user to specify what address to listen on, and update the Dockerfile to pass 0.0.0.0 to this argument.
