### ISSUE TITLE
pyramid.route_path to build internal route_path

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#103]
We are building URIs by hand at multiple places in the code (e.g. parent id, default subrequests) and we should probably use ``request.route_path()`` for that.

http://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.route_path

**Comment by Natim** [comment]
Basically in the code of Kinto we are sometimes building URLs.

 - https://github.com/Kinto/kinto/blob/master/kinto/views/records.py#L35
 - https://github.com/Kinto/kinto/blob/master/kinto/views/records.py#L47-L48
 - https://irccloud.mozilla.com/pastebin/69teBJGJ
 - https://irccloud.mozilla.com/pastebin/1bWBKhLm

Instead of building this URLs by hand we would like to use route_path to do it.

You can have a list of all the URLs and there name by running: ``.venv/bin/proutes config/kinto.ini`` (once you've [installed Kinto](http://kinto.readthedocs.org/en/latest/contributing.html#hack))

For instance ``'/buckets/%s/collections/%s' % (self.bucket_id, self.collection_id)`` could be written: ``route_path('collection-record', bucket_id=self.bucket_id, collection_id=self.collection_id)``
``route_path`` may return the ``/v1/`` prefix in front so we may have to create an helper that will remove it. But that's the idea.

**Comment by vsham20** [comment]
@Natim I am working on this
