### ISSUE TITLE
Kinto Admin version not shown in footer

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1032]
![screenshot from 2017-01-24 17-01-08](https://cloud.githubusercontent.com/assets/546692/22255110/b87c08e2-e256-11e6-9880-b85014bb9f0a.png)

Looks like the effects of this are lost when packaged as a kinto plugin:

https://github.com/Kinto/kinto-admin/commit/8b184b041121ed4affddfbc2ce98ce658226ee34

**Comment by n1k0** [comment]
Te admin must be built exposing a KINTO_ADMIN_VERSION env var, eg. `KINTO_ADMIN_VERSION=1.8.0 npm run build`
