### ISSUE TITLE
Cache backend exception are not converted to BackendError

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1039]

**Comment by leplatrem** [comment]
Are you sure it's not the case? 
Is this only for Memory?

I can see that we catch all `SQLAlchemy` errors in the PostgreSQL client already?

Note: see https://github.com/Kinto/kinto-redis/blob/master/kinto_redis/storage.py#L14-L22

**Comment by Natim** [comment]
Yes, maybe that's for the Memory backend

**Comment by leplatrem** [comment]
What error can happen with the memory cache backend?
