### ISSUE TITLE
?_fields only work on GET

### ISSUE THREAD

**Issue by gabisurita** [Kinto/kinto#1044]
[Selecting fields](http://kinto.readthedocs.io/en/stable/api/1.x/selecting_fields.html) doesn't work with other verbs rather than GET. Should it? The documentation says nothing about it.

**Comment by glasserc** [comment]
I think you could argue that it should work on other requests and have the semantics that it affects only the response to the request. This could maybe be useful for large PUT requests made on an asymmetric connection, for example.

I think you could also argue that the semantics are a little muddled. If someone PUTs to a "subset" of a record, I feel like that could be interpreted to mean "replace the fields I selected, but leave the other fields alone".

Personally, I think it should only work on GET. I think the semantics are clearest and we don't have a use case for having it on other methods.

**Comment by Natim** [comment]
Yes it only works on GET
