### ISSUE TITLE
Add comment to history when editing records

### ISSUE THREAD

**Issue by pocmo** [Kinto/kinto#1051]
The 'history' tab showing past collection updates is pretty helpful. It would be great if I could add a comment when editing a collecting (like you can do when updating Wikipedia). With that I could explain why I did a change and link to a detailed bug.

**Comment by n1k0** [comment]
Do we want comments attached to single entries, or would we prefer a general comment when submitting changes for review?

**Comment by leplatrem** [comment]
Tracking of this will happen in kinto-admin repo. Thanks for the feedback!
