### ISSUE TITLE
Enforce the permission endpoint when the admin plugin is included.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1059]

**Comment by vforvad** [comment]
Could you please provide more information about that?

**Comment by Natim** [comment]
There is a setting to activate the permission endpoint: http://kinto.readthedocs.io/en/stable/configuration/settings.html#activating-the-permissions-endpoint

To activate the admin plugin we use: ``kinto.includes = kinto.plugins.admin``

What we want is to automatically activate the permission endpoint if the kinto_admin plugin is configured.

**Comment by leplatrem** [comment]
See https://github.com/Kinto/kinto/blob/master/kinto/__init__.py#L82-L84
