### ISSUE TITLE
Managing cliquet extra requirements

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#106]
*Cliquet* defines some extra requirements:

* ``postgresql``, for the backends
* ``monitoring`` for monitoring tooling (statsd, newrelic)

Currently, we don't pull them in *Kinto*, because we want it to be straightforward to run (i.e. ``git clone``, ``make serve``). That's why we also switched to the memory backend by default.

But, as a consequence, if someone wants to use *Kinto* with postgresql, she has to explicit pull cliquet requirements using ``pip install "cliquet[postgresql]"`` (see docs).

Ideally, we would like to add a some extra requirements to *Kinto* to ease that (for example ``pip install kinto[production]``).

Our attempts did not lead us anywhere so far. We need help!

See:
* https://github.com/mozilla-services/kinto/commit/695dde80d8b03f95b268d1c4eee46ff7f696f838 : see ``[:-1]``
* https://github.com/mozilla-services/kinto/commit/a17da2a0959638bb80c4ade46e08386b6b59f864 : repeats cliquet underlying deps (not ideal)

**Comment by Natim** [comment]
In Syncto we chose to install monitoring tools as part of the project: https://github.com/mozilla-services/syncto/blob/master/setup.py#L17

But it is not as easy for cliquet.
I think the best way to handle that is to copy the monitoring and postgresql options from cliquet to kinto. (We can also choose to keep them in cliquet as well)

**Comment by leplatrem** [comment]
Fixed with #367
