### ISSUE TITLE
If-Match:* behaviour is unclear (and crashes) with existing record

### ISSUE THREAD

**Issue by gabisurita** [Kinto/kinto#1063]
On 5.2 it would raise a "400" on existing record.

On current master, it will crash in "500" as it's not handled by `kinto.core.resource` anymore, but it's considered a valid header value by deserialization.

I think we should set the behavior to just ignore it. and process the request anyways. Opinions?

**Comment by Natim** [comment]
> I think we should set the behavior to just ignore it. and process the request anyways. Opinions?

No it should raise a 400 because If-Match:* is not a valid value.
