### ISSUE TITLE
If-Match: * does not match the spec

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#1072]
Per https://github.com/Kinto/kinto/pull/1064#issuecomment-279351031, the behavior of `If-Match: *` is the opposite of `If-None-Match: *`. `If-None-Match: *` should succeed if no resource exists at the given URL and fail if any resource exists at the given URL, but `If-Match: *` should fail if no resource exists at the given URL and succeed if any resource exists at the given URL. Currently `If-Match: *` does nothing (it always succeeds).

**Comment by glasserc** [comment]
Ugh, I guess this got opened by someone else in the meantime..

**Comment by Natim** [comment]
You are so lagging 🗡

**Comment by gabisurita** [comment]
What about the behavior of `If-Match` on a numeric value? Should we ignore it when a resource doesn't exists? What does matching on a non-existing resource means?

**Comment by glasserc** [comment]
I agree with you: I think `If-Match: "abcd"` should fail if the record is not there.

While I'm here, I should also note that I think the current behavior of the codebase is slightly wrong. If I read the code correctly, it tries to compare the If-Match header against the current record's ETag, and fail if the record is newer. I think this is different from what the spec says, which is that the request should fail unless the record's ETag is exactly the same (neither older nor newer) than the If-Match header, but I don't think it's super important as long as the clients behave properly (because time, and thus our ETags, are monotonic). We assign more meaning to ETags than the standard really requires -- ETags are just opaque cookies representing the version of a document and don't have to behave monotonically or anything.

**Comment by Natim** [comment]
> it tries to compare the If-Match header against the current record's ETag, and fail if the record is newer.

Yes that's because before we used `If-Modified-Since` and we kept the same behaviour.

**Comment by gabisurita** [comment]
What about the behavior on plural endpoints? Now we consider `If-Match: *` and `If-None-Match: *` to always succeed on collection gets and deletes. Should we keep this behavior or validate on ALL or ANY clauses?
