### ISSUE TITLE
Custom widgets/validation?

### ISSUE THREAD

**Issue by Osmose** [Kinto/kinto#1083]
You can specify a schema for your data, and a uiSchema for how to build the form for it. I'd like to be able to add a custom type for a field (specifically, a [JEXL](https://github.com/TechnologyAdvice/Jexl) expression) that has custom validation, and potentially a UI widget that helps in writing that custom type.

But that custom type doesn't seem like a thing I should, say, land in Kinto itself. I'd like to be able to write something like a plugin for Kinto that adds support for my new custom type to a Kinto instance. I dunno if that's already possible or how hard it would be to add, though.

Thanks!

**Comment by Natim** [comment]
I think this is a question for the [kinto-admin](https://github.com/Kinto/kinto-admin) project.

**Comment by Osmose** [comment]
Moved: https://github.com/Kinto/kinto-admin/issues/388

**Comment by n1k0** [comment]
Well, this is also an issue for Kinto as it impacts the admin plugin and the way Kinto server users may extend the admin plugin capabilities, eg. through plugins with custom widgets. I'm reopening so we can keep track of progress on this.

**Comment by leplatrem** [comment]
We track kinto-admin issues there, closing ;)
