### ISSUE TITLE
How to run backends migration using a project based on kinto.core

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1103]
Today I deployed webpush-channels project using postgresql and I had to run the migrations.

However ``kinto --ini config.ini migrate`` didn't work because the settings were prefixed with `webpush_channels.` and not `kinto.`

I had to change the config to either replace this conf by `kinto.` or removing the prefix to be able to run the command.

I guess I should create a `webpush-channels migrate` command but can we do better?

Should we add a `--config-prefix` parameter?: `kinto --ini config.ini --config-prefix webpush_channels migrate`

**Comment by leplatrem** [comment]
If you set the `project_name` to `webpush_channels`, then this is a bug

**Comment by Natim** [comment]
I guess that was it: https://github.com/webpush-channels/webpush-channels/commit/f9056c66a67637f3f9bd4772099a85c2579d02ce
