### ISSUE TITLE
[history] State of objects at particular timestamp

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1104]
There is a need to be able to see the state of an object (or list of objects) at a particular timestamp (when the history plugin is enabled).

This would consist in applying the history entries backwards to obtain the same response (+headers) as it used to be at that timestamp. The endpoint would be read-only.

There are some specific aspects that may be difficult to handle like permissions (is that user allowed to see those old records?).

An alternative approach is to do it on the client side using the existing history endpoint.

See also #826

**Comment by n1k0** [comment]
If I'm assigned to this it'll probably take a long time before the feature sees the light of the day :) but why not.

**Comment by Natim** [comment]
Should we implement something like:

`/buckets/<bucket_id>/collections/<collection_id>/records?_history_at=<last_modified>`

**Comment by n1k0** [comment]
Just `_at` would work for me

**Comment by Natim** [comment]
It should fail if the history plugin is not present.

**Comment by Natim** [comment]
Maybe it would be easier to use an new view:

- Buckets: /v1/buckets/version?at=1486464958017
- Bucket: /v1/buckets/tasks/version?at=1486464958017
- Collections: /v1/buckets/tasks/collections/version?at=1486464958017
- Collections: /v1/buckets/tasks/collections/todo/version?at=1486464958017
- Records: /v1/buckets/tasks/collections/todo/records/version?at=1486464958017
- Record: /v1/buckets/tasks/collections/todo/records/5c7d0e7b-5f05-4118-b2a1-25ccf329905e/version?at=1486464958017

**Comment by gabisurita** [comment]
From the API perceptive, I like the idea of making it a filter (e.g. `records/id?_at=<last_modified>`), but I'm not sure if this is feasible in a plugin (it probably is, but will be ugly) and I also don't think this should be part of the core.

I think a new view is the easiest approach if we are doing it on the server and want to keep it as a plugin.

**Comment by leplatrem** [comment]
I assigned you as a way to ping, nothing else ;)

Le 23 févr. 2017 18:06, "Gabriela Surita" <notifications@github.com> a
écrit :

**Comment by n1k0** [comment]
We discussed this with @Natim and discarded the idea, but the more I think about it, the more I'd be very happy with just `records/id?_at=<last_modified>`; that would be more intuitive and consistent with other filters. I get that altering core endpoints/features with plugin stuff might sound odd and be harder to maintain though.

**Comment by gabisurita** [comment]
> Edit: well, not so intuitive if you consider mixing qs params like _at=123&_before=123 or silly crap like that. Oh well.

If `_at` is just for records you can't mix it with before, so I guess it still intuitive.

**Comment by gabisurita** [comment]
> I assigned you as a way to ping, nothing else ;)

OK. I'm just having some fun here. haha

**Comment by n1k0** [comment]
> If _at is just for records you can't mix it with _before

Well that's the thing, we started with records but we'll actually want the same for collections.

**Comment by leplatrem** [comment]
I've got another idea: we do it on the client side 😇

**Comment by n1k0** [comment]
> I've got another idea: we do it on the client side :innocent:

I said I needed some sleep 😁

**Comment by leplatrem** [comment]
This was successfully implemented in kinto-http.js, the code is straightforward.
See https://github.com/Kinto/kinto-http.js/pull/161
