### ISSUE TITLE
Add a Makefile rule to py.test-watch plugin to rerun tests automatically on changes for tdd

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1107]
https://github.com/joeyespo/pytest-watch

`$ ptw -- -k ...`

**Comment by shreab373** [comment]
hi, i'm a newcomer, i wanted to take up this bug, could you guide me through it?

**Comment by Natim** [comment]
The idea is to add pytest-watch as a dev dependency and then add a rule in the Makefile to be able to run py.test with that plugin.

**Comment by leplatrem** [comment]
It could be a `make tdd` that runs the `ptw` command with the appropriate parameters

**Comment by shreab373** [comment]
i'm getting this [error](https://kinto.slack.com/files/shreab373/F4RG5BT6Y/error) while installing and  /tmp/pip-build-8aitcx1c/ujson/ doesn't exist

**Comment by Natim** [comment]
You need to install ``python-dev``

**Comment by shreab373** [comment]
solved, i was using python3, i needed python3-dev, thanks!!

**Comment by sahildua2305** [comment]
Just checking in - @shreab373 are you still working on this?

**Comment by shreab373** [comment]
Go ahead :)

**Comment by suryajoshi007** [comment]
Would love to work on this. Can i get started?

**Comment by Natim** [comment]
Yes please go ahead, you don't need to ask. Take the issue and file a pull-request.

**Comment by suryajoshi007** [comment]
Ok will file it as soon as possible:)

**Comment by palash25** [comment]
Hi there I would like to be assigned to this issue.

**Comment by Natim** [comment]
Just file a pull-request and you will be fine :)
