### ISSUE TITLE
Consider moving to mozlog instead of the build-in Heka Renderer

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1110]
Refs [Bug 1340674](https://bugzilla.mozilla.org/show_bug.cgi?id=1340674)
Refs http://mozbase.readthedocs.io/en/latest/mozlog.html

**Comment by leplatrem** [comment]
Would that mean going away from structlog?

I'm +0 :)

**Comment by leplatrem** [comment]
I'll try to drop the built-in Heka renderer and use https://github.com/mozilla/mozilla-cloud-services-logger in Kinto-dist. If the output is alright, we'll get rid of code \o/

**Comment by leplatrem** [comment]
We're doing something wrong, we should get rid of our `logging_renderer` setting.
