### ISSUE TITLE
The Swagger spec is invalid

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#1172]
https://online.swagger.io/validator/debug?url=https://firefox.settings.services.mozilla.com/v1/__api__

cc @chartjes

**Comment by gabisurita** [comment]
It's fixed on Kinto 5.4.1 and Kinto 6.X

https://github.com/Kinto/kinto/releases/tag/5.4.1

**Comment by gabisurita** [comment]
Ref https://github.com/Kinto/kinto/issues/1106
