### ISSUE TITLE
Sync data with PostgreSQL 9.6 backend

### ISSUE THREAD

**Issue by cmizzi** [Kinto/kinto#1175]
Hi everyone !

We have to develop a newer application based on progressive web app idea and we need a solution to manage the offline first mode. We are currently interested about Kinto but we have some interrogations : 

* can we use PostGIS with Kinto ?
* are we forced to use Kinto JSON schema or we could use a custom PostgreSQL schema (typed-field) ?

Best regards,

**Comment by leplatrem** [comment]
Hi!
Welcome on board!

I will try to answer your questions, let us know what you think and we can drill down into details :)

>   can we use PostGIS with Kinto ?

In short: you can use PostGIS in the Kinto database but the provided backend code does not use PostGIS.

You can enhance the default DB schema with your custom tables, views, columns, triggers or whatever, but our backend code won't be aware of it. Of course, you could implement your own geospatial backend, and even publish it as a package for the community if you like :)

May I ask: do you really need PostGIS or you just want to do geospatial queries on your data? For the latter, the [ElasticSearch approach](https://kinto.readthedocs.io/en/stable/tutorials/write-plugin.html) would really be the most efficient IMO :)

> could use a custom PostgreSQL schema ?

There are two strategies:

* you keep the provided Postgresql backend, and you define a trigger that will spread the JSON field into your typed fields
* you define your own Postgresql backend, and you store the data the way you want from the dict objects you'll receive in the Python code

Hope it clarifies a bit :)

**Comment by leplatrem** [comment]
Closing, please re-open if you have more questions on the same topic!
