### ISSUE TITLE
Relationships between collections?

### ISSUE THREAD

**Issue by timwis** [Kinto/kinto#1179]
Hi folks, forgive me if this is not the best place to ask, but I hope it is. I'm quite excited to use Kinto after listening to the Python.__init__ podcast and exploring the documentation. But I'm wondering how I'd go about creating relationships between collections? Ie. a one-to-many relationship between users and posts. Is there a concept of this in kinto? Or do I just need to load the entire contents of the related collection and make the matches manually based on the id?

**Comment by glasserc** [comment]
No, Kinto doesn't have any concept of relationships or "foreign keys". In this, it is much like other document-store technologies like Redis, CouchDB or Mongo. The equivalent of a SQL join is to fetch related things on the client. You could do this in-memory, like you propose; this is easier if you've already "synced" the collections locally. If you're just using an HTTP-based client, you could also do it with multiple round-trips to the server.

I hope this answers your question; if it doesn't, feel free to reopen. This is a fine place to ask questions, but we also list several other places at http://kinto.readthedocs.io/en/stable/community.html :)

**Comment by Natim** [comment]
You can actually use the id of one record as a property of another record. But you won't have ForeignKey constraints or ON DELETE cascade capabilities. In certain cases it might be sufficient.

You can use batch request to achieve a similar request of join.

**Comment by Natim** [comment]
It depends of the use case yes.

For the user / posts thing, you can just sync all users and all posts so that you have the users in your local state.

**Comment by MarcCoet** [comment]
Did anyone develop a custom widget for Kinto admin to handle this?

**Comment by leplatrem** [comment]
Not that I know :)
