### ISSUE TITLE
regeneratorRuntime is not defined error

### ISSUE THREAD

**Issue by flukeout** [Kinto/kinto#1190]
Was starting to work with Kinto, and things were working fine until I started seeing this error.
Below is the only JS I'm running at this point, looks like just including the kinto js file is causing this...

```
  <head>
    <title>Kinto Test</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://unpkg.com/kinto-http/dist/kinto-http.min.js"></script>
  </head>
```

<img src="https://cloud.githubusercontent.com/assets/25212/24926859/e6c0924e-1eb1-11e7-9cc5-04e63e5e9c62.png" width="350"/>

Any ideas or guidance is appreciated.

I'm following the instructions for a client-side implementation here:
* https://doc.esdoc.org/github.com/Kinto/kinto-http.js/

**Comment by leplatrem** [comment]
Could you try with https://unpkg.com/kinto-http@4.2.0/dist/kinto-http.min.js ?
There seems to be a packaging issue in kinto-http.js 4.3.X (released yesterday)

**Comment by flukeout** [comment]
Yeah, that did it. Thanks!

**Comment by flukeout** [comment]
First pass at a Thimble project using Kinto for storage, and works great!
https://thimbleprojects.org/flukeout/250660/

**Comment by n1k0** [comment]
This error should be gone with latest kinto-http [v4.3.2](https://github.com/Kinto/kinto-http.js/releases/tag/v4.3.2). Thanks for reporting.

**Comment by leplatrem** [comment]
> First pass at a Thimble project using Kinto for storage, and works great!
> https://thimbleprojects.org/flukeout/250660/

This is awesome! Yeah!
