### ISSUE TITLE
Filter objects where a particular field is null 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1215]
`/records?field.name=null` ?

**Comment by leplatrem** [comment]
Related #343 #344

**Comment by glasserc** [comment]
Isn't that syntax ambiguous? It's the same to search for any object whose value is the string `"null"`. I'd rather be more rigid about what our query syntax is for this case, maybe introducing a new syntax for JSON-y values like `is_field.name=null` or `json_field.name=null`.

**Comment by Natim** [comment]
``https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/releases/records?build.id=null``

Returns an empty list, so I guess it is not sufficient.

**Comment by glasserc** [comment]
Should `field.name=null` match records where the field is missing, or only where it is explicitly present and null? (I would vote for the second option)

**Comment by glasserc** [comment]
Fixed by #1252 and #1258.
