### ISSUE TITLE
specify record contents accepted by storage

### ISSUE THREAD

**Issue by elelay** [Kinto/kinto#1238]
An inconsistency between memory and PG storage led to shipping broken `accounts` plugin (#1224).

It was caused by memory storage not touching the contents of given record (contained a bytes value), whereas PG storage converted it to str. See discussion in #1227.

Memory can be made like PG storage with a moderate cost (serialiaze/deserialize records with ujson), like in PR #1237. This leaves potential errors in production when somebody sends non utf-8 encoded input where we only tested with utf-8 input.

But, as @glasserc pointed out, storage could also be made stricter on datatypes it accepts in records (i.e. REJECT bytes). Then errors will happen during development, which is better.

To do this, I think one would have to scan records beforehand or add an option to ujson to do it or retuirn to standard package json.

**Comment by glasserc** [comment]
I've opened https://github.com/esnme/ultrajson/issues/264 to see what upstream thinks about disallowing `bytes`, but I don't really expect that to happen because ujson's approach seems to generally be "Serialize it all and let Douglas Crockford sort 'em out". For example:

```
>>> ujson.dumps({"hi": set()})
'{"hi":[]}'
>>> ujson.dumps({"hi": object()})
'{"hi":{}}'
>>> class MyFoo:
...   def __init__(self, a, b):
...     self.a = a
...     self.b = b
... 
>>> ujson.dumps(MyFoo(1, 'a'))
'{"a":1,"b":"a"}'
```

Compare this with the built-in `json`, which is quite conservative about what it will serialize:

```
>>> json.dumps({"hi": set()})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: set() is not JSON serializable
>>> json.dumps({"hi": object()})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <object object at 0x7f60779680a0> is not JSON serializable
```

It might be smart to use the built-in JSON during testing and use ujson for increased performance when in production. That might be more work?

**Comment by elelay** [comment]
@glasserc  good idea: the specification for records is then *a dict that is JSON serializable according to the builtin json module*. 
Anything that is accepted by json would be accepted by ujson. With the already excellent test coverage, the more lax behaviour of ujson would be hidden as a production optimisation.
I'll try it out and let you know.
