### ISSUE TITLE
Accounts parent_id in records table not being set correctly

### ISSUE THREAD

**Issue by delebash** [Kinto/kinto#1248]
Ubuntu 16.04
From source Latest commit 5e2a13b
Postgres database

1. Change kinto.ini to enable accounts
2. Create admin user myadmin with
`kinto.account_create_principals = system.Everyone
`
3. Then change to
`kinto.account_create_principals = account:myadmin`

Final kinto.ini changes
```
multiauth.policies = account
multiauth.policy.account.use = kinto.plugins.accounts.authentication.AccountsAuthenticationPolicy
# Allow anyone to create accounts.
kinto.account_create_principals = account:myadmin
# Set user 'account:admin' as the administrator.
kinto.account_write_principals = account:myadmin
kinto.account_read_principals = account:myadmin

```

4.  Create user using myadmin auth
echo '{"data": {"id": "zzz", "password": "test"}}' | http POST http://192.168.2.12:8888/v1/accounts --auth 'myadmin:test'

5. Try to delete user
`http DELETE http://192.168.2.12:8888/v1/accounts/zzz --verbose --auth 'myadmin:test'`

```
{
    "code": 404,
    "details": {
        "id": "zzz",
        "resource_name": "account"
    },
    "errno": 110,
    "error": "Not Found"
}
```

6. If you change user zzz's password then Delete is a success
echo '{"data": {"password": "asdf"}}' | http PUT http://localhost:8888/v1/accounts/zzz --verbose --auth 'myadmin:test'

If you look at the records table in Postgres you will see that the initial creation of user zzz's parent_id is set to *

After changing zzz's password parent_id is set to zzz

**Comment by leplatrem** [comment]
Thank you very much for this detailed bug report! 

The account resource contains some hacks to be able to allow anonymous creation and still have a `parent_id` that makes its content private to each user. We'll look into it :)
