### ISSUE TITLE
Add support for Auth0

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1270]
See #509

**Comment by leplatrem** [comment]
Duplicate of #939 

Related #508

**Comment by cfguimaraes** [comment]
Hi, all.
Is this the second view I do to this project, it's fantastic and I'm looking for this in a current project. In the next week I think that I have to decide which storage mechanism I need, Auth is a essential part of the app to permit users share their data with other (Kinto does it extremely well, congratulations), could some member give a report about status of this feature.
If there are no plans, can someone give a way to integrate Kinto with Auth0?
Thanks in advance.

**Comment by cfguimaraes** [comment]
Until my last post, I was reading on contributing and looking for implementations, couldn't find anyone.
I'm planning to make a wrapper on auth0 SDK for pyramid, I will setup things to run Kinto locally to make tests and after that make a status report.

**Comment by leplatrem** [comment]
Last month, we could make authentication work with Auth0 using the code of this PR #1425.
It should be enough to get started on your side. We are tracking Auth0 support via OpenID in #939.
