### ISSUE TITLE
Explain how to work with GeoFields and kinto-elasticsearch

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1272]
cc @barbichu

**Comment by leplatrem** [comment]
I revamped the little pizzerias example that we had a couple of years ago: 
https://github.com/Kinto/kinto-elasticsearch/pull/52/files

It just works, I will clean it up and make a blog post out of it...

**Comment by Natim** [comment]
Thanks that would be awesome !!!

**Comment by leplatrem** [comment]
http://www.servicedenuages.fr/en/kinto-elasticsearch
