### ISSUE TITLE
Selection and export features on bucket graphical interface

### ISSUE THREAD

**Issue by mariustresor1** [Kinto/kinto#1287]
It would be great to have the following features on the bucket graphical UI :
- Selection of records by checkboxes to delete them by batch 
- Export button to save records into a CSV file
- Filter records by columns properties

**Comment by glasserc** [comment]
I think this is an issue for [kinto-admin](https://github.com/Kinto/kinto-admin/).

**Comment by glasserc** [comment]
CSV export is covered by https://github.com/Kinto/kinto-admin/issues/438 and https://github.com/Kinto/kinto/issues/817.

I've opened https://github.com/Kinto/kinto-admin/issues/441 for "delete by batch".

I've opened https://github.com/Kinto/kinto-admin/issues/442 for "Filter by properties".

Closing this.
