### ISSUE TITLE
server flushed after restart

### ISSUE THREAD

**Issue by TaoufikBouabid** [Kinto/kinto#1294]
Hi, I'm running kinto in my own server, but my issue is when I need to restart kinto after modifying configuration file, all buckets and data are completely removed, is there any solution for that? a backup system for example?

**Comment by TaoufikBouabid** [comment]
command line : docker restart [kinto-container]

**Comment by Natim** [comment]
It is probably because you are using the memory backend. You should change your config to use the Postgresql or Redis backend instead.

**Comment by leplatrem** [comment]
@TaoufikBouabid for Docker with Postgresql the best way to go is docker-compose: docs.kinto-storage.org/en/stable/tutorials/install.html#using-docker-compose

If you encounter problems or documentation is not clear, please let us know! Good luck!
