### ISSUE TITLE
Add SUPPORT file

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1298]
https://github.com/blog/2400-support-file-support

**Comment by S2606** [comment]
@leplatrem what content should we have in SUPPORT file?

**Comment by Natim** [comment]
@S2606 I think something like that: http://kinto.readthedocs.io/en/stable/community.html#communication-channels

**Comment by palash25** [comment]
Is anyone working on this issue. I'd like to take it up. From what I understand the links to the links to various communication channels need to be added in the SUPPORT.md file. Am I right?

_Sent from my Samsung SM-J210F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Natim** [comment]
Yeah don't hesitate to file a PR we will iterate before merging

**Comment by stellargo** [comment]
@Natim could you assign this issue to me? Thanks in advance!
