### ISSUE TITLE
Missing request data in Sentry logs

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1306]
I can't find the attributes of the request that triggered the exception on Sentry. 
It is problematic with crashes like #1303 or #1305 

It should be related to what we did in #1150 

@Natim do you have an idea?

**Comment by Natim** [comment]
It seems that we have more information since the sentry upgrade.

**Comment by leplatrem** [comment]
I'm looking at Sentry 8.17.0 but don't know where to find request path/querystring for example

**Comment by leplatrem** [comment]
![screenshot from 2018-02-14 16-27-56](https://user-images.githubusercontent.com/546692/36212369-0cb8f708-11a4-11e8-8ff5-e563dc15fd25.png)
