### ISSUE TITLE
Add a kinto createsuperuser command

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1315]
With the [accounts plugin](https://github.com/Kinto/kinto/tree/master/kinto/plugins/accounts) it is now possible to handle user directly in Kinto.

However currently the steps are to activate the user creation for everyone, create an administrator account and then enable the creation of account only for that superuser. 

Each configuration change being a server restart.

For deployment it is something tricky to do. It would be convenient to have a `kinto createsuperuser` command that works a bit like the [`django-admin` command](https://docs.djangoproject.com/fr/1.11/ref/django-admin/#createsuperuser) and allow the creation of the super user from the server.

**Comment by mohit2872** [comment]
i would love to help.
