### ISSUE TITLE
The kinto/kinto-server Docker image doesn't contain the kinto-admin

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1327]
Apparently the kinto-server docker image doesn't embedded the kinto-admin files.

**Comment by leplatrem** [comment]
Apparently we do build it though:
https://github.com/Kinto/kinto/blob/master/Dockerfile#L20-L21

**Comment by Natim** [comment]
It is actually worst than that because it can come from the release itself:

If during the review you didn't noticed: ``WARNING: cannot find kinto.plugins.admin.release_hook.after_checkout hook: kinto; skipping...`` then you publish something without the embedded kinto-admin.

In order to do the thing properly:

```
make install-dev
.venv/bin/pip install zest.releaser
.venv/bin/release
```

If you don't do that, then the hook won't be found...

**Comment by leplatrem** [comment]
I submitted a patch to make hooks fail when they can't be imported : https://github.com/zestsoftware/zest.releaser/pull/236

**Comment by Natim** [comment]
zest.releaser 6.12.5 was released with a fix. I shouldn't happen again.

**Comment by Natim** [comment]
Actually this line in the Dockerfile doesn't seems to work: npm run build kinto/plugins/admin; 

```
npm ERR! enoent ENOENT: no such file or directory, open '~/kinto/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '~/kinto/package.json'
```

**Comment by Natim** [comment]
Should be fixed with https://github.com/Kinto/kinto/commit/051c6a92abe1304b18a7d84d7dd0ca93191c0756

**Comment by Natim** [comment]
This build has it: https://hub.docker.com/r/kinto/kinto-server/builds/b43sueeuaeaqswgnawkt8e5/
