### ISSUE TITLE
Add a way to handle HAWK credentials

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1331]
A number of users are trying to figure out a way to prevent replays attack when using Kinto with game programming.

A solution to that problem would be to add a Hawk authentication handler.

**Comment by Natim** [comment]
Refs https://github.com/kumar303/mohawk/

**Comment by leplatrem** [comment]
I don't think this is super easy to implement, but I may be wrong.

Hawk involves crypto, keys etc. I remember implementing something years ago for Daybed.
https://github.com/spiral-project/daybed/blob/6850c766886074e5d6b590a45f985a171efe6339/daybed/tokens.py

Also, how easy is it to introduce Hawk in client libraries?

**Comment by Natim** [comment]
There are a lot of client library for all kinds of programming languages, on the server side we can use mohawk.

**Comment by TDress** [comment]
I'm interested in giving this a try.  I haven't used Hawk but it would be a good learning experience.. just let me know if you'd rather someone else look into it 

here is my understanding of the goal: 
Hawk  on the client side (application server) will need to send the MAC with a nonce to the kinto backend, where we check that the nonce wasn't already used, and then we store it (nonce checking is required).
The user can opt-in to using Mohawk by setting new configuration options: one turns on Mohawk authorization, and the others specify credential values (client_id, secret_key, and algorithm). 

Am I off about anything?

**Comment by TDress** [comment]
This is NOT ready yet.  I wanted to show some code and get feedback.  
I'm using mohawk with nonce checking (the cache layer is used to check if a nonce has been seen).  
In the settings config I added options for only a single client/secret pair, but I'm guessing we want to allow for an arbitrary number.
Response signing (back to the client) is not implemented yet.   
Tests are currently only checking for valid configuration and a 401 auth failure.  I still need to write tests for HAWK auth actually working :-)
Hopefully this is enough to check if I am on the right path.

**Comment by Natim** [comment]
Thanks a lot @TDress for starting that work, I added some comments to your PR.

**Comment by leplatrem** [comment]
See kinto-hawk https://github.com/Kinto/kinto-hawk

Closing here :)
