### ISSUE TITLE
Contributing to Kinto

### ISSUE THREAD

**Issue by vaibhav6451956** [Kinto/kinto#1351]
Hi Developers,

How can I start contributing to this project being a newcomer in the world of python?

Any documentation to set this project up on my local and get on with it?

**Comment by Natim** [comment]
Sure you can find the documentation on installing your local env here:

- http://kinto.readthedocs.io/en/stable/tutorials/install.html#using-the-python-package

Also the contributing guidelines are here:

- http://kinto.readthedocs.io/en/stable/community.html#how-to-contribute

In a nutshell, looks at the issues list and pick one, ask questions if you need more information, then file a PR.
