### ISSUE TITLE
invalid syntax {**key}

### ISSUE THREAD

**Issue by vanzhiganov** [Kinto/kinto#1354]
I have Debian 8 with Python 3 and when I trying to execute command `kinto into` then I have error message:

```
  File "/home/dbset/kinto/kinto/core/resource/__init__.py", line 1177
    record = {**record}
               ^
SyntaxError: invalid syntax
```

Can I replace this string like:

    record = {**key}

to:

    record = dict(**key)

**Comment by Natim** [comment]
Yes you need to use Python > 3.5
