### ISSUE TITLE
Improvements to logging 

### ISSUE THREAD

**Issue by mostlygeek** [Kinto/kinto#1363]
There are two goals we want to achieve here: 

1. Information to aid debugging / troubleshooting
2. Telemetry / measuring of service

**General things we should do:**

1. Log all http responses we generate
    - 2xx, 3xx, 4xx, 5xx ... log it. 
    - if we send a non 5xx, must have `Fields.errno`, `Fields.msg`
    - use `Fields.code` for the HTTP response code
    - always have `Fields.path` and `Fields.method`
2. `Fields.msg` is for humans. Not for computers. If we must dump a python exception put it somewhere else, ie: `Fields.error` 
3. Omit empty fields. At scale all those extra bits start costing storage/io/cpu to skip
4. when logging level is DEBUG, we should log http request headers/params/body (if printable) and response headers/params/body(if printable)
    - this will dump a ton of data but super helpful to flip a flag and see issues

**Specific changes**:

This is what's logged for a successful POST to /v1/batch:

```
{
  "Severity": 6,
  "Logger": "%",                       [1]
  "Type": "subrequest.summary",        
  "Fields": {                          
    "uid": null,                       [2]
    "querystring": {},                 [3]
    "authn_type": null,                [4]
    "lang": "en-US,en;q=0.5",          
    "batch_size": 1,                   
    "path": "/v1/batch",               
    "errno": null,                     [5]
    "message": "subrequest.summary",   [6]
    "method": "POST",
    "agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64..."
  },
  "Pid": 10,
  "Timestamp": 1510145585496232400,
  "Hostname": "ip-<redacted>",
  "EnvVersion": "2.0"
}
```

1. Should be `kintowe`
2. omit if `null`
3. omit if empty
4. omit if `null`
5. should be `0` for success
6. key should be `msg`, not `message`

Here is an error log:

```
{
  "Severity": 6,
  "Logger": "%",
  "Type": "kinto.core.storage.postgresql.pool.QueuePoolWithMaxBacklog",
  "Fields": {
    "message": "Connection <ConnectionWrapper at 0x7f1a95356d48 for psycopg2.extensions.connection at 0x7f1a9d4dd508> exceeded timeout; recycling"
  },
  "Pid": 18,
  "Timestamp": 1510174390025757700,
  "Hostname": "ip-<redacted>",
  "EnvVersion": "2.0"
}
```

1. `Logger` - should be `kintowe`
2. `Fields.message` should be `Fields.msg`
    - ideal would be something human readable with another field `Fields.error` with debugging information
3. `Fields.errno` is missing. Maybe use a code from [errors.py](https://github.com/Kinto/kinto/blob/master/kinto/core/errors.py)
4. `Fields.path` and `Fields.method` are missing. we should log info about the request that was made that caused the error.  Also helps to match up with nginx logs if available

Here's a slightly longer one: 

```
{
  "Severity": 3,
  "Logger": "%",
  "Type": "kinto.core.storage.postgresql.client",
  "Fields": {
    "message": "(psycopg2.IntegrityError) duplicate key value violates unique constraint \"deleted_pkey\"\nDETAIL:  Key (id, parent_id, collection_id)=(<redacted>, , bucket) already exists.\n [SQL: '\\n            WITH deleted_record AS (\\n                DELETE\\n                FROM records\\n                WHERE id = %(object_id)s\\n                  AND parent_id = %(parent_id)s\\n                  AND collection_id = %(collection_id)s\\n                RETURNING id\\n            )\\n            INSERT INTO deleted (id, parent_id, collection_id, last_modified)\\n            SELECT id, %(parent_id)s, %(collection_id)s, from_epoch(%(last_modified)s)\\n              FROM deleted_record\\n            RETURNING as_epoch(last_modified) AS last_modified;\\n            '] [parameters: {'object_id': '<redacted>', 'collection_id': 'bucket', 'last_modified': None, 'parent_id': ''}]"
  },
  "Pid": 8,
  "Timestamp": 1510174685609011700,
  "Hostname": "ip-<redacted>",
  "EnvVersion": "2.0"
}
```

1. Same changes as other error message comments above

**Comment by leplatrem** [comment]
Thanks for this very detailed report!

Some issues come from the lib we use mozilla/mozilla-cloud-services-logger

Some points are trivial improvements.

Some are bugs (eg. `"path": "/v1/batch",` within a `subrequest.summary`, no `error` output with excinfo)

**Comment by glasserc** [comment]
Should we try to log any information about the user who hit the error?

**Comment by mostlygeek** [comment]
> Should we try to log any information about the user who hit the error?

We can log the `uid`. The PII is auto-scrubbed for that key before it's sent downstream to other sources.
