### ISSUE TITLE
duplicate key value violates unique constraint "deleted_pkey"

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#1375]
https://sentry.prod.mozaws.net/operations/kinto-webextensions-prod/issues/688986/

**Comment by Natim** [comment]
One way of fixing that is to add a `ON CONFLICT` rule here L360

```
            query = """
            WITH deleted_record AS (
                DELETE
                FROM records
                WHERE id = :object_id
                  AND parent_id = :parent_id
                  AND collection_id = :collection_id
                RETURNING id
            )
            INSERT INTO deleted (id, parent_id, collection_id, last_modified)
            SELECT id, :parent_id, :collection_id, from_epoch(:last_modified)
              FROM deleted_record
            RETURNING as_epoch(last_modified) AS last_modified;
            """
```

**Comment by glasserc** [comment]
This seems to happen repeatedly for certain IDs. For instance, we noticed that it happens an awful lot for bucket ID `6a1ee6f2-2e10-fa9e-3bc3-25904412946e`. Based on this, I suspected it might be due to bad data rather than any kind of race condition. If the client issues a "delete bucket" request when there's a record in the `deleted` table, we could get this kind of error. On the other hand, we should remove the rows from the `deleted` table when we create or update the bucket, which should happen on almost every request for the `default_bucket` plugin. Anyhow, I asked Wei to look in the production tables and here's what he found: https://irccloud.mozilla.com/pastebin/hvmDywwh/. It isn't clear to me yet how we are getting into this state. I can't reproduce it easily with simple sequential queries. Maybe there was a race condition at first that got us into a bad state but wasn't logged as an error?

**Comment by glasserc** [comment]
According to a query run in production, there are 23 records appearing in both `deleted` and `records`. https://irccloud.mozilla.com/pastebin/HMXMzNFs/

**Comment by leplatrem** [comment]
23 records among how many? Would be interesting to see if they appeared while the service was overwhelmed...

**Comment by glasserc** [comment]
This is caused by #1396.

**Comment by leplatrem** [comment]
Cannot happen since #1386
