### ISSUE TITLE
duplicate key value violates unique constraint "records_pkey"

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#1376]
https://sentry.prod.mozaws.net/operations/kinto-webextensions-prod/issues/689286/

N.B. Not exactly the same as #1375, although perhaps it's related if we're replaying requests or something.

**Comment by Natim** [comment]
This is because create is called with `ignore_conflict=False` somewhere which is the default.

**Comment by Natim** [comment]
`resource_create_object` for the default_bucket should handle this kind of errors.

**Comment by glasserc** [comment]
This should be fixed in 8.0.0.
