### ISSUE TITLE
Should we return 409 instead of 200 for POST if specified id already exists ?

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#140]
As per https://github.com/mozilla-services/kinto.js/issues/14 I tried to raise a 409 on a POST.

The behavior is not the one I was expected:

```
$ echo '{"data": {"title": "Test"}}' | http --verify no POST https://kinto.dev.mozaws.net/v1/buckets/default/collections/tasks/records --auth natim:HTTP/1.1 201 Created
Access-Control-Expose-Headers: Backoff, Retry-After, Alert
Backoff: 10
Connection: keep-alive
Content-Length: 202
Content-Type: application/json; charset=UTF-8
Date: Wed, 15 Jul 2015 09:38:23 GMT
Server: nginx/1.4.6 (Ubuntu)

{
    "data": {
        "id": "1b719cfb-ff5d-4b86-baf6-1e204245a999", 
        "last_modified": 1436953103016, 
        "title": "Test"
    }, 
    "permissions": {
        "write": [
            "basicauth:df93ca0ecaeaa3126595f6785b39c408be2539173c991a7b2e3181a9826a69bc"
        ]
    }
}
```

```
$ echo '{"data": {"id": "1b719cfb-ff5d-4b86-baf6-1e204245a999", "title": "Toto"}}' | http --verify no POST https://kinto.dev.mozaws.net/v1/buckets/default/collections/tasks/records --auth natim:
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Backoff, Retry-After, Alert
Backoff: 10
Connection: keep-alive
Content-Length: 202
Content-Type: application/json; charset=UTF-8
Date: Wed, 15 Jul 2015 09:43:13 GMT
Server: nginx/1.4.6 (Ubuntu)

{
    "data": {
        "id": "1b719cfb-ff5d-4b86-baf6-1e204245a999", 
        "last_modified": 1436953103016, 
        "title": "Test"
    }, 
    "permissions": {
        "write": [
            "basicauth:df93ca0ecaeaa3126595f6785b39c408be2539173c991a7b2e3181a9826a69bc"
        ]
    }
}
```

As you can see when I try a POST on an existing ID, I get the existing record with a 200.

I was expecting getting a 409 Conflict error with the stored record in the detail field.

**Comment by leplatrem** [comment]
This was already discussed a while ago, and we agreed on returning 200 in this case. Discussion can be reopened, but this is definitely not a bug.
 
As the Cliquet docs say, a ``409`` is returned when a field unicity is violated. It won't be the case with Kinto, since there is currently no way to specify field unicity (until schema feature is landed)

**Comment by Natim** [comment]
Could you link the previous discussion issue?

**Comment by Natim** [comment]
If you wish to have a 409 or something telling you that the record already exists, you should use the ``If-None-Match: *`` header in that case the record will be created only if it doesn't already exists.
