### ISSUE TITLE
Refactor the way postgresql.storage.create_from_settings ignores settings.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1410]

**Comment by emamurho** [comment]
@Natim I am wondering what will be in the whitelist. I think everything  in this [map](https://github.com/emamurho/kinto/blob/a47a90b168938d33e9582129730849322f08abd0/kinto/core/__init__.py#L27) excluding the popped values in [client.py](https://github.com/emamurho/kinto/blob/22eb72026a2787e2a80e63b8a97ecbc33bc7e012/kinto/core/storage/postgresql/client.py#L79-L85). Is this the case?

**Comment by Natim** [comment]
Yes

**Comment by leplatrem** [comment]
Fixed by https://github.com/Kinto/kinto/pull/1439 , right?
