### ISSUE TITLE
Flushing a server breaks migration forever

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#1460]
Using the Kinto `flush` plugin wipes the metadata table, which removes information about the storage schema version. This means it is impossible to do a migration, because we no longer have any idea what version to migrate *from*.

There is currently error-handling logic which tries to accommodate for this. It assumes that 1. if the metadata table is empty, then the server was flushed, and 2. if the server was flushed, the schema version in-place is the "current" maximal one. Point 2 is obviously wrong in the case of e.g. local development, where you might flush the server and then, much later, try to build and run a new Kinto version. Point 1 is about to become wrong as we add migration to the permission backend, which may store data in the same metadata table. On top of all of this, the code is not clearly marked as error-handling logic, although it really is.

**Comment by Natim** [comment]
Great catch !!!! I was wondering for a while about why kinto.dev was actually always wrong about that :D
