### ISSUE TITLE
pytest-sugar breaks pytest 3.4.0

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1470]
Refs https://github.com/Frozenball/pytest-sugar/pull/133

**Comment by Natim** [comment]
Refs https://github.com/Kinto/kinto/commit/71ad7adc86465d062fd073c69f98d9de5c366b77

**Comment by leplatrem** [comment]
What's the status of this?

**Comment by Natim** [comment]
It was fixed and release in pytest-sugar 0.9.1

**Comment by glasserc** [comment]
This no longer blocks #1485.
