### ISSUE TITLE
Exposed providers in openid capabilities are not filtered by `multiauth.policies`

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1509]
For example, with:

```ini

kinto.includes = kinto.plugins.openid

multiauth.policies = google

multiauth.policy.google.use = kinto.plugins.openid.OpenIDConnectPolicy
multiauth.policy.google.issuer_url = https://accounts.google.com
multiauth.policy.google.client_id = a
multiauth.policy.google.client_secret = b

multiauth.policy.fxa.use = kinto.plugins.openid.OpenIDConnectPolicy
multiauth.policy.fxa.issuer_url = https://accounts.mozilla.org
multiauth.policy.fxa.client_id = a
multiauth.policy.fxa.client_secret = b
```

`fxa` provider should not be shown in capability.

See misbehaving code (OMG a `print()` statement!)

https://github.com/Kinto/kinto/blob/bf60689ae016a31b8c5bb1955397be46d7b4acca/kinto/plugins/openid/__init__.py#L89-L95

**Comment by bhaveshpoddar94** [comment]
First Timer here. Could I take up this bug?

**Comment by leplatrem** [comment]
Welcome! Yes, of course! Don't hesitate to ask if something is unclear, and don't hesitate to push some draft code as a pull-request if you need early feedback.
Enjoy!

**Comment by bhaveshpoddar94** [comment]
So only the users with multiauth policies assigned should be appended to openid_poilicies?
for example if `multiauth.policies = google`, then only google should be appended.
I am sorry what do you mean by capability?

**Comment by leplatrem** [comment]
The capabilities are some metadata shown in the JSON on the root URL http://localhost:8888/v1/

**Comment by leplatrem** [comment]
As you can see in the faulty code pointed above, we iterate on every settings without looking at the multiauth.policies setting at all. It should be the other way around :)

**Comment by bhaveshpoddar94** [comment]
@leplatrem So from what I understand, if `multiauth.policies = foo`, `m = re.match('multiauth\.policy\.foo\.use', k)`. And if `multiauth.policies = [foo, bar]` then m will be generated for only foo and bar.

**Comment by leplatrem** [comment]
Exactly. Something like (*untested*):

```py
for policy in aslist(settings['multiauth.policies']):
    v = settings.get('multiauth.policy.%s.use' % policy, '')
    if v.endswith('OpenIDConnectPolicy'): 
        ....
```

**Comment by bhaveshpoddar94** [comment]
Got it. Thanks a lot @leplatrem

**Comment by leplatrem** [comment]
@bhaveshpoddar94 Do you need any help?

**Comment by leplatrem** [comment]
@bhaveshpoddar94 ping :) Let us know if we can help or if someone should take over!

**Comment by SushantGahlot** [comment]
Hi, new here. Does this need to be resolved even now? The last comment was three months back

**Comment by leplatrem** [comment]
I don't think it's resolved, and seeing the lack of activity I believe you can take it!
