### ISSUE TITLE
Add creation of buckets in permissions endpoint

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1510]
Currently with these settings:

```ini
kinto.experimental_permissions_endpoint = true
kinto.bucket_create_principals = system.Everyone  # or whatever 
```

I should see the permission to create buckets in http://localhost:8888/v1/permissions

Something like:
```js
{
  "data": [
    {
      "uri": "/buckets",
      "resource_name": "bucket",
      "permissions": [
        "create",
      ],
    }
  ]
}
```

This is because creating bucket is a specific case: it does not involve parents (buckets are top level) and does not involve the permission backend (permission can only be set in `.ini` settings).
Currently we only iterate on existing buckets https://github.com/Kinto/kinto/blob/bf60689ae016a31b8c5bb1955397be46d7b4acca/kinto/views/permissions.py#L91

Would allow to fix https://github.com/Kinto/kinto-admin/issues/401

**Comment by stloma** [comment]
Thanks for the detailed response!

It looks like `allowed_resources` in the following snippet will always evaluate to false as `from_settings` is `{'': 'bucket:create'}`, so there will be no intersection.

https://github.com/Kinto/kinto/blob/110ace2ea0688c3abfdec8e8f471a540a502fba1/kinto/views/permissions.py#L87

Secondly, I'm getting a key error on `bucket:create` on this line:

https://github.com/Kinto/kinto/blob/110ace2ea0688c3abfdec8e8f471a540a502fba1/kinto/views/permissions.py#L123

I've been digging through the permissions a bit and don't see a `bucket:create` key in `perms_descending_tree`, which seems like it would fix the problem.

In any case, I'll keep going through this and hopefully I'm not too off base here :)

Thanks!

**Comment by leplatrem** [comment]
> It looks like allowed_resources in the following snippet will always evaluate to false as from_settings is {'': 'bucket:create'}, so there will be no intersection.

Yes that's why I was proposing to put it before looking at `allowed_resources` (bucket creation is not linked to any parent resource, as opposed to records creation, collections, groups... etc.)

> I've been digging through the permissions a bit and don't see a bucket:create key in perms_descending_tree, which seems like it would fix the problem.

Yes indeed, and if I look at `PERMISSIONS_INHERITANCE_TREE` (where the `perms_descending_tree` is built from) there seems to be everything we need:

https://github.com/Kinto/kinto/blob/110ace2ea0688c3abfdec8e8f471a540a502fba1/kinto/authorization.py#L26-L28

Enjoy!

**Comment by stloma** [comment]
May I ask, what is the reason for seeing a "create" permission vs a "bucket:create" permission in the response from http://localhost:8888/v1/permissions? Since it is a top-level object, it needs an unbound permission?

For example, this is working:

```
'bucket:create': {
	'': ['bucket:create', 'create']
}
```

However, it responds with:

```
{
	"uri": "/buckets",
	"resource_name": "bucket",
	"permissions": [
		"bucket:create",
	],
}
```

Finally, I'm assuming it is desired behavior that with only `kinto.experimental_permissions_endpoint = true`, that an authenticated user should see the create permissions on the /buckets uri?

I'm asking because it's failing several tests in `test_views_permissions.py` so I just wanted to make sure before rewriting them and adding my own :)

**Comment by leplatrem** [comment]
I think you already went far enough for me to get lost :) 

First, let's agree on how it should look like.

Currently, this is how it comes out on `GET /permissions` for a single bucket:

```js        
        {
            "bucket_id": "bid",
            "id": "bid",
            "permissions": [
                "write",
                "read",
                "collection:create",
                "group:create"
            ],
            "resource_name": "bucket",
            "uri": "/buckets/bid"
        }
```
So we can see that we have `"uri": "/buckets/bid"` and the perm `collection:create`. 
We don't have `"uri": "/buckets/bid/collections"` and the perm `create`.

So I think it would be consistent to have `"uri": "/"` and the perm `bucket:create`, instead of `"uri": "/buckets"` and the perm `create` or `"uri": "/buckets"` and the perm `bucket:create`.

What do you think?

Once you define well what we expect, you may have to touch several unit tests to match the new behavior yes :)

Also, don't hesitate to open a pull-request with your work-in-progress, so that we can iterate on real code ;)

Thanks for being so thorough!

**Comment by stloma** [comment]
Awesome, thanks for the direction and the suggestion of a work-in-progress pull-request.

My thought on the response mirrors yours; I think it makes sense for a `bucket:create` perm and `"uri": "/buckets"` (partially because there's already a home view mapped to /).

I'll make some finalizations and submit soon.
