### ISSUE TITLE
Switch to pipenv ?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1517]
- pipenv is the [official tool recommended on python.org](https://twitter.com/kennethreitz/status/936239842039619584)
- pipenv = pip + virtualenv + virtualenvwrapper
- Verifies dependencies hashes (.lock file)
- Handles default/dev dependencies
- Has a nice CLI
- Mimics Cargo

Basically it would just consist in:
- [ ] Changing parts of the `Makefile`
- [ ] Changing contributing / installation docs

**Comment by leplatrem** [comment]
@peterbe could you please confirm that switching to Renovate instead of Pyup would allow us to use pipenv?

**Comment by peterbe** [comment]
Still an open issue https://github.com/renovatebot/renovate/issues/2212

**Comment by leplatrem** [comment]
Note: Dependabot supports Pipenv :)

**Comment by leplatrem** [comment]
How does Pipenv play with tox?

**Comment by leplatrem** [comment]
Archiving old issues.

See also #2445 #1921
