### ISSUE TITLE
Introduce the notion of user directory ?

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#154]
We need a way for a user to share data with another user.

In order to do so, the user needs to be able to map an email address to a userid.

One way to do so is to add the email address in the list of principals.

So that the user can do something like that:

```
{"permissions": {
        "read": ["email:alexis@mozilla.com"]
}}
```

**Comment by Natim** [comment]
The good thing behind that is that then it is possible to share things with people that doesn't use the application yet.

**Comment by leplatrem** [comment]
I guess we can close this issue, in favor of Portier #933 #994 . Please reopen if I'm wrong.
