### ISSUE TITLE
revoke permissions on a record

### ISSUE THREAD

**Issue by brunobord** [Kinto/kinto#155]
Following the [First step tutorial](https://kinto.readthedocs.org/en/latest/tutorial.html#sync-and-share-data-between-users), I've managed to give Bob read access on Alice's task.

I've tried to figure out a way to revoke this permission, but I've failed to: it looks like PATCHing the record would only work by *adding* permissions, and not removing any of them.

Use cases:

* changing a "write" permission to a "read" one,
* revoking a permission for a specific user because she behave very badly.

```
$ echo '{"permissions": {"read": []} }' | http PATCH http://127.0.0.1:8888/v1/buckets/todo/collections/tasks/records/2b2fd6ad-5521-46d5-8712-5a27e42dd31f -v --auth 'alice:alicepassword'

PATCH /v1/buckets/todo/collections/tasks/records/2b2fd6ad-5521-46d5-8712-5a27e42dd31f HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Authorization: Basic YWxpY2U6YWxpY2VwYXNzd29yZA==
Connection: keep-alive
Content-Length: 31
Content-Type: application/json
Host: 127.0.0.1:8888
User-Agent: HTTPie/0.9.2

{
    "permissions": {
        "read": []
    }
}

HTTP/1.1 200 OK
Access-Control-Expose-Headers: Backoff, Retry-After, Alert, Content-Length
Content-Length: 316
Content-Type: application/json; charset=UTF-8
Date: Tue, 04 Aug 2015 21:24:32 GMT
Etag: "1438722779308"
Last-Modified: Tue, 04 Aug 2015 21:12:59 GMT
Server: waitress

{
    "data": {
        "description": "Alice task",
        "id": "2b2fd6ad-5521-46d5-8712-5a27e42dd31f",
        "last_modified": 1438722779308,
        "status": "todo"
    },
    "permissions": {
        "read": [
            "basicauth:a103c2e714a04615783de8a03fef1c7fee221214387dd07993bb9aed1f2f2148"
        ],
        "write": [
            "basicauth:9be2b51de8544fbed4539382d0885f8643c0185c90fb23201d7bbe86d70b4a44"
        ]
    }
}
```

this one led to an error (it's expecting a list, for it's looping on it in cliquet):

```
echo '{"permissions": {"read": null} }' | http PATCH http://127.0.0.1:8888/v1/buckets/todo/collections/tasks/records/2b2fd6ad-5521-46d5-8712-5a27e42dd31f -v --auth 'alice:alicepassword'
```

1. is there a way to revoke a permission?
2. if it does exist, I think it should be mentioned in the documentation

**Comment by ametaireau** [comment]
Currently, the only way to remove a permission is to issue a PUT on the associated endpoint. Using a PATCH will only add members.

This is not the final API and we are currently working on the semantics to use in order to delete principals.

One of the proposal that was done was to keep the endpoint like it is right now, and add new sub-endpoints on which it would be possible to:

- issue PATCH with `{"remove": ["tartenpion"]}` on  e.g. `/records/{id}/permissions/read`;
- issue DELETE on e.g. `/records/{id}/permissions/read/tartenpion`.

(Discussion is still open on this)

**Comment by Natim** [comment]
So after having discuss this with @leplatrem I am going to implement it like this:

 - PATCH can let you change some fields of a resource, but the value is immutable

This means that the new PATCH will replace the permission list with the new one.

```http
$ echo '{"permissions": {"read": []} }' | http PATCH http://127.0.0.1:8888/v1/buckets/todo/collections/tasks/records/2b2fd6ad-5521-46d5-8712-5a27e42dd31f -v --auth 'alice:alicepassword'

PATCH /v1/buckets/todo/collections/tasks/records/2b2fd6ad-5521-46d5-8712-5a27e42dd31f HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Authorization: Basic YWxpY2U6YWxpY2VwYXNzd29yZA==
Connection: keep-alive
Content-Length: 31
Content-Type: application/json
Host: 127.0.0.1:8888
User-Agent: HTTPie/0.9.2

{
    "permissions": {
        "read": []
    }
}

HTTP/1.1 200 OK
Access-Control-Expose-Headers: Backoff, Retry-After, Alert, Content-Length
Content-Length: 316
Content-Type: application/json; charset=UTF-8
Date: Tue, 04 Aug 2015 21:24:32 GMT
Etag: "1438722779308"
Last-Modified: Tue, 04 Aug 2015 21:12:59 GMT
Server: waitress

{
    "data": {
        "description": "Alice task",
        "id": "2b2fd6ad-5521-46d5-8712-5a27e42dd31f",
        "last_modified": 1438722779308,
        "status": "todo"
    },
    "permissions": {
        "write": [
            "basicauth:9be2b51de8544fbed4539382d0885f8643c0185c90fb23201d7bbe86d70b4a44"
        ]
    }
}
```

It seems to be the behavior @brunobord was expecting.
