### ISSUE TITLE
Schema validation at bucket/collection level too

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1555]
Currently if there's a `schema` attribute in the collection metadata, we validate the posted records.
See
https://docs.kinto-storage.org/en/stable/api/1.x/collections.html#collection-json-schema

I propose that when we set `collection:schema`, `group:schema` or `record:schema` in the bucket metadata, we validate the collection, group or record respectively :)

Use case: the «per bucket» configuration of Firefox remote settings where every record in every collection could have a `target` field that is validated against the same schema

**Comment by saurabhShrivastava1995** [comment]
Working on this

**Comment by leplatrem** [comment]
@ssWitcher I'm sorry I hadn't seen your comment :( I needed this for something we have in production and jumped on it!
I hoped you hadn't spent too much energy on it :(
