### ISSUE TITLE
Question - possible to do atomic "find and update" through API?

### ISSUE THREAD

**Issue by ronhanson** [Kinto/kinto#1597]
Hi,

Is it possible to do a query that would retrieve and update an object at the same time?

Something like : 
    *Give me one "pending" object and set its new status to "running" (so that it is only me that will retrieve the object).*

Is that possible to do actually?

If not, would it be possible to create a plugin that would allow such thing? And where would you advise me to take a fist look.

Thanks in advance.

Ronan

**Comment by Natim** [comment]
I am not sure to understand exactly the use case.
You can probably do that using the batch endpoint.
However when you update a record you always get its new value.

If you know that the object is in the pending state then if you use a `PATCH status=running` you will retrieve that object.

In anycase you can always create a plugin if the usecase differs.

Can you tell us more about your data flow?

**Comment by ronhanson** [comment]
Hi @Natim - thanks for instant reply,

Well, it is like if I would use sort of a queueing system. Someone will add a "job" to be consumed, and someone else would consume the job. 
But if I do :

    SELECT id WHERE status=pending            # returns ID1
    UPDATE status=running WHERE id=ID1

and that these calls are not atomic, 2 or more consumers might retrieve the ID1 and therefore duplicate the job and also override what the other just updated.

I need atomic select and update, but not based on ID. This is not something that Restful APIs usually give the ability to do so.

In SQL, it would relate to a SELECT FOR UPDATE statement. In MongoDB it is a findAndModify statement.

I guess with transaction we would be near from what I want, but I don't know if I can use the retrieved ID variable in a second update statement - not sure I am clear in that sentence.

Thanks for your answer.

**Comment by Natim** [comment]
For atomic updates in Kinto we use a CAS mecanism.

When you get the record you will get a unique Etag header.

If you do you PATCH with the `If-Match: "EtagValue"` you will get a 412 if can another worker already updated the task.

I would do a get and a patch with the header just after and ignore the task if the worker get a 412 answer on the PATCH.

**Comment by Natim** [comment]
Note that you might encounter this issue: https://github.com/Kinto/kinto/issues/1407

Are you sure that Kinto qualifies for a task queuing service? Why not use [redis.BLPOP](https://redis.io/commands/blpop) or RabbitMQ instead?

**Comment by ronhanson** [comment]
Well, the system I build is a long running task running/queueing service, and it uses mongodb + a dummy naive custom built API to access it. Thus I am interested in Kinto as it has many more features. Using a push to redis and a BLPOP was something I was planning to dig into but you confirm me it would be a good solution. About the double PATCH request, I am a bit uncertain but it might also be really valid indeed. 

2 additionnal questions : 

 - How hard is it to add a storage like MongoDB? I see that kinto-redis seems pretty much inactive and not much used at the moment.  
 - How hard would you think it would to add a custom rest API request like /<collection>/findAndUpdate ? I guess it would need a storage class function more and some added http methods which makes it hard for one plugin.

Thanks again for ideas and great help.

**Comment by Natim** [comment]
> How hard is it to add a storage like MongoDB?

For the MongoDB storage backend, all the tests are already written and there is a Python lib for it.
So it is a matter of a couple hours I guess. You can give it a try I think.

> kinto-redis seems pretty much inactive and not much used at the moment.

What makes you think **kinto-redis** is not used? I know multiple users myself.
Fortunately kinto.core.storage API doesn't change often so we don't need to update kinto-redis often :) However note that the redis storage like the memory storage don't handle transaction rollbacks which might cause issues with some plugins (the quota plugin for instance)

>  How hard would you think it would to add a custom rest API request like //findAndUpdate ?

The issue with `/findAndUpdate` is that it is not REST anymore but JSON-RPC like.
However you can definitely create a plugin that would expose such a view.

You can look at https://github.com/Kinto/kinto-elasticsearch/blob/master/kinto_elasticsearch/views.py or 
https://github.com/Kinto/kinto-attachment/blob/master/kinto_attachment/views/services.py examples.

In this end it should be as complex as writting a cornice view.

Regarding your question about adding a storage function while doing this you might need to fix #1407 which would be merged directly at the kinto repository level.

**Comment by glasserc** [comment]
I guess I wouldn't be averse to something like `PATCH /v1/buckets/my-bucket/collections/my-collection/records?status=open&_limit=1`. But we don't support it now, and I am extremely hesitant to endorse the use of Kinto as a queue. I think using a queue as a queue is going to be better for you than using a database as a queue. I don't know if this is still a problem, but I had a co-worker from a couple jobs ago who worked for a company who had built a queue around MongoDB and constantly ran into issues where the database indices gradually got less and less efficient as records moved forward in time. I think they ended up having to rebuild indices periodically.

My personal opinion about kinto-redis is that it doesn't support the level of query you need in order to avoid race conditions. I'd expect the same thing from kinto-mongodb. But maybe for some applications that's OK? I guess if losing your data were a big problem, you wouldn't be using MongoDB anyhow.

**Comment by leplatrem** [comment]
What's the status of this? Is it a «won't fix»?

**Comment by Natim** [comment]
I will close this since this was a question and I guess @ronhanson has got all the answer we can give for it.

We can open a new issue about implementing @glasserc suggestion if the use-case arise in the future.
