### ISSUE TITLE
recent `pip` required for 2.4.0+

### ISSUE THREAD

**Issue by phrawzty** [Kinto/kinto#162]
Should we note that as of 2.4.0 a very recent version of `pip` is required for installation? I'm thinking specifically of the tutorial section.

**Comment by leplatrem** [comment]
I wish we will fix this. It was not the case with the previous versions. It might come from the fact we changed the tooling for packaging (from zest releaser to twine).

Regarding documentation, it would be worth just mentioning something like a side-note : «*it is not bad to have a recent pip installed, run ``pip install -U pip`` if yours is a couple of years old»

**Comment by leplatrem** [comment]
This was resolved by @Natim and @ametaireau in the last versions of cliquet.

I could install the stack with pip 1.5.6 :)

Thanks for the feedback !
