### ISSUE TITLE
No proper stacktrace with py.test and webtest ?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#163]
With **py.test** and**webtest** I find it very hard to understand errors in my views.
I have no proper stacktrace in my view:

![capture d ecran de 2015-08-21 11 26 26](https://cloud.githubusercontent.com/assets/546692/9405387/980b48f2-47f7-11e5-8557-36f29fe35441.png)

Whereas with nose, it is less colourful, but look I can know what is going on:
![capture d ecran de 2015-08-21 11 28 46](https://cloud.githubusercontent.com/assets/546692/9405421/cfb5563a-47f7-11e5-8092-9ac156c2639a.png)

Could we improve that ?

**Comment by Natim** [comment]
I totally agree about that. @magopian any ideas?

**Comment by leplatrem** [comment]
Using ``--tb=native`` is not essentially better :|
![capture d ecran de 2015-09-10 13 08 22](https://cloud.githubusercontent.com/assets/546692/9786780/0986318e-57bd-11e5-94b9-42b87211c760.png)

**Comment by magopian** [comment]
The issue is that by default pytest does not capture the logs (only the output). So the logs (giving more information about the failure) were not displayed on test failure. Using `pytest-capturelog` fixes that (see #191)
