### ISSUE TITLE
Link to Slack doesn't work

### ISSUE THREAD

**Issue by webwurst** [Kinto/kinto#1638]
Following this link https://slack.kinto-storage.org/ from the [documentation](http://kinto.readthedocs.io/en/stable/community.html) gives me:
> 403 Forbidden

**Comment by glasserc** [comment]
This should be OK now, right? I got someone to fix it short-term, but long-term there's still some question about where it should live (and how).

**Comment by webwurst** [comment]
Sorry, my fault :) I had already registered some time ago, it seems. So all good now.
