### ISSUE TITLE
user id is prefixed with auth0 when loging in OpenID Connect with Google provider

### ISSUE THREAD

**Issue by magopian** [Kinto/kinto#1652]
The context: https://github.com/Kinto/kinto-admin/pull/509#discussion_r190574395

The issue is present when there's both an `auth0` and a `google` provider for OpenID Connect:

```
multiauth.policies = auth0 google

multiauth.policy.google.use = kinto.plugins.openid.OpenIDConnectPolicy
multiauth.policy.google.issuer = https://accounts.google.com
multiauth.policy.google.client_id = <google client id>
multiauth.policy.google.client_secret = <google client secret>
multiauth.policy.google.userid_field = email

multiauth.policy.auth0.use = kinto.plugins.openid.OpenIDConnectPolicy
multiauth.policy.auth0.issuer = https://minimal-demo-iam.auth0.com
multiauth.policy.auth0.client_id = <auth0 client id>
multiauth.policy.auth0.client_secret = <auth0 client secret>
multiauth.policy.auth0.userid_field = email
```

In such a case, here's the redirect chain:
```
307 http://localhost:8888/v1/openid/google/login?callback=....&scope=openid%20email

200 https://accounts.google.com/o/oauth2/v2/auth?client_id=...&response_type=code&scope=openid+email&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Fv1%2Fopenid%2Fgoogle%2Ftoken%3F&state=...

200 https://accounts.google.com/signin/oauth?client_id=...&as=...&destination=http://localhost:8888&approval_state=...&xsrfsig=...

200 https://accounts.google.com/_/signin/oauth?authuser=1&hl=fr&_reqid=58049&rt=j

307 http://localhost:8888/v1/openid/google/token?state=...&code=...&authuser=1&session_state=...&prompt=none#
```

And here's the final result:
<img width="718" alt="screen shot 2018-05-25 at 15 29 48" src="https://user-images.githubusercontent.com/167767/40550431-58157ab6-603a-11e8-9f41-410eadc51dff.png">

Now if I change the `multiauth.policies` to `google auth0` (reversed the order), then in that case loging in with "OpenID Connect (Google)" works well, but "OpenID Connect (Auth0)" will fail:
<img width="671" alt="screen shot 2018-05-25 at 16 40 02" src="https://user-images.githubusercontent.com/167767/40550515-95be306a-603a-11e8-8274-837459057f61.png">

**Comment by leplatrem** [comment]
The following seems to happen: 

1. user authenticates to Auth0 with Google identity
1. user obtains an Access Token that has openid scope, and thus allows to fetch user info
1. user sends access token to obtain user id from root URL
1. kinto iterates the configured policies to validate the access token, and tries to fetch the user info for that
1. since access token obtained from Auth0 allows to fetch profile from Google, kinto identifies the user with the google policy
1. kinto admin sees that user tried to identify with auth0 but obtains a user id prefixed with google and considers that something is wrong

Since Auth0 is a kind of bridge to Google (and other identity providers), I don't think it makes sense to have both configured, and we could consider it a limitation of the server.

What do you think?

**Comment by magopian** [comment]
I don't see if there's any use case that would need both configured, indeed. Maybe we could add a note to the documentation about this limitation, and revisit this in the future if needed?

**Comment by fpiedrah** [comment]
Hi! Is this task still available? I would like to take it.

Should I just add a new section in the troubleshooting.rst describing this issue? or is there any other suggestion on where to place this?

**Comment by Natim** [comment]
Are you sure this is not specific to the kinto-admin rather than kinto?

**Comment by fpiedrah** [comment]
I'm not sure. should I try to replicate the issue and see if it is kinto the one where the error originates from?
Because if it's kinto-admin specific we could move this issue to the kinto-admin repo.

**Comment by Natim** [comment]
@fpiedrah ok I had a look at this issue and I guess you are correct.

We could say something like: "Make sure that two authorization policy matches a given token, because in that case you might have incoherent user ID behaviours"

**Comment by leplatrem** [comment]
I think the documentation changes that @fpiedrah submitted were enough and that we can close this. Do you all agree?

**Comment by Natim** [comment]
:+1:
