### ISSUE TITLE
Move up to fstrings

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1659]
[![fstrings](https://pbs.twimg.com/media/DeTEtf4XUAAH8J8.jpg)](https://twitter.com/mariatta/status/1001141610107699200)

I guess this means going up to Python 3.6 and losing Python 3.5 support.

**Comment by peterbe** [comment]
Calm down! :)

I use Ubuntu 16.04 on my Digital Ocean servers and they only have 3.5 by default.

**Comment by Natim** [comment]
With Bionic the last LTS 18.04 it is  Python 3.6.5
With the previous artful (17.10)  Python 3.6.3
With the previous LTS xenial (16.04) Python 3.5.1 (note that it is totally possible to install Python 3.6 with the deadsnake PPA)

**Comment by Natim** [comment]
Google App Engine is using Python 3.6.4

**Comment by DrFaustie** [comment]
Is this something we are still interested in doing?

**Comment by Natim** [comment]
This means we will drop support for Python 3.5 and start supporting Python 3.6 only. Since we already decided to move to Black I guess we are now fine with the idea. You can probably start the work although we might not merge it right away but we will eventually.

**Comment by DrFaustie** [comment]
My only concern is if some of the logic and references regarding the f strings is changed during this time, it might end up very unwieldy to merge. Or perhaps Github has ways to account for this problem?

**Comment by Natim** [comment]
Yes git is pretty handy to merge this kinds of conflicts so I wouldn't worry too much about that.

**Comment by DrFaustie** [comment]
What would be good practice here? Should I start a pull request immediately and work on that, or simply submit one when I've finished most of it?

**Comment by Natim** [comment]
I would use grin to list all the files I need to handle:

```
$ grep -R \\\.format\\\( kinto
```
- [ ] kinto/config/__init__.py
- [ ] kinto/schema_validation.py
- [ ] kinto/core/scripts.py
- [ ] kinto/core/openapi.py
- [ ] kinto/core/__init__.py
- [ ] kinto/core/events.py
- [ ] kinto/core/utils.py
- [ ] kinto/core/cache/postgresql/__init__.py
- [ ] kinto/core/storage/memory.py
- [ ] kinto/core/storage/exceptions.py
- [ ] kinto/core/storage/postgresql/__init__.py
- [ ] kinto/core/storage/postgresql/client.py
- [ ] kinto/core/storage/postgresql/migrator.py
- [ ] kinto/core/storage/testing.py
- [ ] kinto/core/statsd.py
- [ ] kinto/core/initialization.py
- [ ] kinto/core/authentication.py
- [ ] kinto/core/resource/__init__.py
- [ ] kinto/core/resource/model.py
- [ ] kinto/core/resource/__pycache__/model.cpython-36.pyc
- [ ] kinto/core/resource/schema.py
- [ ] kinto/core/resource/viewset.py
- [ ] kinto/core/permission/memory.py
- [ ] kinto/core/permission/postgresql/__init__.py
- [ ] kinto/core/authorization.py
- [ ] kinto/core/views/heartbeat.py
- [ ] kinto/core/views/errors.py
- [ ] kinto/core/views/batch.py
- [ ] kinto/core/testing.py
- [ ] kinto/plugins/quotas/scripts.py
- [ ] kinto/plugins/quotas/listener.py
- [ ] kinto/plugins/admin/build/static/js/main.6eacca3d.js.map
- [ ] kinto/plugins/admin/build/static/js/main.6eacca3d.js
- [ ] kinto/plugins/accounts/scripts.py
- [ ] kinto/plugins/accounts/__init__.py
- [ ] kinto/plugins/accounts/views.py
- [ ] kinto/plugins/accounts/authentication.py
- [ ] kinto/plugins/openid/__init__.py
- [ ] kinto/plugins/openid/views.py
- [ ] kinto/plugins/default_bucket/__init__.py
- [ ] kinto/plugins/history/listener.py
- [ ] kinto/authorization.py
- [ ] kinto/views/records.py
- [ ] kinto/views/permissions.py
- [ ] kinto/views/groups.py
- [ ] kinto/__main__.py

And then tick the checkboxes :dagger:

**Comment by Natim** [comment]
> Should we drop support for Python 3.5?

Yes that's definitely the question to answer, I don't think it will hurt anyone to do so to be honest.

**Comment by peterbe** [comment]
Ubuntu 16.04 still uses 3.5 and 16.04's end-of-life is [April 2021](https://wiki.ubuntu.com/Releases). And [as you said](https://github.com/Kinto/kinto/issues/1659#issuecomment-436185425) 3.5 is still supported until Sept 2019. 

But it's already getting old. 3.7 is already a thing. Is f-strings the only benefit of dropping 3.5? I love f-strings and their clearly very performant but does that performance matters in the IO world of talking to a SQL database? Also, is it worth the pain of preventing some from upgrades just for f-strings? :)

If you drop support for 3.5, you can simply say to the people stuck in Ubuntu 16.04 etc. to just not upgrade any more. But what if there are security releases. Does Kinto promise any support at all? Are they documented?

Mozilla is Kinto's biggest consumer and Mozilla uses Docker almost everywhere for deployments so it's not at the mercy of slow-moving Linux distributions. 

By the way, beyond f-strings, one place that needs a lot of attention when dropping 3.5 is the [.travis.yml file](https://github.com/Kinto/kinto/blob/master/.travis.yml).

**Comment by DrFaustie** [comment]
If f-strings are the only benefit of dropping 3.5 then this wouldn't be a very pressing concern, as there is plenty of time before support needs to be dropped. That said, i believe there are some other issues open? I'm not too familiar though, so that's better for others to discuss.

On the other hand, it's not a bad idea to get the work done in preparation from when it is necessary to move on.

**Comment by Natim** [comment]
I guess if someone needs a security backport for Python 3.5 in the future they can file a PR and we will gladly make a release for them. Generaly since Python 3.5+ people are trying to follow along with Python upgrade especially since Python 3.7 adds a bunch of performance improvments.

**Comment by peterbe** [comment]
I'm not a core contributor to Kinto but I would recommend with leaving this issue and filing a new one that lists the pros and cons. I can think of some to get started:

**Pros**
- Only having to support 3.6 and 3.7 makes the surface area of debugging and support smaller for the core team. 
- f-strings are more performant than `string.format`.
- Fewer Python environments in TravisCI means for faster feedback on CI from pull requests. 
- 3.6 and above preserve the insertion order in dicts. (But only 3.7 guarantees it)

**Cons**
- Drops support for LTS Linux releases that are stuck on 3.5. E.g. Ubuntu 16.04.
- Security releases become extremely hard to provide to people stuck on old pre-3.6-only platforms. 


What else? Are there any other backports required that we'd be able to drop in favor of built-ins?

**Comment by Natim** [comment]
> Are there any other backports required that we'd be able to drop in favor of built-ins?

We would be able to rely more on async/await but we don't have any ioloop for now.

**Comment by Natim** [comment]
> Drops support for LTS Linux releases that are stuck on 3.5. E.g. Ubuntu 16.04.

I wouldn't consider it a blocker since it is really handy to install Python > 3.5 on Ubuntu 16.04 see https://askubuntu.com/a/865569/11333
