### ISSUE TITLE
OpenID payload cache uses the wrong cache key

### ISSUE THREAD

**Issue by peterbe** [Kinto/kinto#1660]
The `cache_key` becomes the same for every access token due to this bug: https://github.com/Kinto/kinto/blob/e1e0d6be0024418fd100210901f9d2ca06344fe1/kinto/plugins/openid/__init__.py#L51
No matter what the `hmac_tokens` variable is the `cache_key` always becomes `'openid:verify:%s'`.

**Comment by leplatrem** [comment]
![](https://media.giphy.com/media/nspvD8XYqUxP2/giphy.gif)
