### ISSUE TITLE
kinto.plugins.accounts problem while deploying on Heroku

### ISSUE THREAD

**Issue by JEricaM** [Kinto/kinto#1669]
Hi,
I'm trying to add **kinto.plugins.accounts** to my kinto project hosted on Heroku, and I followed the instructions of the documentation here http://docs.kinto-storage.org/en/stable/api/1.x/accounts.html

This is my **kinto.ini** file (the parte that I edited like the guide says):
```
kinto.includes = kinto.plugins.default_bucket
                kinto.plugins.admin
                kinto.plugins.accounts
               
multiauth.policies = account
multiauth.policy.account.use = kinto.plugins.accounts.authentication.AccountsAuthenticationPolicy

# Allow anyone to create accounts.
kinto.account_create_principals = system.Everyone

# Set the session time to live in seconds
kinto.account_cache_ttl_seconds = 30
```

When I deploy the edited .ini file, I get this error: 
`AttributeError: module 'kinto.plugins' has no attribute 'accounts'`

This is my full stacktrace: https://pastebin.com/p0fBeZcL 

Furthermore, if I try to execute from my Heroku dyno, the command 
`kinto create-user --ini /etc/kinto.ini --username admin --password mypassword`
gives me error that the command `kinto create-user `don't exist.

How can I fix it? 
Thank you in advance.

**Comment by glasserc** [comment]
Oh, I didn't realize we had to update our packaging for heroku, but I see that https://github.com/Kinto/kinto-heroku shows a dependency on kinto 6.0. The accounts plugin was introduced in 7.0.0. I'll open a PR on kinto-heroku to bump the version. Sorry about this!

**Comment by JEricaM** [comment]
Thank you so much for your answer :)

**Comment by glasserc** [comment]
I merged the kinto-heroku PR. As far as I know, that's all I need to do -- I don't have to cut a release or anything like that. Please give it a try and let me know if it works or not!

**Comment by JEricaM** [comment]
Thank you, I tried and the accounts endpoint works good!!
I have only another little problem, when I run from the Heroku dyno the command  (I have ` kinto.ini ` out of the etc folder, so I don't have `/etc/kinto.ini` but only `kinto.ini `) 
`kinto create-user --ini kinto.ini --username admin --password mypass` 
I have this error:
`sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string ‘’`
This is my full stacktrace https://pastebin.com/Ek6rDD45

Thank you in advance.

**Comment by glasserc** [comment]
That looks like it's somehow failing to instantiate the Postgres storage backend. I'm guessing your `kinto.storage_url` setting is an empty string. Otherwise I'm not sure either..

**Comment by JEricaM** [comment]
Thank you, I'll check asap!

**Comment by glasserc** [comment]
Hi, what's the status on this? Can I close it?

**Comment by JEricaM** [comment]
Sorry for the late.

I solved by creating the account through endpoint not with the kinto create-user command.
So you can close the issue.

Thank you again!
