### ISSUE TITLE
Unhandled JSON pointer errors

### ISSUE THREAD

**Issue by stloma** [Kinto/kinto#1685]
When setting a schema on resources, unresolvable references are not checked upon creation.

When creating a resource that is checked against that schema, a `RefResolutionError` is raised by `jsonschema` and not caught.

For example, creating the schema:

```json
{"data": {
    "schema": {
      "properties": {
        "address": { "$ref": "#/definitions/address" }
      }
    }
  }
}
```

POST data:

```json
{ "data": {
   "address": "seattle"
  }
}
```

This will crash the server with a 500 error and the following message:

```shell
"Unresolvable JSON pointer: %r" % fragment
jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'definitions/address' 
```

I can work on this, I was just wondering what you all felt the approach should be.

It can either check when creating the schema or upon each invocation of it (i.e., POST data). The only slight trouble I can see with checking and not allowing unresolvable schema is that the schema can be a url, so if it is not resolving at the time of creation, it will fail.

That seems fair to me; does that seem like a reasonable fix?

**Comment by glasserc** [comment]
Yes if a URL is permitted then I think it's OK to fail when checking it.
