### ISSUE TITLE
docker deployment missing kinto.ini

### ISSUE THREAD

**Issue by geomapdev** [Kinto/kinto#1686]
Docker build fails with the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/kinto/kinto.ini'

Am I missing a step? This occurs with both the docker and docker-compose build instructions:
http://docs.kinto-storage.org/en/stable/tutorials/install.html#using-docker
http://docs.kinto-storage.org/en/stable/tutorials/install.html#using-docker-compose

**Comment by Natim** [comment]
The Docker file is suposed to create this kinto ini file: https://github.com/Kinto/kinto/blob/master/Dockerfile#L23

I assume you are using the lastest image?

Ok I found the error, it is because the cache_backend is asking for its value.

```
Select the cache backend you would like to use: (1 - postgresql, 2 - redis, 3 - memcached, default - memory) 

Traceback (most recent call last): File "/usr/local/bin/kinto", line 11, in <module> load_entry_point('kinto', 'console_scripts', 'kinto')() File "/app/kinto/__main__.py", line 151, in main answer = input(prompt).strip() EOFError: EOF when reading a line`
```

Thank you for noticing.
