### ISSUE TITLE
Crash in Postgres backend when querystring contains NUL character (0x00)

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1704]
![screenshot from 2018-07-02 10-40-31](https://user-images.githubusercontent.com/546692/42153765-64ff0752-7de4-11e8-81f6-2531fd8719cd.png)

:laughing: 

![screenshot_2018-07-02 valueerror a string literal cannot contain nul 0x00 characters](https://user-images.githubusercontent.com/546692/42153904-b238b82e-7de4-11e8-8dbd-5e9bbef7efed.png)

**Comment by leplatrem** [comment]
For those who want to have a look at this, this could be avoided by adding some safety check here for example:

https://github.com/Kinto/kinto/blob/21bac9b787639da76b38f535aa34e1f0391e48e9/kinto/core/utils.py#L106-L117

**Comment by Cnidarias** [comment]
And to add to this, what would the expected result be?

**Comment by leplatrem** [comment]
> Hey, if this is still open I would like to work on this

Great!

>  where would be the best place to put a test for this?

I guess that somewhere around here:
https://github.com/Kinto/kinto/blob/f9e3c6ea2c2a44e855c16cf2969dd73200ac94ac/tests/core/test_views_errors.py#L114

> And to add to this, what would the expected result be?

If the querystring contains a bad character, the view should return 400
