### ISSUE TITLE
Record added twice in storage testing suite

### ISSUE THREAD

**Issue by zeeshanabid94** [Kinto/kinto#1711]
https://github.com/Kinto/kinto/blob/a7f94773610566ec91f2d6172da910fb73fa84ef/kinto/core/storage/testing.py#L186

Here you are checking if the record already exists. This raises an error as it should as the record was already there. But, the error should be caught in the assert statement. This just causes the test to fail because the record is added twice.

**Comment by leplatrem** [comment]
Thanks for the report!

> But, the error should be caught in the assert statement. This just causes the test to fail because the record is added twice.

I didn't understand that part :( What do you mean by *caught in the assert statement* ?

**Comment by zeeshanabid94** [comment]
Nevermind. Closing the issue. I was looking at it the wrong way.
