### ISSUE TITLE
Use Python module as config instead of INI file?

### ISSUE THREAD

**Issue by alexryabkov** [Kinto/kinto#1729]
I'm reading Kinto documentation. And I see there's an option to specify the settings via an INI file.
Is there any specific reason behind this? IMO, we could use .py module (for example, as we do in Django-based projects) as a config instead of INI file, so INI parser won't be needed. 

Thanks in advance!

**Comment by glasserc** [comment]
The specific reason is because we're built on Pyramid, and deployed with [pserve](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/startup.html), which is configured using a PasteDeploy `.ini` file. I don't think there's a real architectural reason why it *has* to be this way, though.

**Comment by stloma** [comment]
I think another reason `.ini` configurations are useful is for non-developers to configure the project. That is, rather than editing source code, an `ini` file is a bit more user friendly.

**Comment by alexryabkov** [comment]
Thank you guys for explanation, appreciate it!

**Comment by alexryabkov** [comment]
Could somebody mark this issue as "question" please?
