### ISSUE TITLE
Implement quotas in Kinto

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#173]
When building Syncto I have seen that Firefox Sync handle quota and return the remaining space on device with a header.

   X-Weave-Quota-Remaining: 125

https://github.com/mozilla-services/server-syncstorage/blob/d961d1012e2c48921180934c369b136b83916a7d/syncstorage/views/decorators.py#L133-L137

I wonder if I can map this to ``Quota-Remaining`` for Kinto and open a Kinto.js specific error for quota.

**Comment by leplatrem** [comment]
This looks like a feature request : add quota management in Kinto !
It could be a very relevant feature indeed, especially with public Kinto servers :)

Once we have an actual use-case, we could provide some specs here... Should quotas be defined at the collection level, per user, in config, in bucket/collections objects ? 

Meanwhile, for SyncTo, maybe you could just pass the header along. And in see if Kinto.js has an elegant way to introduce failures on custom response attributes like headers...

**Comment by leplatrem** [comment]
Could you explain why you closed please ?

**Comment by ametaireau** [comment]
I think that it is a useful feature to provide for Kinto, if we want to have servers open to the world at some point :-) Reopening for now, we can close it if/once we all agree this feature isn't useful.

**Comment by Natim** [comment]
I closed because your answer answered my question.
We can rename the issue to implement Quota in Kinto but as we don't have the use case yet we can also create a new one then.

**Comment by tarekziade** [comment]
We have a use case for Webextensions.

We need to implement the quotas defined in https://developer.chrome.com/extensions/storage#property-sync  - where Kinto is used as a Key-Value storage (so one collection/addon and one bucket/user I guess)

On the server side we should add:

-  **QUOTA_BYTES**: The maximum total amount (in bytes) of data that can be stored in sync storage, as measured by the JSON stringification of every value plus every key's length.

- **QUOTA_BYTES_PER_ITEM**: The maximum size (in bytes) of each individual item in sync storage, as measured by the JSON stringification of its value plus its key length.

- **MAX_ITEMS**:  	The maximum number of items that can be stored in sync storage.

**Comment by leplatrem** [comment]
The main question is: is it enough to have it by bucket or per collection? Or should it be a complex combination of both?

Some insights on how it could work:

* Add a new built-in plugin (`kinto.plugins.quotas`)
* Introduce a new capability with exposed quotas values 
* Register a `AfterResourceChanged` subscriber that listens to every action on the record resource
* Use an internal storage dataset to track stats ([see example](https://github.com/Kinto/kinto-attachment/blob/0.6.0/kinto_attachment/utils.py#L146-L152))
* On create, sum the bytes, on delete subtracts, on update sum the difference between old/new. (*note: postgresql internal JSONB is going to be smaller but what counts is API input/output*)
* On create/update, check if the body size exceeds setting `size_per_item`
* On every new response provide the current stats in headers (?)
* On create/update, when one condition fails, raise the appropriate http exception

Then in a second iteration we can imagine defining the settings in the parent bucket etc.

Related #360

**Comment by Natim** [comment]
I would go for the per collection quota and then if we want a per bucket quota it can just be the sum of all per collection quota.

**Comment by tarekziade** [comment]
> Use an internal storage dataset to track stats

Why not as a collection metadata ?

**Comment by Natim** [comment]
After discussing that with @tarekziade over IRC, tarek's proposition is to add the value alongside with `id` and `last_modified`:

```
{
  "id": "certificates",
  "last_modified": 1470061473832,
  "items_count": 2,
  "storage_size": 400
}
```

**Comment by tarekziade** [comment]
Yeah, my rationale is that ``items_count`` and ``storage_size`` will be used by the client (or the quota plugin) like the ``last_modified`` field and that it's valuable to have them as a core value alongside ``last_modified``.
