### ISSUE TITLE
Clean up event listener initialization

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#1755]
https://github.com/Kinto/kinto/blob/1af1f00e7e106b741ca8e94d7fd6de98e1442a47/kinto/core/initialization.py#L470-L475

Shouldn't this `return` be a `continue`? Actually I don't really find the code very easy to read..

**Comment by leplatrem** [comment]
> Shouldn't this return be a continue?

Excellent catch! It should be a `continue`! It's a buuuug :)


> Actually I don't really find the code very easy to read..

Oh yeah I agree!
