### ISSUE TITLE
Remove WebOb deprecation warnings

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1779]
```
/home/mathieu/Code/Mozilla/kinto/.venv/lib/python3.6/site-packages/webob/acceptparse.py:1297: DeprecationWarning: The behavior of .best_match for the Accept classes is currently being maintained for backward compatibility, but the method will be deprecated in the future, as its behavior is not specified in (and currently does not conform to) RFC 7231.
  DeprecationWarning,
/home/mathieu/Code/Mozilla/kinto/.venv/lib/python3.6/site-packages/webob/acceptparse.py:1187: DeprecationWarning: The behavior of .__contains__ for the Accept classes is currently being maintained for backward compatibility, but it will change in the future to better conform to the RFC.
  DeprecationWarning,

```

TODO:
* track usage (most likely in [cornice](https://github.com/Cornices/cornice/search?q=best_match&unscoped_q=best_match))
* switch to recommeded way :)

**Comment by abk-code** [comment]
In order to fix this, do we need to install Py3.6? I don't see these warnings in 
`.venv/lib/python3.5/site-packages/webob/acceptparse.py` file.

**Comment by leplatrem** [comment]
I don't think so, look at this job on Travis with python 3.5:
https://travis-ci.org/Kinto/kinto/jobs/435094504

**Comment by leplatrem** [comment]
https://github.com/Pylons/webob/blame/master/src/webob/acceptparse.py#L1005-L1010 ?

**Comment by abk-code** [comment]
Thanks, I will pick this one up. But may need some help.
https://github.com/Pylons/pyramid/pull/3326 : That has similar 
issues for a different method. I wonder what is the recommended
way. Also using iPython3 (or jupyter) is there a way to see this warning?
(Basically trying to recreate, apply a fix and  unit test before I  implement
the code for Kinto)

**Comment by abk-code** [comment]
I wonder if this is also related:
https://bugzilla.redhat.com/show_bug.cgi?id=1625599#c11

**Comment by leplatrem** [comment]
> Thanks, I will pick this one up
Awesome!

Apparently you're right, Pyramid might be affected.
But we could start with cornice (we own the repo):
https://github.com/Cornices/cornice/search?q=best_match&unscoped_q=best_match

> Also using iPython3 (or jupyter) is there a way to see this warning?
(Basically trying to recreate, apply a fix and unit test before I implement
the code for Kinto)

I see them when I run the tests `tox -e py36`. Don't bother about unit tests for that case. We can also see them on TraviCI jobs output

**Comment by abk-code** [comment]
Ok, thanks. Where do I see the right method to use instead of this old method?
Specifically for 'best_method'

**Comment by leplatrem** [comment]
If I understand well what is said here : https://github.com/Pylons/webob/blame/master/src/webob/acceptparse.py
We should use `.acceptable_offers()`

**Comment by abk-code** [comment]
Thank you. How do I unit-test to make sure my changes are fine?

**Comment by leplatrem** [comment]
> How do I unit-test to make sure my changes are fine?

In that case I don't think we really need unit-tests. The tests coverage in Cornice is 100% I think.

**Comment by leplatrem** [comment]
See https://github.com/Cornices/cornice/pull/493

**Comment by glasserc** [comment]
I think this can be closed now that we have the new cornice version.

**Comment by glasserc** [comment]
We still seem to have the warnings and indeed cornice still uses best_match.

**Comment by glasserc** [comment]
Refs #1936, https://github.com/Cornices/cornice/pull/499. This should be OK now.
