### ISSUE TITLE
Add a clear cache command to kinto

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1785]
For debugging purposes mainly we want to be able to clear the cache on time to time

**Comment by Pac23** [comment]
@Natim @leplatrem has this been done ? if not can i work on this ?

**Comment by Pac23** [comment]
I will then @leplatrem asap. Can you provide a rundown of some sort, this would be my first open source contribution to a big project. Any pointers that you might want to add? I did understand that I simply have to make the changes in the argparse section and add the command as an argument.

**Comment by leplatrem** [comment]
I would suggest adding a `flush-cache` command, that would call the `.flush()` method of the cache backend.

It should not be too hard to get it working. For testing, you can look at:

https://github.com/Kinto/kinto/blob/e19ff82e38dd263d5f6480652d4ed2d02ff50557/tests/core/test_scripts.py#L13-L14

Don't hesitate to open a pull-request very early in the process, this way it's easier to help :)

Enjoy!

**Comment by Pac23** [comment]
@leplatrem thank you for the info,expect a pr soon.

**Comment by Pac23** [comment]
@leplatrem i have made a pr,i think i am on the right track as far as the parsing goes, not sure if registry.cache.flush() is the function to actually call.
