### ISSUE TITLE
Migrate to JSONschema Draft v7

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1808]
Currently we use Draft4. The library that we use supports Draft7

https://json-schema.org/specification.html

The idea would be:
* to use `Draft7Validator` instead of `Draft4Validator` (nothing more...)
* list main changes and add links in CHANGELOG (see spec release notes)
* check compatibility with kinto-admin

**Comment by peterr101** [comment]
I would like to take on this issue if it's still open?

**Comment by leplatrem** [comment]
Yes sure!
