### ISSUE TITLE
Invalid account_create_principals key

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1813]
The `account:create` check_permission code is looking at `account_account:create_principals` settings key rather than `account_create_principals`

**Comment by leplatrem** [comment]
Does it mean it hadn't worked since day 1? I'm surprised, I'm pretty sure that not put `account_create_principals = system.Everyone` in settings does not allow to create accounts...

**Comment by Natim** [comment]
> Does it mean it never worked?

I don't think so because it used to work for sure.
