### ISSUE TITLE
Raise error instead of returning 404 on __version__ if version file is missing

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1841]
https://github.com/Kinto/kinto/blame/master/kinto/core/views/version.py#L49

suggested by @peterbe 

4XX errors are client errors. In that case, if the file is not on the server, the client is not guilty ;)

**Comment by peterbe** [comment]
Django has a great "solution" to this, the perfectly named [`django.exceptions.ImproperlyConfigured` exception](https://docs.djangoproject.com/en/2.1/ref/exceptions/#improperlyconfigured).

**Comment by leplatrem** [comment]
Pyramid has the same `ConfigurationError` :)

**Comment by DrFaustie** [comment]
wouldn't something like `raise VersionNotFound` do the trick?

**Comment by leplatrem** [comment]
> wouldn't something like raise VersionNotFound do the trick?

Whatever, we just need to raise an exception with a clear message that the server administrators would receive when a client tries to access this endpoint if the file does not exist...

**Comment by DrFaustie** [comment]
I'll do this in an hour or so, no worries!

**Comment by benjamindhimes** [comment]
Is this issue still open?

**Comment by DrFaustie** [comment]
Sorry, I've been busy.
I made a pull request here: https://github.com/Kinto/kinto/pull/1860

If I messed up, feel free to take it
