### ISSUE TITLE
Question: .NET client?

### ISSUE THREAD

**Issue by zakaluka** [Kinto/kinto#1864]
Hello,

My search skills are failing me today, so I hope the community here can help.  

I am trying to find a client for .NET (any language - C#, F#, etc.).  Does anyone know of an existing one?  If not, does anyone know of something close to use as a starting point?

Thank you.

**Comment by glasserc** [comment]
I've never heard of anyone using Kinto in a .NET stack. I don't have a lot of experience with that stack so I'm afraid I can't really make any recommendations for starting points.
