### ISSUE TITLE
Moving up to fstrings

### ISSUE THREAD

**Issue by DrFaustie** [Kinto/kinto#1884]
It's good to keep open a checklist, even if we aren't interested in dropping support for older versions just yet

- [x] `kinto/config/__init__.py`
- [x] `kinto/schema_validation.py`
- [x] `kinto/core/scripts.py`
- [x] `kinto/core/openapi.py`
- [x] `kinto/core/__init__.py`
- [x] `kinto/core/utils.py`
- [x] `kinto/core/cache/postgresql/__init__.py`
- [x] `kinto/core/storage/memory.py`
- [x] `kinto/core/storage/exceptions.py`
- [x] `kinto/core/storage/postgresql/client.py`
- [x] `kinto/core/storage/testing.py`
- [x] `kinto/core/statsd.py`
- [x] `kinto/core/initialization.py`
- [x] `kinto/core/resource/model.py`
- [x] `kinto/core/resource/schema.py`
- [x] `kinto/core/permission/memory.py`
- [x] `kinto/core/views/heartbeat.py`
- [x] `kinto/core/views/errors.py`
- [x] `kinto/core/views/batch.py`
- [x] `kinto/core/testing.py`
- [x] `kinto/plugins/quotas/scripts.py`
- [x] `kinto/plugins/quotas/listener.py`
- [x] `kinto/plugins/openid/__init__.py`
- [x] `kinto/plugins/openid/views.py`
- [x] `kinto/plugins/default_bucket/__init__.py`
- [x] `kinto/plugins/history/listener.py`
- [x] `kinto/authorization.py`
- [x] `kinto/views/records.py`

# Partially Complete
- [ ] `kinto/core/events.py`
- [ ] `kinto/core/storage/postgresql/__init__.py`
- [ ] `kinto/core/storage/postgresql/migrator.py`
- [ ] `kinto/core/authentication.py`
- [ ] `kinto/core/errors.py`
- [ ] `kinto/core/resource/__init__.py`
- [ ] `kinto/core/resource/viewset.py`
- [ ] `kinto/core/permission/postgresql/__init__.py`
- [ ] `kinto/core/authorization.py`
- [ ] `kinto/plugins/accounts/scripts.py`
- [ ] `kinto/plugins/accounts/__init__.py`
- [ ] `kinto/plugins/accounts/views.py`
- [ ] `kinto/plugins/accounts/authentication.py`
- [ ] `kinto/views/permissions.py`
- [ ] `kinto/views/groups.py`
- [ ] `kinto/__main__.py`

_Originally posted by @Natim in https://github.com/Kinto/kinto/issues/1659#issuecomment-436208399_

**Comment by leplatrem** [comment]
I don't understand this issue, how is it different than #1659?

**Comment by DrFaustie** [comment]
I thought it may be better to have a checklist of tasks on the top, since it was decided we could at least start work on this. If others think it's unnecessary we can of course close this.

**Comment by leplatrem** [comment]
I think it makes sense to have this exact post as a comment in the issue there, or as the description of a pull-request that starts the work

**Comment by DrFaustie** [comment]
That makes sense. I'll make a pull request once my initial tests pass.
