### ISSUE TITLE
Displaying username while asking for password confirmation

### ISSUE THREAD

**Issue by DrFaustie** [Kinto/kinto#1885]
Is this intended? Wouldn't displaying something else make a bit more sense?

https://github.com/Kinto/kinto/blob/d08b36b7be86c6342f2f50b4e19ef8a2b4799e5e/kinto/plugins/accounts/scripts.py#L38-L41

**Comment by leplatrem** [comment]
We are open to suggestions!

**Comment by leplatrem** [comment]
I don't understand what this issue means. 

SSH does this:
```
$ ssh user@server.org
user@server.org's password: 

....
```

Please re-open with more details if relevant ;)
