### ISSUE TITLE
Should we use slack / gitter as a communication channel?

### ISSUE THREAD

**Issue by almet** [Kinto/kinto#190]
Hi!

It seems that some other projects are relying on slack and/or gitter for their communication channel, because it's more intuitive to use than the traditional mailing list or irc.

It seems to be possible to enable two-ways syncing between slack and irc for instance, so it could make sense to enable it.

What do you think?

**Comment by leplatrem** [comment]
I would be in favor of enabling Slack with two-ways sync with IRC. Even though I am not delighted with that proprietary drain :]

**Comment by ametaireau** [comment]
Exactly the same story for me, hence the question.

**Comment by leplatrem** [comment]
Note for later:
* http://www.mattermost.org
* https://zulip.org

And @n1k0 was mentioning something like «distort» :)

**Comment by n1k0** [comment]
https://discordapp.com/ ;)

**Comment by Natim** [comment]
Why we should not use Slack at all: https://twitter.com/amontalenti/status/660849837982674945

**Comment by ametaireau** [comment]
Ideally, using IRC would be the preferred way to connect. However, IRC is too complex for newcomers and they don't tend to stay in there. Plus IRC does require you to stay connected to access the backlog (well, it's possible to use hacks, but that's what they are: hacks).

Zulip ([zulip.org](zulip.org)) seems to be one of the alternatives that it is possible to self-host. However, it [unfortunately takes a large amount of memory to run](https://github.com/zulip/zulip/issues/34)

The other proposed solution, mattermost seems to be a good alternative. We need to try it out!

**Comment by Natim** [comment]
I do not think IRC backlog is a feature for newcomers. Also facilitating access to IRC is.
I thought the link to http://chat.mibbit.com/?server=irc.mozilla.org&channel=%23storage in the documentation was actually enough.

**Comment by ametaireau** [comment]
I think we should put IRC aside, as it isn't a great way to be in communication. For instance, none of the Outreachy is currently there, nor any of the occasional contributors.

**Comment by Natim** [comment]
PouchDB did a link between Slack and IRC, I am not a big fan of using Slack but if it helps people why not.
Also I am not sure if I would not worth to help them to use IRC instead since it is an OpenSource protocol rather than a proprietary solution.

**Comment by ametaireau** [comment]
The thing being: how do you help them?

**Comment by Natim** [comment]
> How do you help them?

By making it as easy to get started and use as Slack seems to be.

**Comment by gfortaine** [comment]
Did you think about SwellRT ?

http://swellrt.org

"This is the only decentralized-federated framework to build collaborative applications."

**Comment by Natim** [comment]
Here at the coworking space they are using Slack, but the IRC integration works like a charm.
It seems slack is really trendy and help people to get in touch so maybe it could be a good alternative.

**Comment by almet** [comment]
I like the idea to keep the canonical way to contact us to be IRC on freenode: it's a network run for projects like us, and it's not baked by a company (which can disappear any time).

However, as slack seems to be a convenient way for people to contact us, it might be a good idea to do a duplex, maybe using https://github.com/hoodiehq/slack-irc-duplex and then proposing the two ways to contact us ?

**Comment by enguerran** [comment]
I saw [you were speaking about mattermost](https://github.com/Kinto/kinto/issues/190#issuecomment-149332070) and on may 10, framasoft announced an installation on their server called [framateam](https://framateam.org/). What do you think about?

And the _one more thing_, [mattermost can connect to IRC channel](http://www.mattermost.org/mattermost-v1-1-open-source-slack-compatible-integrations/) with [matterbridge](https://github.com/42wim/matterbridge).

**Comment by leplatrem** [comment]
Slack was setup, closing
