### ISSUE TITLE
Remove psycopg deprecation warnings

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1905]
```

  /home/mathieu/Code/Mozilla/kinto/.venv/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
    """)
  /home/mathieu/Code/Mozilla/kinto/.venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py:204: SADeprecationWarning: The 'postgres' dialect name has been renamed to 'postgresql'
    loader = self.auto_fn(name)

```

**Comment by fpiedrah** [comment]
I've been taking a look at this error, I've installed **psycopg2-binary==2.7.6.1** but did not solve the issue. The only thing that worked out was to get an older version of the library **psycopg2==2.7.3.2** but I do not like the idea. Any other thoughts on how to solve this issue?

**Comment by Natim** [comment]
You need to install **psycopg2-binary** and to remove **psycopg2** from the venv as well.

**Comment by cmdlinebeep** [comment]
Just hoping to point out to others who search on this error message.
I was already using psycopg2-binary, and was still getting the issue.

For me, the issue was resolved by just changing my Postgres DB path from:
"postgres://<user:pass>@localhost:5432/<db_name>"
to:
"postgresql://<user:pass>@localhost:5432/<db_name>"

**Comment by Natim** [comment]
I am surprise @cmdlinebeep because this has been fixed more than a year ago in that commit: https://github.com/Kinto/kinto/commit/8809f6b67c8aeeec8adbe126a21fc02e6582d655

**Comment by cmdlinebeep** [comment]
Yeah, I'm not sure why.  I'm not making any claims other than my version of psycopg2-binary is well past that:  psycopg2-binary==2.8.5
If I make no other change than adding 'sql' to the end of 'postgres', the deprecation warning goes away.  Hope it helps someone else.
