### ISSUE TITLE
Usage of default bucket is costly

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#192]
Because we want underlying bucket and collections objects to be created implicitly when using the `default` bucket, we knew we'd have some overhead. 

However, we implemented the implicit creation using Pyramid *subrequests*, and this is particularly inefficient.

If I disable the implicit creation, a local simulation load test with postgresql goes from `35 RPS` to `53 FPS` (~50% win).

If this default bucket is used in a `/batch`, it means two levels of cascaded subrequests are performed.

> This is problematic especially because default is the main bucket of kinto.js

I could get some major improvement (from 35 to 48 RPS) by replacing the current subrequests with a direct interaction on the storage backend:

```python
# views/buckets.py

def create_bucket(request, bucket_id):
    """Create a bucket if it doesn't exists."""
    bucket_put = (request.method.lower() == 'put' and
                  request.path.endswith('buckets/default'))

    if not bucket_put:
        request.matchdict['id'] = bucket_id
        service = Bucket(request)
        try:
            service.collection.create_record({'id': bucket_id})
        except exceptions.UnicityError:
            pass


def create_collection(request, bucket_id):
    subpath = request.matchdict.get('subpath')
    if subpath and subpath.startswith('collections/'):
        collection_id = subpath.split('/')[1]
        collection_put = (request.method.lower() == 'put' and
                          request.path.endswith(collection_id))
        if not collection_put:
            request.matchdict['bucket_id'] = bucket_id
            request.matchdict['id'] = collection_id
            service = Collection(request)
            try:
                service.collection.create_record({'id': collection_id})
            except exceptions.UnicityError:
                pass
```

But I now wonder why we don't just do something like this:

```python
class Bucket(resource.ProtectedResource):
    def __init__(self, *args, **kwargs):
        super(Bucket, self).__init__(*args, **kwargs)
        if self.record_id == 'default':
            digest = hmac_digest(hmac_secret, request.prefixed_userid)
            self.record_id = text_type(UUID(digest[:32]))
```
I think I asked already, but I can't remember. We should write it in the buckets code :)

**Comment by Natim** [comment]
Let's do that then :+1:

**Comment by leplatrem** [comment]
Following up on this: I changed from `default` to a specific bucket in the load tests. And went from  35 to 75 RPS. 
That means the `default` bucket is currently 55% slower than other buckets.

I start a PR to tackle this step by step.

**Comment by ametaireau** [comment]
Nice investigation.
