### ISSUE TITLE
Kinto not able to start - Regression due to jsonschema Draft7Validator

### ISSUE THREAD

**Issue by almet** [Kinto/kinto#1926]
#1808 introduced a regression, because the Draft7Validator is not currently released by the jsonschema package (they introduced it in master but it's not released yet)

Solution is either to depend on the master branch of jsonschema (not recommended I guess) or revert this change back until a new version is issued.

**Comment by leplatrem** [comment]
Workaround is to install the `jsonschema` lib with `--pre` option

**Comment by leplatrem** [comment]
This should be ok now with 11.2.1
