### ISSUE TITLE
KeyError: 'No such route named collection-record'

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1938]
I guess our last updates of master broke something. Is it cornice update?

https://travis-ci.org/Kinto/kinto-http.js/jobs/468031385

Last release seems good though.

**Comment by leplatrem** [comment]
The route is now called `collection-record`, this is due to #710 

That means we need a fix in kinto-attachment :)

**Comment by glasserc** [comment]
Refs https://github.com/Kinto/kinto-attachment/pull/158.

**Comment by leplatrem** [comment]
I released a new version kinto-attachment
