### ISSUE TITLE
Notion of transaction for the whole request/response cycle

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#194]
After discussing with @phrawzty, we should probably expose clearly a limitation of the current implementation.

> There is no notion of transaction for the whole cycle request/response.

Which basically means that every interactions with the backends are performed atomically and not rolled back if something wrong happens afterwards, before serving the response.

I believe we can be pretty confident in the python code that is executed between storage interaction and returning the response. However we can't guarantee *«per-request integrity»* when performing several backend operations.

This mainly applies:
* `/batch` requests
* requests that interact with both `storage` and `permissions` backend (eg. requests with both `data` `permissions` attributes)
* **edit**: Purging tombstones when deleting bucket/collections

It is especially problematic with non idempotent requests, like `POST` or `PUT` using ETag headers (404 on delete could still be ignored).

One way of fixing this issue would be:
* Creating a `savepoint` when the request kicks in
* Rollback if the response status is not 2XX
* Commit otherwise.
* Rewriting the *subquest* approach for the batch

Meanwhile, we should use this issue to think about it and find a comforting way to present the currrent limitation in the documentation :)

**Comment by tarekziade** [comment]
side note: once this is implemented, it would be cool to have transaction-level events (start/success/failure) with a transaction number (uuid?) attached

**Comment by leplatrem** [comment]
Note: This was landed in cliquet master (2.11.dev).

**Comment by leplatrem** [comment]
Done in 1.9.0
