### ISSUE TITLE
Remove the delete-collection command 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1959]
This command was introduced to fix a very specific use-case a long time ago where we had created a collection with an invalid ID. It could thus not be deleted via the HTTP API. 

I think we can remove it.

(from #1953)

**Comment by Natim** [comment]
Yes it makes sense.

**Comment by AnanthKumarVasamsetti** [comment]
Hi, can I take up this bug and work on. As I started my open source contribution this would be my first fix

**Comment by leplatrem** [comment]
Welcome onboard! Go ahead ;)
