### ISSUE TITLE
Pagination documentation is unclear

### ISSUE THREAD

**Issue by almet** [Kinto/kinto#196]
It is hard to find information about pagination in the Kinto repository. We should make it easier to find.

**Comment by nikkisquared** [comment]
I'd like to work on this. I've looked up the sections on pagination, but I'm not sure how or where they could be better referenced.

**Comment by Natim** [comment]
The question you can ask yourself is, when landing on the documentation home page and looking for getting paginated records, what would you like to do to find it really quickly?

**Comment by Natim** [comment]
I tried to do it and I ended-up on the [record-get page](http://kinto.readthedocs.org/en/latest/api/records.html#records-get)

Where there is nothing about filtering/paginating or anything yet (after 3 clicks)
Although there is a link to [resource-endpoints](http://kinto.readthedocs.org/en/latest/api/cliquet/resource.html#resource-endpoints)

But I think we can add a list of link for direct access from the [records-get page](http://kinto.readthedocs.org/en/latest/api/records.html#records-get)

**Comment by nikkisquared** [comment]
That helps me a lot. I'll start with adding more to the records-get page, and then see about making better references in previous pages.

**Comment by nikkisquared** [comment]
Sorry, I won't be able to do this. I'm struggling with the time zone between me and the kinto team, I find myself unable to do much without being able to get feedback over irc as I work.

**Comment by ametaireau** [comment]
Ah, too bad to hear this @nikkisquared. Feel free to reach out tu us whenever you can/want about kinto.

**Comment by leplatrem** [comment]
Closing because there is now a *paginate* entry in docs. http://kinto.readthedocs.io/en/stable/api/1.x/pagination.html
