### ISSUE TITLE
OpenID authentication plugin is missing a profile view

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1989]
When validating the token, the plugn is fetching the profile, but there are no endpoint available to fetch this info: https://github.com/Kinto/kinto/blob/master/kinto/plugins/openid/__init__.py#L74

I would be in favor of adding a `/v1/openid/google/profile` view in order to grab the username and the profile_pic of the user.

This information might also be added in the `user` field of the `/v1/` endpoint. What do you think?

**Comment by leplatrem** [comment]
the `user` field in the root URL would be nice, but probably not as easy as the other option ;)

**Comment by Natim** [comment]
I would be willing to try that, it makes a lot of sense to me.
