### ISSUE TITLE
How to recover an account password?

### ISSUE THREAD

**Issue by nukeador** [Kinto/kinto#1998]
Hello,

We are trying to figure out how to recover an account password, basically we want to reset the admin password without having access to this admin account.

Thanks!

/cc @MichaelKohler @johngian @leplatrem

**Comment by leplatrem** [comment]
So the easiest wasy I can suggest is to create another account, give it privileges via the `.ini` file.

```ini
# Allow anyone to create accounts.
kinto.account_create_principals = system.Everyone
# Set user 'account:admin' and 'account:recover' as the administrator.
kinto.account_write_principals = account:admin account:recover
```
Create the `recover` account (using `httpie`):
```
$ echo '{"data": {"password": "secret"}}' | http PUT :8888/v1/accounts/recover -v
```
Overwrite the `admin` password:

```
$ echo '{"data": {"password": "new-password"}}' | http PUT :8888/v1/accounts/admin -a recover:secret
```
Delete the `recover` account:

```
$ http DELETE :8888/v1/accounts/recover -a admin:new-password```
``` 

Let me know how it goes!

**Comment by MichaelKohler** [comment]
Thanks, we could recover the password.
