### ISSUE TITLE
CSP error while trying to load kinto-admin 1.23 from /v1/admin/

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#2000]
https://catalog.chefclub.tools/v1/admin/

![image](https://user-images.githubusercontent.com/229453/51763766-97e3fc80-20d3-11e9-9d79-edb4d941f641.png)

![image](https://user-images.githubusercontent.com/229453/51763787-a3cfbe80-20d3-11e9-9add-a8a8c30fe0a2.png)

**Comment by leplatrem** [comment]
hmm.. 

https://github.com/Kinto/kinto/blob/8455861294cf35963e24946d301e5c04daa6f3f7/kinto/plugins/admin/public/index.html#L6-L7

**Comment by Natim** [comment]
It looks like this line doesn't allow for the inline script that get's added in the html build file.
