### ISSUE TITLE
kinto-redis should not be a requirement to build docs

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#2038]
Redis is a plugin and maintained in a separate repository because it is optional. Requiring it to build docs defeats that optionality, and automatically cross-linking to it in the docs makes it seem more official and supported than it actually is. We should probably scour the docs for any reference to Redis and maybe remove it or at least turn it into a link to the kinto-redis repository.

**Comment by palutlaanirudh** [comment]
I would like to contribute to this issue. Can you guide me on how I may help?

**Comment by glasserc** [comment]
Hi @palutlaanirudh, the problem is that the docs make several references to kinto-redis, which is a plugin. This leads to a situation where the generated docs include the Redis backends as though they were first-class, built-in components instead of an optional plugin. See https://kinto.readthedocs.io/en/latest/core/cache.html for an example of what I mean. This also leads to the unfortunate situation where you have to install the kinto-redis plugin to build the docs, instead of just being able to build them from the kinto source. In other words, kinto has a dependency on a plugin, which is bad. A plugin can depend on kinto but not the other way around -- if kinto requires it, it isn't a plugin.

To help, I'd like to see a patch that reviews the places where Redis/kinto-redis is mentioned in the Kinto docs (or anywhere else in this repository!). I think any usage of kinto-redis should be changed to a "link" -- instead of including kinto-redis in the kinto docs, we should include links to the kinto-redis project for those who are interested. Ideally we would be able to remove kinto-redis from the requirements needed to build the docs.

To get started, I'd encourage you to clone the Kinto project and try running the tests and building the docs. Then try making some changes and rebuild the docs to make sure you get the results you expect. Don't hesitate to say something if you get stuck or have problems. We hang out sometimes on IRC or on Slack if you need help.

**Comment by yatinmaan** [comment]
@palutlaanirudh Hey, are you still working on this ?
