### ISSUE TITLE
WebPush integration

### ISSUE THREAD

**Issue by almet** [Kinto/kinto#210]
[WebPush](http://www.w3.org/TR/push-api/) allows client to pass along an URL that will trigger a push notification on their side.

Supporting WebPush allows to notify User-Agents that *something* happens. I see a few things to investigate further:

- Fine-grained notifications: clients should tell when notifications should be sent their way. For instance, they might only be interested in updates to data they created.
- Permissions (related to the first point). We shouldn't notify people that don't have access to the information, otherwise we might leak some data.

**Comment by Natim** [comment]
If we can link on a bucket/collection/records the event we are subscribing, the user ID as well as the PUSH url, then we are all set.

On an event, we can go through impacted notification, get the principal list for each user and then decide if we should do the push according to the permission backend.

Hopefully we can handle that asynchronously.

**Comment by ametaireau** [comment]
Also, it should be possible to have different push urls for one person, depending on the collection.

**Comment by leplatrem** [comment]
Just to get some inspiration... The Pusher ecosystem is really simple to setup ! 
https://github.com/pusher/pusher-http-python#triggering-events

**Comment by leplatrem** [comment]
https://github.com/Kinto/kinto-webpush/ was implemented \o/
