### ISSUE TITLE
Instructions to deploy in leading cloud providers GCP, AWS and Azure

### ISSUE THREAD

**Issue by chaitanya9186** [Kinto/kinto#2114]
Please provide instructions to deploy Kinto in different cloud providers. Thanks

**Comment by glasserc** [comment]
I don't consider this part of the project documentation requirements. Even well-known and mature projects such as PostgreSQL and CouchDB do not provide deployment instructions for any third-party platform vendor.

**Comment by leplatrem** [comment]
The problem with that kind of documentation is that it gets obsolete quickly...

In case you're interested to start some documentation for this, I believe you could use the wiki.
