### ISSUE TITLE
ConfigTest is a little bit intermittent

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#2129]
In https://github.com/Kinto/kinto/pull/2125, ConfigTest failed because the timestamp it generated in the test was different from the timestamp generated in the `kinto.config.init` function. (I restarted the test and merged it when it passed.) This is possible when the test runs just before the end of a second, causing the two calls to `strftime` to refer to two different seconds.

**Comment by leplatrem** [comment]
Instead of this strict comparison: 

https://github.com/Kinto/kinto/blob/24f5d838f606a4f68d8940eb061a4d85fc97c5d7/tests/test_config.py#L88

We could use this pattern:

https://github.com/mozilla/normandy/blob/b075d14d906f3d18aedc4faaa17a64564fe007f1/normandy/base/tests/__init__.py#L29-L40

**Comment by tamarbuta** [comment]
I would like to try to fix this issue.
