### ISSUE TITLE
Docker kinto/kinto-server image is out of date

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#2157]
The last release on https://hub.docker.com/r/kinto/kinto-server/tags is 13.0.1, even though we have 13.1.0 and 13.1.1. Are we supposed to be building this image ourselves?

**Comment by Natim** [comment]
It is because of this: https://success.docker.com/article/i-have-issues-triggering-autobuilds

**Comment by Natim** [comment]
I reconfigured the automatic building.

**Comment by leplatrem** [comment]
> I reconfigured the automatic building.

Should we document that somewhere? Are we all admins on Docker?

**Comment by Natim** [comment]
At least you are, I don't know what is @glasserc hub.docker.com id, I invited him with his gmail address.
