### ISSUE TITLE
kinto-storage.org has been offline for a while now

### ISSUE THREAD

**Issue by adebisi-fa** [Kinto/kinto#2184]
Hello,

It appears the official website for **kinto**, [kinto-storage.org ](https://kinto-storage.org), has been offline for a while now.

Is there a maintenance work going on? or Is it going to be replaced with something different or new?

The portal's being offline has made it not that easy to advocate **kinto**, (without coming to github).

Any word on this, please?

Thanks for the good work on this project.  It's simply awesome!!

**ADEBISI Foluso A.**

**Comment by Natim** [comment]
It is one of @mostlygeek task, the domain is now supposedly handled by Mozilla and we only him can configure the DNS...

**Comment by mostlygeek** [comment]
I got https://slack.kinto-storage.org/ back online.  Where is the source for the website?  We can host that somewhere too.

**Comment by glasserc** [comment]
@mostlygeek I found it: https://github.com/Kinto/kinto-website. Also be aware that although HTTPS works, http://slack.kinto-storage.org/ does not work.

**Comment by glasserc** [comment]
Refs https://github.com/Kinto/kinto-website/issues/20.

**Comment by Natim** [comment]
Seems to be back: https://www.kinto-storage.org/

**Comment by Natim** [comment]
@mostlygeek do you have the CNAME I should use for slack.kinto-storage.org ?

**Comment by mostlygeek** [comment]
Is slack.kinto-storage.org something you can host as well?

**Comment by Natim** [comment]
Yes I can try to host it, in the meantime I will try to use the CNAME you've provided, thanks.

**Comment by Natim** [comment]
It works: https://slack.kinto-storage.org/

**Comment by Natim** [comment]
Do you have a link to the source code that need to be hosted?

**Comment by glasserc** [comment]
Alexis said it was https://github.com/outsideris/slack-invite-automation.

**Comment by Natim** [comment]
Great thanks
