### ISSUE TITLE
Use plain ini sections for configuring Kinto, not old-style Paster

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#220]
all in the title

**Comment by tarekziade** [comment]
in pserve + app.wsgi

**Comment by Natim** [comment]
Could you provide an config example of what you have in mind for this?

**Comment by tarekziade** [comment]
Right now we have to do this in kinto.ini

```ini
[app:main]
use = egg:kinto
kinto.http_scheme = http
kinto.http_host = 0.0.0.0:8888

# Backends.
kinto.storage_backend = cliquet.storage.postgresql
kinto.storage_url = postgres://postgres:postgres@localhost/postgres
kinto.cache_backend = cliquet.cache.postgresql
kinto.cache_url = postgres://postgres:postgres@localhost/postgres
kinto.permission_backend = cliquet.permission.postgresql
kinto.permission_url = postgres://postgres:postgres@localhost/postgres
```

My change would allow to do something way less verbose:

```ini
[app:main]
use = egg:kinto
kinto.http_scheme = http
kinto.http_host = 0.0.0.0:8888

[storage]
backend = cliquet.storage.postgresql
url = postgres://postgres:postgres@localhost/postgres

[cache]
backend = cliquet.cache.postgresql
url = postgres://postgres:postgres@localhost/postgres

[permission]
backend = cliquet.permission.postgresql
url = postgres://postgres:postgres@localhost/postgres
```

**Comment by tarekziade** [comment]
The proposed change is straightforward. Example:

```diff
--- a/kinto/__init__.py
+++ b/kinto/__init__.py
@@ -30,6 +30,8 @@ DEFAULT_SETTINGS = {


 def main(global_config, **settings):
+    from konfig import Config
+    settings['config'] = Config(global_config['__file__'])
     config = Configurator(settings=settings, root_factory=RouteFactory)

     # Force project name, since it determines settings prefix.
```

Then the code can grab the config object. Another option is to pour back the content of the config file into settings, but I think it's less powerful than letting the code interact with the config object.

**Comment by leplatrem** [comment]
I am globally seduced by that. But I have a mixed feeling in regards to the Pyramid ecosystem conventions...

* We should probably replace pserve with something that runs the app.wsgi file no?
* It looks like prefixing settings name is a common pattern in Pyramid applications. This would contrast with the ecosystem, no?
* I wish this could apply to every cliquet applications, without having to copy/paste this `global_config` line)

**Comment by tarekziade** [comment]
> We should probably replace pserve with something that runs the app.wsgi file no?

why ?

**Comment by tarekziade** [comment]
> We should probably replace pserve with something that runs the app.wsgi file no?

why ? I think we can tweak the startup files so pserve is happy

> It looks like prefixing settings name is a common pattern in Pyramid applications. This would contrast with the ecosystem, no?

The configuration file is used by humans to tweak the app options, so the target is them, not the code.
I don't really think the configuration file should stick to a pattern if we think it's less explicit and clean, since for the code both ways to load the options can be done.

The only consideration imho is: do we like it better with explicit sections or not

> I wish this could apply to every cliquet applications, without having to copy/paste this global_config line)

This step can happen in cliquet during the initialization chain I think

**Comment by leplatrem** [comment]
Unlikely to happen. Been here for too long.
