### ISSUE TITLE
Link repo description does not work

### ISSUE THREAD

**Issue by webwurst** [Kinto/kinto#2210]
This one does now work for me: http://docs.kinto-storage.org/
Maybe someone can replace that with: https://kinto.readthedocs.io/en/latest/ ?

**Comment by glasserc** [comment]
Thanks for the report! I updated the link as you suggested.

**Comment by Natim** [comment]
Oh I just reactivated the docs.kinto-storage.org domain name

**Comment by glasserc** [comment]
OK, I put the link back.
