### ISSUE TITLE
Provide a Datadog implementation for StatsD ?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#2222]
Back at this https://github.com/mozilla-services/cliquet/issues/643

I want to take advantage of Datadog tags in https://github.com/Kinto/kinto-signer/pull/611 
Should we ship a Datadog implementation of our statsd interface? Should it be built-in Kinto or packaged elsewhere?

**Comment by Natim** [comment]
> Should we ship a Datadog implementation of our statsd interface?

Yes I guess we could do that or try to import statsd from datadog statsd?

```
from datadog import statsd

```

**Comment by leplatrem** [comment]
Hmm, after conversations with the OPs team, this won't be the way to go (spoiler: Grafana)
