### ISSUE TITLE
How to restrict `admin` user to localhost?

### ISSUE THREAD

**Issue by chaitanya9186** [Kinto/kinto#2242]
Hi Kinto Team, 

I am new to Kinto, I love the simplicity and the features. Is there anyway I can restrict the `account:admin` to localhost.

I may be asking the wrong question. But my intention is I want to restrict the admin access to limited, so that it will be secure (to some extent).

Thanks in advance.

**Comment by Natim** [comment]
We don't have such feature so far. I would recommand you do comment the admin user in production and uncomment it only when you need it.

Alternatively you can also use a 2FA authentication method through an openid provider and use this user as an admin for a more robust login method.
