### ISSUE TITLE
Admin / Account initial mess

### ISSUE THREAD

**Issue by BillMeyerRSA** [Kinto/kinto#2258]
Got Kinto up. 
Followed instructions... running...
Wanted to access /accounts
Documentation is vague, cannot find how to admin users...
Then it started hanging
Stopped the docker, started again
And then Admin don't authenticate
tried anonymous - OK - but then cannot logout or get to log in to Admin again. 
Come on!!!

**Comment by Natim** [comment]
Hello @BillMeyerRSA,

I am really sorry to hear that you are having troubles with the account feature.

Things to keep in mind:
 - Accounts don't work with the memory backend.
 - You can use a create user command to create the user account:

```
$ kinto create-user --help
usage: kinto create-user [-h] [--ini INI_FILE] [-q] [-v] [-u USERNAME]
                         [-p PASSWORD]

optional arguments:
  -h, --help            show this help message and exit
  --ini INI_FILE        Application configuration file
  -q, --quiet           Show only critical errors.
  -v, --debug           Show all messages, including debug messages.
  -u USERNAME, --username USERNAME
                        Superuser username
  -p PASSWORD, --password PASSWORD
                        Superuser password
```

  - You can configure an admin in the kinto.ini file: http://docs.kinto-storage.org/en/stable/configuration/settings.html#bypass-permissions-with-configuration

We have yet to create the management UI for accounts: https://github.com/Kinto/kinto-admin/issues/437 If you need this feature we would gladly accept your help in building it.

**Comment by leplatrem** [comment]
We should probably show a huge warning when using accounts with the memory backend, that accounts are flushed when restarted
