### ISSUE TITLE
Add Content Security Policy header to responses

### ISSUE THREAD

**Issue by mozcloudsec** [Kinto/kinto#2303]
Site https://webextensions.settings.services.mozilla.com has failed the web security baseline scan.

The failing tests are:

 Content Security Policy (CSP) Header Not Set [10038] x 1 
 * https://webextensions.settings.services.mozilla.com/ (307 Temporary Redirect)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=webextensions.settings.services.mozilla.com) dashboard.
If you have any questions or concerns please get in contact with @psiinon

**Comment by leplatrem** [comment]
@psiinon is this really necessary on an API? 

We set CSP in a `<meta>` tag for the admin UI:

https://github.com/Kinto/kinto/blob/2247cb781396c1a5f936681951e8e71e9fd244e4/kinto/plugins/admin/public/index.html#L6-L7

**Comment by leplatrem** [comment]
Thanks! 

Then, we'll have to do the whole #1075

**Comment by leplatrem** [comment]
[MDN says](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri) that `report-uri` is deprecated, so we'll do header first :)

**Comment by mozcloudsec** [comment]
The web security baseline for site https://webextensions.settings.services.mozilla.com is still failing, this issue should stay open.

**Comment by mozcloudsec** [comment]
Unable to change this issue state to "open" due to lack of permissions - please do this manually

**Comment by psiinon** [comment]
@leplatrem I'm afraid I've only implemented github integration at this stage.
I can change @mozcloudsec to raise bugs for kinto on one of our private repos if you like but it will be a manual process to then manage the associated bugzilla bug.

**Comment by Natim** [comment]
Then I guess using mozilla-services/kinto-dist would be a good place for this.

**Comment by psiinon** [comment]
So we can use that for all of:

* firefox.settings.services.mozilla.com
* kinto.stage.mozaws.net
* webextensions.settings.services.mozilla.com

?

**Comment by Natim** [comment]
Yes this is correct.

**Comment by psiinon** [comment]
Configs changed :)

**Comment by leplatrem** [comment]
And even https://testpilot.settings.services.mozilla.com

**Comment by psiinon** [comment]
This has now been raised as https://github.com/mozilla-services/kinto-dist/issues/1063 so this issue can be closed.
Let me know if any other changes are needed.
