### ISSUE TITLE
"Security Considerations" section in the docs.

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto#231]
We identified several issues which would be best practices when deploying a Kinto server:

* Use bucket id's that are unique to the group that has access to the collections in that bucket (i.e. don't use a "default" bucket that would make data from different users use identical URLs).
* Restrict the `"access-control-allow-origin"` header if the allowed origin(s) is/are known.
* Send a `"Cache-Control": "no-cache"` header on each response (this does not prevent caching, but it makes sure the browser cache does not leak info without triggering a revalidate and checking authorization with the server first.

There might be more things worth adding to this section.

**Comment by tarekziade** [comment]
Sounds like the 3rd one can be enforced by default in the Kinto API ?

**Comment by michielbdejong** [comment]
Here's an illustration showing why using the default bucket is a bad idea: https://michielbdejong.com/kinto-buckets.html

**Comment by leplatrem** [comment]
Thanks Michiel for initiating this! 

> don't use a "default" bucket

We are replacing the default bucket with a redirection in #233 

> Send a "Cache-Control": "no-cache" header on each response

This would indeed be a no-brainer. And we would restrict the [client cache headers feature](http://kinto.readthedocs.org/en/latest/api/collections.html#collection-caching) to anonymous requests (like @Natim suggested in https://github.com/mozilla-services/cliquet/issues/449)

**Comment by ametaireau** [comment]
Good catch @michielbdejong !

If I understand the holy spec correctly ([link to the caching section of the HTTP spec](http://tools.ietf.org/html/rfc7234#section-4)), it seems that returning "no-cache" would make the client issue a request even if there are matching records in the cache. The response [could be cached by inbound servers](http://tools.ietf.org/html/rfc7234#section-4.3), and as such the problem would remain.

Rather, we could use the `Vary` header ([see spec](http://tools.ietf.org/html/rfc7231#section-7.1.4)), specifying the header "Authorization".

> The "Vary" header field in a response describes what parts of a
>  request message, aside from the method, Host header field, and
>  request target, might influence the origin server's process for
>  selecting and representing this response.  The value consists of
>  either a single asterisk ("*") or a list of header field names
>  (case-insensitive).

**Comment by michielbdejong** [comment]
Ah you're right, we probably still need that `Vary` header, bummer. That makes the security model of the default bucket much more complex than the security model without default bucket.

**Comment by ametaireau** [comment]
What about adding this `Vary` header to all the buckets? It seems to be something we want anyways, which would mean the security model would be the same across buckets, nope?

**Comment by Natim** [comment]
Actually it is a bit more complex than that, because even when not using default bucket, with regards to the permission, two persons may not have access to the same record list while if not using the Vary header we could give them the same cached list.

**Comment by Natim** [comment]
So as @ametaireau we will need the Vary header on every bucket.

**Comment by michielbdejong** [comment]
Right, that's true.

**Comment by michielbdejong** [comment]
Update on  https://michielbdejong.com/kinto-buckets.html - it was still failing after `Cache-Control: no-cache` was added to kinto.dev, but that was because there was a bug in my test script (not setting `dbPrefix: userid`) which is fixed now. So I think for browser cache (and probably also for shared-cache proxies, because they should also revalidate), it's now safe to use the default bucket on kinto.dev. A revalidate will always be triggered, and then Kinto will do two things:

* check the Authorization header
* respond with the ETag for the user corresponding to the Authorization header, so the cache knows which cached data to serve, based on that ETag header, and will never serve the wrong data.

Hope I'm right about this description. ;)

**Comment by michielbdejong** [comment]
Created https://michielbdejong.com/kinto-test2.html to illustrate that the current situation with the kinto.dev default bucket looks safe.

**Comment by leplatrem** [comment]
Closing as I think this was resolved. Please re-open if I'm mistaken

**Comment by Natim** [comment]
@n1k0 still had a similar bug today on ``/buckets`` we need to add the ``Vary`` header.

**Comment by n1k0** [comment]
> @n1k0 still had a similar bug today on ``/buckets`` we need to add the ``Vary`` header.

Note that it's not only for `/buckets` but for all urls shared by different authenticated users like `/buckets/default`.

**Comment by Natim** [comment]
This was fixed by https://github.com/mozilla-services/cliquet/commit/eda3be3af48b004b2b5ebfeaf7d4e27e6591d8e9
