### ISSUE TITLE
PIP requires an update when docker-compose is building images

### ISSUE THREAD

**Issue by kaloneh** [Kinto/kinto#2321]
Since the `docker-compose` is building images two issues come up one with `docker` and the other along with data persistency. Former can be resolved with some manipulation in `Dockerfile` and docker-compose, however, the latter _tightly depends on saving data on volume_ in which database is gonna be responsible for hold data on disk. Anytime `docker-compose` downing the process, all data will be lost and this not properly what we expect from `PostgreSQL` as a persistence layer, however, it might be fine with _cache_ because of its nature and _in-memory behaviour_.

**Comment by Natim** [comment]
Fixed with #2324
