### ISSUE TITLE
kinto-admin package's not properly installed in docker image

### ISSUE THREAD

**Issue by kaloneh** [Kinto/kinto#2322]
Following errors are reported during composing images by `docker-compose`
```
> kwac@1.25.2 build /app/kinto/plugins/admin
> react-scripts build

Creating an optimized production build...
Failed to compile.

./node_modules/kinto-admin/lib/index.js
Cannot find module: 'react-redux'. Make sure this package is installed.

You can install this package by running: npm install react-redux.


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kwac@1.25.2 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kwac@1.25.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-30T13_29_25_294Z-debug.log

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...
```
It seems this issue connects to `package.json` in `kinto-admin` package and usage of the package in the application!

**Comment by leplatrem** [comment]
You are right, there are issues, we have 3 PRs that fail with the same kind of error.

Is it related to #2279 ?

**Comment by kaloneh** [comment]
There are _two different packages_ including `react-redux` and `redux`.  Former depends on latter while the latter has been declared in `package.json` and the application looking for a proper instance of the `react-redux` that's been missed. You can explore `node_module` and find out why this error comes up!
I think it should have been saved as dev dependency by `npm install --save-dev react-redux`.
