### ISSUE TITLE
Venusian version in requirements.txt needs modifying.

### ISSUE THREAD

**Issue by kaloneh** [Kinto/kinto#2335]
It seems _TravisCI_ is detecting an anomaly and conflict during verification amongst test cases. [venusian](https://github.com/Pylons/venusian/pull/63#issuecomment-549991842) reports that the correct version of 2.0.0 is 3.0.0 and 1.2.0 is mutated to 2.1.0 so that in requirements.txt should have been modified at line 40.

**Comment by Natim** [comment]
Rebasing from master should fix this issue. Refs https://github.com/Kinto/kinto/pull/2332
