### ISSUE TITLE
Resource timestamp should be current instead of highest timestamp 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#2343]
> I think resource_timestamp just being "the biggest timestamp of any of the resources" is inherently flawed and we should move instead to "the last timestamp any resource changed" instead.

Basically, imagine that at t=100 I created a record in an empty collection forcing its timestamp to 50.
The collection timestamp will be 50.

We propose that the collection timestamp should be 100 instead.

**Comment by Natim** [comment]
This feature is there so that we can duplicate a collection from a bucket to another.

**Comment by leplatrem** [comment]
> This feature is there so that we can duplicate a collection from a bucket to another.

Yes, it's fine, when we duplicate records we may want to keep their original timestamp, but I think the resource timestamp should reflect the fact that something happened on that resource.

I would suggest the following:
- the resource timestamp should never go back
- the resource timestamp should always be bumped when an object is created/updated
- an object create/update with a timestamp specified should be ignored when inferior or equal to the current resource timestamp

I thought it was the case, but I found this code comment in the tests:

https://github.com/Kinto/kinto/blob/84cbaa3fcc7665a6aa595f34a8158c039caffb46/kinto/core/storage/testing.py#L884-L887

BTW, the source of this discussion is https://github.com/Kinto/kinto-signer/issues/779

**Comment by glasserc** [comment]
> an object create/update with a timestamp specified should be ignored when inferior or equal to the current resource timestamp

Isn't that inconsistent with "I think the resource timestamp should reflect the fact that something happened on that resource." ?

I think the test verifies that in fact the behavior is as you described -- the newly created object has a timestamp in the past, but the resource timestamp remains the same.

Unfortunately I think the comment raises a good point (discussed in https://github.com/Kinto/kinto/pull/1361) -- when we put objects into the past, we kind of break synchronization. Because the resource's timestamp is meant to correspond to some object's `last_modified`, clients are expected to do `?since=last_resource_timestamp`, and this is meant to catch all objects that were inserted in the meantime. I don't really have a good idea for how to fix this.. some kind of "object timestamp" representing the time the object was modified, as well as a "collection timestamp" for each object representing a monotonic order for every operation? Vector clocks?

I suspect we'll have to close this issue and address it in `kinto-changes`/`kinto-signer`..

**Comment by Natim** [comment]
I don't think this is related to the kinto-signer bug, you can always remove the last_modified value of your record when synchronizing if you don't wish to keep the same timestamp.

**Comment by Natim** [comment]
>when we put objects into the past

This is only possible in one case : when you create objects from a previous collection, most of the time it isn't possible.

This is possible only if the resource_timestamp is lower than the current last_modified value. If you change this behaviour it won't be possible anymore.

**Comment by Natim** [comment]
> some kind of "object timestamp" representing the time the object was modified, as well as a "collection timestamp" for each object representing a monotonic order for every operation

This is already the case today.

**Comment by leplatrem** [comment]
> > an object create/update with a timestamp specified should be ignored when inferior or equal to the current resource timestamp
> 
> Isn't that inconsistent with "I think the resource timestamp should reflect the fact that something happened on that resource." ?

I don't think so. If I supply an old timestamp in my record, it's ignored and replaced by a new one.

>> some kind of "object timestamp" representing the time the object was modified, as well as a "collection timestamp" for each object representing a monotonic order for every operation
>
> This is already the case today.

I don't think it is. The resource timestamp and object timestamp are strongly correlated. As Ethan said, we use the later for `_since`. Plus, it's possible to create objects in the past without having the resource timestamp be bumped, so it doesn't represent every operation.

> This is possible only if the resource_timestamp is lower than the current last_modified value. If you change this behaviour it won't be possible anymore.

I don't see that, and this test kinda shows it's possible to create records with timestamp lower than resource timestamp:

https://github.com/Kinto/kinto/blob/84cbaa3fcc7665a6aa595f34a8158c039caffb46/kinto/core/storage/testing.py#L871-L887

> I suspect we'll have to close this issue and address it in kinto-changes/kinto-signer..

Yes, mainly because of the fact that we use the resource timestamp for the value of `_since`

**Comment by Natim** [comment]
> it is possible to create objects in the past on empty collections (or if the past is more recent that current timestamp, see previous)

How do you handle the case where you need to create 20 items in the past of today if the first one uses current_timestamp as the current timestamp?

**Comment by leplatrem** [comment]
> How do you handle the case where you need to create 20 items in the past of today if the first one uses current_timestamp as the current timestamp?

:sweat: Good point :rofl:

**Comment by leplatrem** [comment]
It seems that the only solution that my brain can process consists in changing kinto-signer
