### ISSUE TITLE
Activate POST on collections

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#237]
$ curl -H "Content-Type: application/json" \
              -X POST -d '{"data": {"test": "some_data"}}' --user testuser:abc123 \
              https://kinto.dev.mozaws.net/v1/buckets/test_bucket/collections

    {"errno":115,"message":"Method not allowed on this endpoint.","code":405,"error":"Method Not Allowed"}

**Comment by leplatrem** [comment]
Related #64
