### ISSUE TITLE
Could someone suggest a way to do password less authentication using SMS or Email?

### ISSUE THREAD

**Issue by chaitanya9186** [Kinto/kinto#2395]

**Comment by Natim** [comment]
You even have a plugn for it :joy: 
https://github.com/Kinto/kinto-nexmo-verify/

**Comment by chaitanya9186** [comment]
Thanks @Natim for the plugin.

But I don't see any code in the master branch. Is any one using this plugin?

**Comment by Natim** [comment]
You are right, the code is missing.
I am adding it there: https://github.com/Kinto/kinto-nexmo-verify/pull/66/files
