### ISSUE TITLE
USB device input not working after reboot

### ISSUE THREAD

**Issue by markogresak** [Kinto/kinto#2492]
When I install kinto, it's working correctly right away. But after rebooting the machine, all USB input freezes, even the USB mouse stops working. The only thing I was able to do is to use the hardware power button to reboot the machine and remove the configuration from the recovery boot.

When digging through the `/var/log/syslog`, I found this line, which might be of interest:
```
pop-os kinto.desktop[2281]: /bin/sleep: unrecognized option '--user'
pop-os kinto.desktop[2281]: Try '/bin/sleep --help' for more information.
```

But I can't find where is `sleep --user` called.

To be sure, I have pulled out and tested `sleep_ms` separately with same Makefile, and it works as expected when I run the binary. 

I thought it might be related to the binary, so I've rebuilt it on my machine and reinstalled kinto, but I still hit the same problem after rebooting. 

---

**Install Type:** Bare Metal
**Distro:** PopOS 19.10
**DE:** Gnome
**Branch:** master
**Commit:** 701bf25c699d8485165b7eab78d75b0e8257823d

Other info: 
- System input is English (US) with Emacs input and Caps lock = Esc tweaks
- Windows ([ISO](https://en.wikipedia.org/wiki/ISO/IEC_9995#ISO/IEC_9995-10)) keyboard (104 keys)
- Applied the default options and suggested tweaks for gnome

**Kinto Input Caret Status**

The `/tmp/kinto` folder does not exist. In some cases it did, but it was empty.

**Kinto Debug Log (1.0.6-2+)**

Running the script directly works, and it also works well immediately after the install. I have also tried by modifying the script to run it with `--debug` flag but I did not find anything useful by grepping the `syslog` for `kinto|keyswap`.
Due to the nature of the problem, I can't go and run the script when I experience the problem.

**Comment by glasserc** [comment]
I think you must be thinking of another project called kinto, such as https://github.com/rbreaves/kinto.

**Comment by markogresak** [comment]
@glasserc yes, I’m sorry. It was late and I’ve clicked the wrong project 😅
