### ISSUE TITLE
Add column for default values in settings documentation

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#255]
We should add the default values in the config doc. e.g.: what's the default size of the pool?

**Comment by tarekziade** [comment]
see https://github.com/mozilla-services/cliquet/blob/master/cliquet/__init__.py#L27-L88

**Comment by Natim** [comment]
There is a link to that list in the note here http://kinto.readthedocs.org/en/latest/configuration/production.html#recommended-settings

**Comment by almet** [comment]
They already are in there (in the docs). See in red after the key of the setting?

**Comment by tarekziade** [comment]
I am here: http://kinto.readthedocs.org/en/latest/configuration/settings.html#storage

I was reading the list of options for the storage. I think we should somehow mention what are the default values in the settings section.

**Comment by tarekziade** [comment]
oh! I see what you mean now, "10" is the default value. This was not obvious. Maybe we could explicitely write: 

```
default value: 10 
```

**Comment by tarekziade** [comment]
I would suggest an exlicit row in the table called "default value" maybe ?

**Comment by leplatrem** [comment]
Yes, adding a column for default values was already suggested in #208
