### ISSUE TITLE
Mention sticky session for Nginx is memory cache is used in production

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#262]
So that same user is always routed to the same worker

**Comment by Natim** [comment]
I would rather mention not to use the Memory backend in production.
But at least this yes.

Refs https://github.com/mozilla-services/cliquet/issues/406

**Comment by tarekziade** [comment]
That will work only if Kinto runs with a single process, which is not the case most of the time when you deploy with uWSGI

+1 to just mention that the Memory backend is suboptimal in a real deployment with mutiple processes.

**Comment by leplatrem** [comment]
Sounds rather obvious that memory backend is suboptimal for production...
