### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by dstaley** [Kinto/kinto#2644]
Based on the info [here](https://travis-ci.community/t/builds-hang-in-queued-state/10250/6), we should probably go ahead and migrate the entire `kinto` GitHub org over to travis-ci.com. I think the only ones who are able to do that are the org admins. @leplatrem I think this would be you!

**Comment by leplatrem** [comment]
![Screenshot from 2020-10-29 01-03-21](https://user-images.githubusercontent.com/546692/97509457-a0412980-1982-11eb-9b7b-784d462694d5.png)

I don't really know where this happens..

**Comment by dstaley** [comment]
@leplatrem I believe you need to here and enroll in the beta:

https://travis-ci.com/organizations/Kinto/migrate

**Comment by leplatrem** [comment]
Thanks! After having approved a couple of disclaimer about beta stuff, I think it's done

**Comment by dstaley** [comment]
I'm seeing builds in the UI! Once the green checks start flowing again I'll close this issue.
