### ISSUE TITLE
Expose the experimental json-schema feature in the public settings on the hello_page.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#270]
https://kinto.dev.mozaws.net/v1/

**Comment by Natim** [comment]
I wonder if this list of public exposed settings should not be configurable using the configuration file.

**Comment by Natim** [comment]
Now that we have capabilities it should be exposed as a capability.

Here is an example of how a capability can be exposed: https://github.com/Kinto/kinto-attachment/blob/master/kinto_attachment/__init__.py#L19-L22

Here is the place where we could add the capability: https://github.com/Kinto/kinto/blob/8cc9b87b7776b68da391790f99a9b8b0aa65195f/kinto/__init__.py#L55

Here as some example of the two tests that could be written:  https://github.com/Kinto/kinto-attachment/blob/a3b531662b6468dd2585e92a238e99551439703e/kinto_attachment/tests/test_plugin_setup.py

**Comment by Natim** [comment]
@lavish205 said on IRC he wanted to work on this bug.

**Comment by Natim** [comment]
You need to expose the capability if the settings is set to true:

Here is the way to do it:
```
config.add_api_capability("schema",
                          description="Enforce a schema for collection records.",
                          url="http://kinto.readthedocs.org/en/latest/api/1.x/"
                              "collections.html?highlight=schema#collection-json-schema")
```

**Comment by lavish205** [comment]
@Natim can you assign this bug to me?
