### ISSUE TITLE
Decoding record with > 64-bit integer fails

### ISSUE THREAD

**Issue by damilgra** [Kinto/kinto#2736]
If a record is added to Kinto that includes a number greater than 64 bits, one cannot view the record via the
 GET /buckets/(bucket_id)/collections/(collection_id)/records/(record_id)
endpoint.

For instance if the record contains {"weight": 211230200427052203004205123} , the numeric value is stripped, rendering the resultant JSON as invalid so that it can't be decoded.

From a quick test, I saw that the issue is related to ujson usage; the same error does not occur with the native json module, nor with pysimdjson which like ujson is advertised as being extremely performant.

**Comment by leplatrem** [comment]
@damilgra I'd happy to replace ujson by simdjson, if you'd like to open a pull-request that would be cool :)

**Comment by damilgra** [comment]
Thanks @leplatrem . I can add a pull request but am not sure the best way to resolve the following sub-issue: 
simdjson fails my added unit test when the memory storage is used.

For now, I've modified the memory storage to use native json to make it pass, but am not sure if that's desirable.

**Comment by TkTech** [comment]
Keep in mind that you should be storing integers > 64bits as strings. While JSON doesn't specify constraints on numbers, if you start storing larger numbers you aren't guaranteed that whatever you're using to read from kinto will be able to parse it. The vast majority of parsers are limited to 64 bits.
