### ISSUE TITLE
Plugins views hide default bucket

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#277]
Currently, the default bucket views are registered after `cliquet.initialize()`.

The plugin views (`kinto.includes`) are registered during `cliquet.initialize()`.

The plugin views are hence registered before `/buckets/default/*`, and thus hide it.

This is a limitation for *kinto-attachment* which registers `/buckets/{bucket_id}/collections/{collection_id}/records/{id}/attachment`. 

Possible solutions:
* register default bucket views before `cliquet.initialize()`. *Note: version prefix will thus have to be managed explicitly*
* add an *kinto ready* event on which plugins can hook to do last minute config modifications

Thoughts?

**Comment by Natim** [comment]
I am wondering if we shouldn't put the default_bucket feature as a plugin and let the plugin order handle that current limitation.
