### ISSUE TITLE
list the possible responses status codes

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#279]
When reading http://kinto.readthedocs.org/en/latest/api/buckets.html#bucket-delete I was confused about the signification of getting back a 403 on an unexistant bucket.

Maybe we could add for each API a list of possible response codes and a short explanation for each one ?

**Comment by leplatrem** [comment]
Yes, we still have a problem regarding documentation.

The trick we used to include the cliquet resource docs isn't working very well. 
See here, we have status code listed http://kinto.readthedocs.org/en/latest/api/cliquet/resource.html#delete-collection
BTW, 401 and 403 aren't mentionned :D 

We have to find a way to document that the buckets/groups/collections/records all share a common set of properties. And those properties are the one described in the documentation of cliquet resource (above link).

I fully agree that the current situation isn't very much engaging

**Comment by leplatrem** [comment]
Related #196

**Comment by tarekziade** [comment]
One solution would be to extend resource.register() so we can list for each verb the status codes. 

That'd also be a great way to improve testing by asserting that whatever response goes out of the method, its status is in the list
