### ISSUE TITLE
Update parent last_modified ?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#286]
Currently, bucket and collections are resources, exactly like records. When a bucket or collection is deleted, every underlying objects are deleted. But when an underlying object is modified the parent timestamp (`last_modified`) is not bumped.

For example, when querying `GET /buckets/blocklists/collections`:
```
GET /buckets/blocklists/collections
{"data":[{"last_modified":1447944869447,"id":"certificates"}]}
```

Here, the `last_modified` of the collection objects are only modified when the collection itself is changed (for example, when a `schema` is set, or a `cache_expires`, or any collection attribute).

It may be relevant to update the timestamp of the collection when one of its records is created/changed/deleted. Same for buckets (with underlying collections and groups). 

This would ease global polling for changes for example. But nonetheless, there would be no difference between a timestamp bump for a collection attribute change or for an underlying record change.

If we don't want this, we should at least clarify it in the documentation.

**Comment by tarekziade** [comment]
I consider children to be part of the parent resource content and I think the logical thing is to impact the last_modified of the parent when a child change.

What would be the benefit of not doing it ?

**Comment by Natim** [comment]
For a collection there are two things:
 - The collection update
 - The collection records update.

The former is the collection.last_modified value which changes when the collection properties are updated.
The later is the collections records.collection_timestamp which is the last record update last_modified value.

I am wondering if we shouldn't keep both value separated and add a last_updated properties on collection which would contain the /records ETag value.

**Comment by Natim** [comment]
Or we should do what @tarekziade said (ie. update the collection last_modified value when a record is updated) and add schema a a subresource of collection. (with a proper schema last_modified value.)

**Comment by tarekziade** [comment]
> The former is the collection.last_modified value which changes when the collection properties are updated.

Is that a specific use case we have ? to be able to do something when a collection property has changed but NOT when a record has changed ?

**Comment by Natim** [comment]
> Is that a specific use case we have?

Today we have the schema experimental feature that is using this last_modified value as a schema version.

**Comment by leplatrem** [comment]
Closing. Not a good idea.
