### ISSUE TITLE
cliquet.storage.exceptions.BackendError: ConnectionError: Error 8 connecting to localhos:6379

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#289]
The config wizard has typos:

https://github.com/Kinto/kinto/blob/master/kinto/config/__init__.py#L39
https://github.com/Kinto/kinto/blob/master/kinto/config/__init__.py#L41
https://github.com/Kinto/kinto/blob/master/kinto/config/__init__.py#L43

I am not sure how, but maybe we could have a way to test that the produced default config works

**Comment by leplatrem** [comment]
Also, these lines are not necessary:
https://github.com/Kinto/kinto/blob/master/kinto/config/__init__.py#L48

And this: https://github.com/Kinto/kinto/blob/master/kinto/config/__init__.py#L55-L61
could be simplified to `**values`

**Comment by tarekziade** [comment]
by the way, I could not find where init() can be used from the shell. I had to use a \_\_main\_\_ section to run it. Is this somewhere or we should add it?

**Comment by Natim** [comment]
@tarekziade you should be able to use:

    from kinto.config import init
    init("config/kinto.ini")

**Comment by tarekziade** [comment]
@natim yes, as I said, that's what I did, but I though the intent of that code was to be published through a console entry point for example. 

e.g. something like

```python
ENTRY_POINTS = {
  'console_scripts': [  'kinto-quickstart = kinto.config:init' ]
}
```
Because right now it breaks "make serve" in Kinto, since config/kinto.ini has dissapeared

if we have that console entry point we can change the Makefile with:

```makefile

config/kinto.ini:  $(VENV)/bin/kinto-quickstart

serve: config/kinto.ini
  etc
```

**Comment by tarekziade** [comment]
It's even simpler:

```bash
.venv/bin/kinto --ini config/kinto.ini init
```

There's a bug though when this file does not exists, for some reason "make serve" does not re-create it, I;ll open another bug

**Comment by tarekziade** [comment]
see https://github.com/Kinto/kinto/issues/290
