### ISSUE TITLE
sentry raven lib is deprecated

### ISSUE THREAD

**Issue by slav0nic** [Kinto/kinto#2909]
Sentry related documentation looks outdated.
raven package is outdated (3y ago) in favor of [sentry-sdk](https://docs.sentry.io/platforms/python/) lib

**Comment by kirtan-desai** [comment]
What is needed to be done? I can do it

**Comment by leplatrem** [comment]
This would consist in replacing the use and mentions of raven by sentry-sdk

thank you!

**Comment by kirtan-desai** [comment]
I may be wrong but I could not find any usage of raven. I could only find its mentions as a dependency and in the docs/configuration/production.rst file. Isn't the code in the production.rst file supposed to be in an ini file itself?
