### ISSUE TITLE
Run multiple commands : kinto init migrate start

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#292]
Would that make sense ?

Or would it make sense to run `init` and `migrate` on `start` only when necessary ?

**Comment by conlini** [comment]
It would make sense to tie in dependency chain on commands.

So running _migrate_ would ensure _init_ is run if not done previously
and running _start_ would run _init_ > _migrate_ and then _start_

That would reduce the need for multi step setup/startup

**Comment by Natim** [comment]
We try to keep up with the *"Explicit is better than implicit"* [Python Zen philosophy](https://www.python.org/dev/peps/pep-0020/#content).

Doing the chain automatically will add complexity to detect cases.

For instance we might generate a new configuration file and run migration whereas the user actually forget to set its configuration file path or didn't run the kinto command from the proper repository.

Also letting the user run: ``kinto --ini config/kinto.ini init migrate start`` seems to make a lot of sense for me.

**Comment by conlini** [comment]
hmm yes that does add a level of complexity and branches when there are multiple configurations.
Trying to work that out would require asking user to chose one of the configs, which would defeat the purpose of a single command starting up the server.

**Comment by leplatrem** [comment]
Unlikely to happen (been here for too long)
