### ISSUE TITLE
Deprecate the use of Basic Authentication in the examples

### ISSUE THREAD

**Issue by almet** [Kinto/kinto#297]
Originally reported at https://github.com/mozilla-services/cliquet/issues/590

Currently, the demo instances and the code in the tutorial are relying on Basic Authentication. We should get rid of these examples and let the users directly rely on OAuth providers instead.

The user id should be unique, and the way to do this is to rely to an external authn provider, and all of the services we integrate with are integrable by using OAuth.

We should make it really easy to have the examples integrate with Github / Twitter / Facebook authentication. For instance, having them defined as extra-dependencies could make sense. Consider:

`$ pip install kinto[github-auth]`

**Comment by tarekziade** [comment]
I hope that does not mean Kinto can't run without an OAuth provider... If Kinto can run with Basic Auth (or no auth at all), I think the tutorial should use it to KISS. 

When I am trying a new storage service and following a tutorial, I don't care about authentication. It's not something I care about until I deploy the service.

If your tutorial forces me to use Github, Twitter or Facebook - It makes me want to stop right there.

**Comment by almet** [comment]
That's not the intention. The intention was implemented in https://github.com/Kinto/kinto/pull/395
