### ISSUE TITLE
add a --web-admin option to kinto start

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#299]
It would be cool to be able to run the web admin when Kinto is started.

**Comment by tarekziade** [comment]
one option is to have a composed wsgi app where /\_\_admin is served by a second app (kwak)

**Comment by Natim** [comment]
I would go for /admin/ rather than /__admin/ but yeah :+1:

**Comment by n1k0** [comment]
:+1:

**Comment by n1k0** [comment]
Makes me think the static web admin webpage will have to load its default settings from a json file if we want it to be ready to consume the running server API.

**Comment by leplatrem** [comment]
What about a built plugin specified in `.ini` instead of CLI arg ?

**Comment by tarekziade** [comment]
@leplatrem an option in the ini file sounds cool too

**Comment by leplatrem** [comment]
According to what was done in kinto, this will simple be a built-in plugin :) specified or not in the `kinto.includes` setting !

**Comment by Natim** [comment]
This has been handled in https://github.com/kinto/kinto-dist
