### ISSUE TITLE
How to handle different Oauth providers

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#301]
OAuth providers are giving a token that can be use to log into the service.

Today we have the Firefox Account OAuth provider which is using this formalism:

    Authorization: Bearer OAUTH-TOKEN

While implementing the Github oauth provider I've seen that [they are using TOKEN as a prefix](https://developer.github.com/v3/oauth/#use-the-access-token-to-access-the-api):

    Authorization: Token OAUTH-TOKEN

So it is easy to differentiate Firefox Account and Github because one is using TOKEN and the other one BEARER.

However, [Twitter is also using BEARER](https://dev.twitter.com/oauth/application-only) which is ambiguous because when looking at the Authorization header it is impossible to tell if it is a Firefox Account Bearer token or a Twitter Bearer token.

If we are using Bearer for both, then an application with both Firefox Account and Twitter bearer token activated will need to check the token validation on Firefox Account and then if it fails, on Twitter.

This will add complexity and will slow the authentication process while leaking Bearer tokens to another service.

My proposal is to use the Oauth service provider as the Authorization Keyword.

So that we may use this formalism when Authenticated on a Kinto service:

    Authorization: FirefoxAccount OAUTH-TOKEN
    Authorization: Twitter OAUTH-TOKEN
    Authorization: Github OAUTH-TOKEN

This will make it obvious which oauth provider to call and will not break any API.

We could also keep ``Bearer`` for Firefox Account Oauth token not to break current implementations.

I also considered adding a second header with the provider name:

    Authorization: Bearer OAUTH-TOKEN
    Provider: Twitter

But it means we need to have the context of both header to handle the Authorization Policy choice which might impact the way we are handling cache invalidation (whereas we will less likely forget about the Authorization header we might forget about handling the Provider one).

However we might want to consider this as a good solution too.

What do you think?

**Comment by leplatrem** [comment]
In the tutorial we decided to go with ``Github+Bearer``.
