### ISSUE TITLE
move away from ujson if not released soon-ish

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#306]
If we don't hear back from the utrajson project this week, I propose that we move away from it 

see https://github.com/esnme/ultrajson/issues/185

**Comment by Natim** [comment]
Actually we cannot really move away from the package because it is really faster. What we could do is to use the ultrajson package in the mean time.

**Comment by leplatrem** [comment]
I remember that we had found some difference with Readinglist. But it could be worth to re-run some benchmarks, since some comments say it's not faster for every usecase :)

**Comment by leplatrem** [comment]
ujson 1.35 was just released \o/
