### ISSUE TITLE
«how to run kinto» should be highlighted in doc homepage 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#315]

**Comment by niraj8** [comment]
Something like this?
![screenshot 2015-12-10 21 15 41](https://cloud.githubusercontent.com/assets/8666468/11719972/399dcacc-9f83-11e5-90a1-8804258439a4.png)

**Comment by leplatrem** [comment]
That is just excellent!
It would point to the *Run kinto* page ?
We'd be delighted to merge that! Thank you very much!

**Comment by niraj8** [comment]
Yes, it will point to Run Kinto page. I'll send a pull request right away.
