### ISSUE TITLE
Add Promotheus support

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#3407]
https://prometheus.io/docs/introduction/overview/

Currently, when installed with `[monitoring]`, Kinto has support for Newrelic and StatsD.

These choices are 7 years old, and may have to be revisited. Namely, we would like to add Prometheus support.

This would probably consist in replacing. `app.registry.statsd` with something else like an abstraction `app.registry.metrics` interface.
Since Prometheus requires a new endpoint, and some users may want to stick with StatsD, it could probably be implemented as a built-in plugin.

**Comment by Natim** [comment]
Nice!
