### ISSUE TITLE
Filter/Sort on subobject properties

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#345]
Let's say I have the following records:

```
{
    "data": {
        "title": "My title",
        "tags": ["astronomie", "science", "burundi"],
        "author": {
            "username": "natim",
            "first_name": "Rémy"
        }
    }
}
```

**How can I get all records from natim?**

http://localhost:8000/v1/buckets/wiki/collections/articles/records?author.username=natim ?

**Comment by almet** [comment]
I would suppose the "." could be a delimiter.

**Comment by Natim** [comment]
I also think ``.`` is a good idea for that :+1: 

- ``author.username=natim``

**Comment by leplatrem** [comment]
We use the dot notation for partial responses (`_fields=a.b`) so it seems the best option.
