### ISSUE TITLE
Feature Request: Websockets and Hooks

### ISSUE THREAD

**Issue by zwhitchcox** [Kinto/kinto#352]
Hey, love what you guys are doing. I think database-as-a-service is the future.

Gotta say, it would be pretty cool if we could use websockets, for real-time database updates.

Also, it would be nice if we could do some sort of hooks for actions, maybe provided by third-party apps. Like, maybe once a new record is added, an email could be sent or something. That would be super helpful, for me at least.

**Comment by Natim** [comment]
> it would be pretty cool if we could use websockets.

We are working on it could you describe exactly what your use case is with that?
Did you try the cliquet-pusher plugin that let you do that using [Pusher](https://pusher.com/)?

> maybe once a new record is added, an email could be sent or something

This is already doable using Notification. We would love to help you building a cliquet-email-notification plugin.

**Comment by zwhitchcox** [comment]
Ah ok, cool, I didn't know about that. And my use case is for a contact form for a marketing website. Ideally, they could automatically have new messages shown and maybe even a live chat. Obviously, you could do that with a long poll, but I thought it might be a little nicer with websockets.

**Comment by zwhitchcox** [comment]
I guess I should be more explicit with my websockets request though. So, you could create a hook and add "listeners" to the collection. Whenever someone adds a new field, the other party is informed via a websocket.

**Comment by Natim** [comment]
Ok, so yes what you describe is exactly what you can already do with cliquet-pusher.

**Comment by zwhitchcox** [comment]
Ok, thanks haha I had no idea.

**Comment by almet** [comment]
Hi, and thanks for your request and comments. In addition to pusher (and cliquet-pusher), one can integrate with any service to notify on new changes. The goal of Kinto is to be easily integrated with all these different services.

**Comment by zwhitchcox** [comment]
Yeah, that's really cool. I can't wait to use these services. And maybe start creating some of my own if there's on I need and isn't available! Thanks

**Comment by zwhitchcox** [comment]
Also, not trying to nitpick or anything, but I read through the whole documentation, and I didn't see anything about that. So, maybe, if it is in there make it a little more prominent? Not complaining at all! Just thought you might want to hear the suggestion.

**Comment by almet** [comment]
You're actually completely right, we need to update the documentation to add information about notifications on Kinto. It's hidden |in the Cliquet docs](http://cliquet.readthedocs.org/en/latest/reference/notifications.html), but we didn't spent the needed time to update the Kinto docs. I've opened #353 about this.
