### ISSUE TITLE
Add information about notifications in the documentation

### ISSUE THREAD

**Issue by almet** [Kinto/kinto#353]
Currently, our documentation doesn't contain any information about how to handle notifications, we should add a section about it, pointing to the projects we have to do this, maybe with an incentive to contribute on this field for the readers.

**Comment by leplatrem** [comment]
Would you create a new page *Notifications* ? Where we can imagine opening to sending emails etc, or do we refactor (and move) the existing synchronisation page with a new section focused on live sync ?

**Comment by leplatrem** [comment]
Closing now that tutorials about notifications have landed
