### ISSUE TITLE
requesting team access for Cynthia Anyango

### ISSUE THREAD

**Issue by karlht** [Kinto/kinto#355]
I would like to introduce @anyangocynthia, who is my Outreachy intern for this spring, helping me document and test Docker containers for various Cloud Services projects.  Could we please add her to the team that can file pull requests, etc.?

**Comment by Natim** [comment]
She can file pull-request :+1:

**Comment by anyangocynthia** [comment]
Thanks 😀

On Wednesday, January 6, 2016, Rémy HUBSCHER <notifications@github.com>
wrote:

> Closed #355 <https://github.com/Kinto/kinto/issues/355>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kinto/kinto/issues/355#event-506853066>.
>


-- 
KInd Regards,
Cynthia Anyango
