### ISSUE TITLE
Invitation for community to point to their own demos/use cases

### ISSUE THREAD

**Issue by karlht** [Kinto/kinto#356]
Submitting this on behalf of @anyangocynthia, so she can get a look at our process:

Under tutorials/examples in http://kinto.readthedocs.org/en/latest/tutorials/app-examples.html, we could be more friendly (and provide a little more detail) when asking people to upload their demos e.g. "Here is a complete list of the demos, follow this link to add yours."

**Comment by karlht** [comment]
I think I may also need access to put labels on issues.  I was trying to label this one "documentation" and "enhancement."

**Comment by almet** [comment]
That's a very good idea, Karl! Do you think a link to the edition form on github for the specific page would work?
