### ISSUE TITLE
[documentation] Add "bind: address already in use" solution to Troubleshooting section

### ISSUE THREAD

**Issue by karlht** [Kinto/kinto#357]
Again, on behalf of @anyangocynthia:

Could we add the error "Error response from daemon: Cannot start container <container_id>: failed to create endpoint <name> on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use '' to the troubleshooting section and perhaps add a solution?
 
A lot of users have encountered that problem when using docker for Kinto.

**Comment by almet** [comment]
That's a good idea! Do you want to work on a pull request or would you prefer us to add it?

**Comment by anyangocynthia** [comment]
You can just add it .

**Comment by leplatrem** [comment]
I can't reproduce it. How did you resolve it?

Do you have a Postgresql running locally?

@karlht how do you know that *a lot of users* have encountered that problem ? :) I'm curious and wonder why we were not aware of it!

**Comment by Natim** [comment]
> Do you have a Postgresql running locally?

Yes I think that's the way to reproduce it.

**Comment by karlht** [comment]
> how do you know that a lot of users have encountered that problem ? :) I'm curious and wonder why we were not aware of it!

@anyangocynthia said that was the case; presumably she and a number of colleagues encountered it.

**Comment by anyangocynthia** [comment]
I managed to trace the error . I run postgres=$(sudo docker run -e POSTGRES_PASSWORD=postgres -d -p 5432:5432 postgres) and then it gave me that error . 
p.s I have postgresql installed and docker too
