### ISSUE TITLE
[documentation] Add Requirements section to Overview

### ISSUE THREAD

**Issue by karlht** [Kinto/kinto#358]
With credit to @anyangocynthia:

In the overview section could we add a list of requirements e.g. python3, docker, etc.?

**Comment by almet** [comment]
It's all in the installation section. The overview was meant to explain what kinto is, and not to get started with it. We could add a section with a link to the "installation steps" if you think it's worth it?

**Comment by leplatrem** [comment]
We should also probably mention minimum python version :)

From IRC: 
> before going further, is there a required python version?

**Comment by vsham20** [comment]
Which all requirements are we supposed to add and where? I mean in Readme or any requirements.txt file?

**Comment by Natim** [comment]
I did something like that in the readme: https://github.com/Kinto/kinto/pull/465/files

But I think we should add requirements in the beginning of all Getting Started paragraph telling what the user needs to install and in which version before going further.

**Comment by ipsha21** [comment]
Can we add instructions to install python, Postgresql, redis in the getting started section, or just mention the requirements and not the steps to install them?

**Comment by almet** [comment]
How to install postgres [is already described](http://kinto.readthedocs.org/en/latest/configuration/production.html#postgresql-install). We could add some more information about how to install python and redis in subsequent sections.

**Comment by Natim** [comment]
Fixed with https://github.com/Kinto/kinto/pull/465/files
