### ISSUE TITLE
Trigger events only when transaction is committed

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#369]
Currently notifications are triggered when the resource method is executed.

For batch requests, if one of the sub-requests fails, the whole batched is rolledback. However the events are still triggered.

The events should be triggered when the batch transaction is committed.

This will also affect performance since only one event per collection will be triggered for a batch request.

**Comment by tarekziade** [comment]
Maybe It might worth adding in that case specific events *before* the data is saved into the DB, so some custom code can alter the data and maybe even reject the change ?

**Comment by leplatrem** [comment]
> adding in that case specific events before the data is saved into the DB

Good idea, but it's another scope IMO. Please open an other issue to describe what you have in mind! 
For naming ideas : https://docs.djangoproject.com/es/1.9/ref/signals/ :)
