### ISSUE TITLE
Tutorials should explain (better?) how to get the user/password

### ISSUE THREAD

**Issue by davidbgk** [Kinto/kinto#393]
The first command to issue within the [First steps tutorial](http://kinto.readthedocs.org/en/latest/tutorials/first-steps.html) is:

```
$ echo '{"data": {"description": "Write a tutorial explaining Kinto", "status": "todo"}}' | \
    http POST https://kinto.dev.mozaws.net/v1/buckets/default/collections/tasks/records \
         -v --auth 'user:password'
```

How do you get a `user:password` for that dev server?

**Comment by Natim** [comment]
You are right. Actually we will replace those ``user:password`` with an arbitrary string like ``token:your-user-token`` to avoid confusion when using BasicAuth.

Every token is valid with the default configuration that lets anyone authenticated to create a bucket.

But using BasicAuth introduces a lot of limitations (you identified one in #394) which should be made explicit in the documentation.

We've decided to avoid managing users in Kinto and rely on a third-party to provide tokens. For example, [Github tokens can be enabled](http://kinto.readthedocs.org/en/latest/tutorials/authentication-github.html) or any other identity provider (OAuth). We could even imagine implementing a simple service that provides tokens for users (registration/password management).
