### ISSUE TITLE
Document a change password scenario?

### ISSUE THREAD

**Issue by davidbgk** [Kinto/kinto#394]
> With Basic Auth a unique identifier needs to be associated with each user. This identifier is built using a combination of username and password, therefore users cannot change their password without losing access to their data.

Reading this I'm a bit scared of storing my data without an explanation of how to handle a corrupted password.

**Comment by leplatrem** [comment]
As we explained in #393, there is no notion of password in Kinto (we'll rework the documentation).

Basic Auth has a bunch of limitations. We are aware of them but the documentation does not make them explicit (yet! Thank you for this feedback, we opened #395 to start addressing this issue.).

As a workaround, it's possible to change the permissions of the records for a specific user, by authenticating with the old `user:pass1` and adding the userid of the new `user:pass2` pair.

It is also possible to use groups to handle permissions for multiple users on multiple objects at the same time.

But ideally, for long term storage of personal data, we'd recommend using another authentication method... (see [tutorial custom auth](http://kinto.readthedocs.org/en/latest/tutorials/authentication-github.html))
