### ISSUE TITLE
Specify keys on records response.

### ISSUE THREAD

**Issue by Dejab666** [Kinto/kinto#399]
I'm opening this Issue for a question in terms of filtering / specify keys on Records Response.

Is there any way to specify some keys that i want to get back at the API Call:

    `/buckets/(bucket_id)/collections/(collection_id)/records`

Here are an example (3 of my Records):
```
{
    "data": [
        {
            "id": "58561e0c-fe12-440b-9795-b0cea7efaf88", 
            "last_modified": 1453901844785, 
            "title": "Record 1", 
            "description": "Record Description 1",
            "data": {
                # ....  big data
            }
        }, 
        {
            "id": "78e00676-057f-48c1-b792-5682aa54306d", 
            "last_modified": 1453901861755, 
            "title": "Record 2", 
            "description": "Record Description 2"
            "data": {
                # .... big data
            }
        }, 
        {
            "id": "807304be-689f-45c6-a070-6d9cf09c00f9", 
            "last_modified": 1453903450792, 
            "title": "Record 3", 
            "description": "Record Description 3"
            "data": {
                # .... big data
            }
        },
        .... # more Records
    ]
}
```

And now i want to specify keys that i want to get back on that API Call
_(id, title, last_modified - **and not the key** data)._

I don't want to get the key "data" with some big JSON in it every time when when i call this ( performance reasons ).

-------

I imagine something like this..

API Call:
 `/buckets/(bucket_id)/collections/(collection_id)/records?keys=id,title,last_modified `

Response:
```
{
    "data": [
        {
            "id": "58561e0c-fe12-440b-9795-b0cea7efaf88", 
            "last_modified": 1453901844785, 
            "title": "Record 1", 
        }, 
        {
            "id": "78e00676-057f-48c1-b792-5682aa54306d", 
            "last_modified": 1453901861755, 
            "title": "Record 2", 
        }, 
        {
            "id": "807304be-689f-45c6-a070-6d9cf09c00f9", 
            "last_modified": 1453903450792, 
            "title": "Record 3",
        },
        .... # more Records
    ]
}
```

**Comment by almet** [comment]
Hi, thanks for opening this issue.

This is not something we currently allow, because we didn't had an use-case for it. It's possible to add this feature, and should be done in cliquet rather than in kinto.

I personally like the idea of specifying the keys you want in return, with a `_keys?` argument probably. Do you want to work on a patch for this?

**Comment by Natim** [comment]
I think this already landed. https://github.com/mozilla-services/cliquet/pull/601 and was released with Cliquet 2.14.0

The next release of Kinto (which should not be long now will include it)

**Comment by Natim** [comment]
The syntax to use will be: ``/v1/buckets/(bucket_id)/collections/(collection_id)/records?_fields=id,title,last_modified``

**Comment by leplatrem** [comment]
I confirm: this will be available in Kinto 1.11

**Comment by almet** [comment]
Ah yes! Neat, I missed this change in cliquet.

**Comment by Natim** [comment]
Kinto 1.11.0 has been released with this feature.
You can try it on the https://kinto.dev.mozaws.net/v1/ instance or [create your's on Heroku](https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2FKinto%2Fkinto-heroku&template=https%3A%2F%2Fgithub.com%2FKinto%2Fkinto-heroku%3E)
