### ISSUE TITLE
Move the readonly settings to a capability.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#403]

**Comment by leplatrem** [comment]
I really see the capabilities as a list of extra-features that are not built-in.

The `readonly` is exposed in settings. Its value has an impact on the behaviour of the API (like `max_batch_requests`) but I don't see it as a «capability».

For example, the default bucket could (once activation is not forced on startup) will become a capability.
 
But I may be wrong, please argue a bit :)

**Comment by Natim** [comment]
For me a readonly server cannot be used to sync user data.
Also the client will get 405 errors but it was the reason why I though it was a capability.

Is the server capable of writing user data during sync? Yes ? No ?

The capability could be ``writable``

**Comment by leplatrem** [comment]
> The capability could be `writable`

:+1:

**Comment by leplatrem** [comment]
> The capability could be `writable`

After thinking about this, I believe we should keep capabilities for extra features.

In this case, the `writable` capability seems a bit obvious and basically expected.

**Comment by Natim** [comment]
Should we then add the readonly capability instead?

**Comment by leplatrem** [comment]
I am still convinced that `readonly` can remain a public setting.

A capability could be something that expresses an additional property: `cdn-friendly` ?

**Comment by Natim** [comment]
A public settings seems to be enough here.
