### ISSUE TITLE
Kinto value proposition -- why do I need a JSON store?

### ISSUE THREAD

**Issue by Dowwie** [Kinto/kinto#410]
Why do I need a dedicated JSON store when databases, such as postgresql, support JSON and JSONB?

**Comment by leplatrem** [comment]
That is an excellent question which forces us to write a proper summary of the purpose of Kinto.

I suggest that we add it somewhere in the overview/faq :)

**Comment by ayusharma** [comment]
## Why do I need a JSON store? 

Language Independent : JSON is a language independent data format as Kinto Stores it. JSON can accept undefined data set in document but for pgsql query we need to define it and in pgsql JSON mostly usage for raw or secondary data.

Secure: All the data is stored in files/documents so users can not temper it.

Simple: No need of using ugly SQL Queries, Easy to work - no schema, no indexes, no complex sql but Just objects. More Javascript friendly.

Lightweight : Very small NoSQL and Validation engine as comparison to other databases. No databases processing to convert the JSON data into JSONB, BSON etc. to store it. pgsql has defined type of query natural like select * and JSON based on hstore docs or say collection when we are doing get call we need to write query which is not efficient .

File/Document Based: No need to run separate server or Backend Server and Databases Server. All data is to be stored in files as JSON Format. Better portability.


Does it seem right ? I want to get review before creating a Pull request.

**Comment by almet** [comment]
Hi, and thanks for taking the time to write this down.

By reading it, however, I feel more confused than before, so I think it's the good time to decide together what we would like to put in there.

Here is what I would like to put in this:

Why do I need a dedicated JSON store where databases such as postgres offer the same thing:
- Databases don't offer a way to access your data over an HTTP interface.
- Databases expose a complicated query language.
- Kinto lets you configure the database you want to use, and exposes a unified API for all the different databases.
- Databases are not meant to have offline first clients.

**Comment by ayusharma** [comment]
Could we also add about kinto admin here , like:

- Kinto admin allows to perform admin operations very easily.

**Comment by Natim** [comment]
I've started a pad here if you want to help: https://public.etherpad-mozilla.org/p/why-do-i-need-a-json-database

**Comment by magopian** [comment]
I've added a "second attempt, different wording" part on the pad: https://public.etherpad-mozilla.org/p/why-do-i-need-a-json-database

**Comment by leplatrem** [comment]
Looks good!

Where would we put this ? FAQ ?

**Comment by magopian** [comment]
I think it would benefit from more visibility, maybe a link from the very first sentence on http://kinto.readthedocs.org/en/latest/index.html?

Maybe something like "Why should I use Kinto" which links to a paragraph in the http://kinto.readthedocs.org/en/latest/overview.html page? (the first paragraph?)

**Comment by almet** [comment]
Could be of some interest — http://daybed.readthedocs.org/en/latest/

**Comment by almet** [comment]
Some comments: you're focusing on what kinto does for the users at first, stating what they want, but this might or might not be the case, depdending who your users are.

I proposed a few changes (in the pad and here):

```rst

We believe data belongs to the users, and not to the application authors. When writing an application, data should be made available from any device, connected or offline, and everything should be in sync.

Rather than spending a non-trivial amount of time and expertise on implementing all that (and then maintaining it !), you could use Kinto, that does all that for you:

    - Expose your data over an HTTP interface, unlike a database like PostreSQL
    - Use simple HTTP queries, instead of SQL
    - Use Kinto.js to easily implement offline first clients
    - Choose the database you want from those that Kinto supports, and use a unified API to access its data
    - Administrate your data using the handy admin UI
    - Easily set up live push notifications for live synchronisation
    - Make it possible to  share data between users (using fine-grained permissions)
    - Take advantage of schema validation if you need it
    - Use tools and libraries like Kinto.js that implements encryption so you don't have to
```

About the wording: we try in general in the documentation to avoid using "you".
