### ISSUE TITLE
broken link in docs about single-click deployment on Heroku

### ISSUE THREAD

**Issue by kumar303** [Kinto/kinto#412]
There is a broken sphinx reference link on http://kinto.readthedocs.org/en/latest/overview.html It looks like: 

![screenshot 2016-01-31 01 12 20](https://cloud.githubusercontent.com/assets/55398/12700818/dbd05b82-c7b7-11e5-9cb1-e100b6d48d8b.png)

**Comment by michielbdejong** [comment]
Looks like it should link to http://kinto.readthedocs.org/en/latest/get-started.html#deploy-an-instance-on-heroku

**Comment by michielbdejong** [comment]
Fixed in  856ec46
