### ISSUE TITLE
Internal architecture of kinto in documentation

### ISSUE THREAD

**Issue by ayusharma** [Kinto/kinto#430]
1. I think there must be a document explaining internal architecture of kinto. What are core packages like pyramid, zope, cliquet and sqlalchemy (ORM ) and learning them will surely help new contributors. 

2. Could we also add a flow/sequence diagram explaining internal architecture. ?

**Comment by leplatrem** [comment]
That's an excellent idea!

I can work on this using pen and paper, and post scanned diagrams here so that someone can contribute nice ones :)

**Comment by leplatrem** [comment]
I started this:

![archi](https://cloud.githubusercontent.com/assets/546692/13224850/b17591ce-d98a-11e5-8a83-de2173204c5f.png)

What do you think ?
(forget about aesthetic :))

Regarding sequence diagrams, I still have to think :) (e.g. scenario, level of details)

**Comment by ayusharma** [comment]
It is great.  Explaining the architecture. :+1:
