### ISSUE TITLE
add events for TERM, HUP and INT

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#435]
we should provide a mechanism to register some code when the app receives an INT or TERM (stopping), or a HUP (reload asked) signal 

Use cases: cleanup the workers pool, restart all backend connections, reload the configs etc.

Dummy implementation:

``` python
import signal
from cliquet.events import AppClosing, AppRestarting
from pyramid.threadlocal import get_current_registry

def close():
    get_current_registry().notify(AppClosing(async=False))
    sys.exit(0)

def _reload():
     get_current_registry().notify(AppRestarting(async=False))

signal.signal(signal.SIGHUP, _reload)
signal.signal(signal.SIGTERM, close)
signal.signal(signal.SIGINT, close)
```

**Comment by leplatrem** [comment]
Sounds good!

Although I would put it in a `setup_signals` function in `cliquet/initialization.py`

**Comment by tarekziade** [comment]
one minor annoyance is if Kinto is running under mod_wsgi : that web server complains when you register signals, so we need to add something about it in the doc

**Comment by tarekziade** [comment]
btw @leplatrem : if we add an async flag to all our events, the listener will be able to know which one to run synchronously.  Does that help for what you want to do with in-transaction events ?

**Comment by Natim** [comment]
I am currently using HUP with ``uwsgi`` can we say that this is a feature of the WSGI workers handler (circus/gunicorn/uwsgi)?

**Comment by leplatrem** [comment]
> can we say that this is a feature of the WSGI workers handler (circus/gunicorn/uwsgi)?

Yes.
