### ISSUE TITLE
requires.io

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#436]
looks neat, should we use it ?

https://requires.io/

**Comment by Natim** [comment]
Sounds good yes.

**Comment by Natim** [comment]
Also it seems to be using the requirements.txt file while we are not handling dependencies using it.

**Comment by Natim** [comment]
See: https://github.com/Kinto/kinto/pull/437

**Comment by leplatrem** [comment]
What is the status of this ? Is it done already ?

**Comment by leplatrem** [comment]
Looks like it's done.

![capture d ecran de 2016-04-12 15-29-49](https://cloud.githubusercontent.com/assets/546692/14461573/6dd089c8-00c3-11e6-8b25-e0f02c5e6bb2.png)
