### ISSUE TITLE
Kinto is broken with cliquet master

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#438]

**Comment by Natim** [comment]
```AttributeError: 'Request' object has no attribute 'current_service'```

**Comment by Natim** [comment]
Seems related to: https://github.com/mozilla-services/cliquet/commit/1f63dbbfbb558b5649c146ab2dd632b51bb174cc#diff-5521feacb0889694564ca55904b2742dR185

**Comment by Natim** [comment]
I think it happens when the request is not linked to any service.

**Comment by ayusharma** [comment]
I am getting this error on test cases. I am using  `make tests` .

**Comment by Natim** [comment]
This have been fixed.

**Comment by Natim** [comment]
https://github.com/mozilla-services/cliquet/pull/650
