### ISSUE TITLE
uwsgi -  bind(): No such file or directory

### ISSUE THREAD

**Issue by ayusharma** [Kinto/kinto#447]
I am configuring Kinto with nginx and getting the following error :

`bind(): No such file or directory [core/socket.c line 230]`

**Comment by Natim** [comment]
It seems to be because the repository that you defined for the socket parameter of uwsgi doesn't exists or doesn't have the right permissions:

    socket = /var/run/uwsgi/kinto.sock

**Comment by ayusharma** [comment]
Should we add this to troubleshooting section ? Took me some time to figure out while deploying kinto on nginx.

**Comment by Natim** [comment]
Yes please :)
