### ISSUE TITLE
docker run -p 8888:8888 kinto/kinto-server fails

### ISSUE THREAD

**Issue by abdulsattar** [Kinto/kinto#456]
It was working 30 minutes ago before the latest one was pushed I guess. (https://hub.docker.com/r/kinto/kinto-server/tags/)

```
/bin/sh: 1: kinto: not found
```
is the error.

**Comment by abdulsattar** [comment]
`docker run -p 8888:8888 kinto/kinto-server:1.11.2` works though.

**Comment by Natim** [comment]
Apparently the build didn't work: https://hub.docker.com/r/kinto/kinto-server/builds/b6udavocsnvt3vg7vtizzpt/

**Comment by Natim** [comment]
I will try to trigger it again.

**Comment by leplatrem** [comment]
Can we close this ?

**Comment by Natim** [comment]
Yes.

**Comment by domtallo** [comment]
It's happening again

```
# docker run -p 8888:8888 kinto/kinto-server
/bin/sh: 1: kinto: not found
```

**Comment by Natim** [comment]
It works here.

**Comment by Natim** [comment]
What happens is that every time we push on master an new docker build is triggered. Some of them breaks.

Maybe we should only build new docker images on tags.

**Comment by Natim** [comment]
I opened https://github.com/Kinto/kinto/issues/654 to address this recuring problem.

**Comment by gEndelf** [comment]
I have the same issue:

```
docker run -p 8888:8888 kinto/kinto-server
/bin/sh: 1: kinto: not found
```

**Comment by Natim** [comment]
Which tag are you using?

**Comment by Natim** [comment]
I re-triggered the build for the latest master.

**Comment by Natim** [comment]
Can you try with the last build?

**Comment by gEndelf** [comment]
tag by default  - latest
it's working now, thx!

**Comment by enguerran** [comment]
same here, I guess you can close the issue.

**Comment by Natim** [comment]
It is already closed but it reappears when the docker build fails.
