### ISSUE TITLE
Implement RFC 6902 (json patch)

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto#458]
Right now to add a single read or write permissions, you have to fetch them all, merge the new permissions with the existing ones and send them back to the server using PATCH and If-Match.

While perfectly doable, it's not super convenient when writing a client, no mention of the performances penalty.

A solution could be to add new endpoints for managing permissions more atomically?

The new endpoints could be:

- `/buckets/foo/permissions` to update everything at once
- `/buckets/foo/permissions/read` to add a single read permission (possibly many?)
- `/buckets/foo/permissions/write` same ^
- `/buckets/foo/permissions/create` same ^

With regular CRUD verbs as we know them, and the very same would go for collection permissions.

Bunch of work, and increases the surface API by a lot, so not really sure about this.

Thoughts?

**Comment by Natim** [comment]
Actually using PATCH you can already update one of the permission at the time.

Previously we add some keywork like ``{"permissions": {"read": ["+niko", "-natim"}]}}``

Another proposal was to let people use this syntax:

    {"permissions": {"read": {"add": ["niko"], "remove": ["natim"]}}}

But we ended up saying that the value of an attribute should be changed like that:

    {"permissions": {"read": ["niko"]}}

Adding an endpoint per permission doesn't seems to be consistent with what we currently have in the API. (Being able to upgrade sub objects but naming them in the endpoint)

**Comment by n1k0** [comment]
Ok never mind.

**Comment by Natim** [comment]
Note that we have a similar problem with the group members management.

If I want to add Alice as a moderator of my blog articles I would probably want to be able to write a request to add Alice without minding about who is already in the permission/group.

**Comment by Natim** [comment]
A solution could be to follow [RFC 6902](http://tools.ietf.org/html/rfc6902) which is using something like:

    [
      { "op": "add", "path": "/permissions/read", "value": "niko" },
      { "op": "remove", "path": "/permissions/read", "value": "natim" }
    ]

**Comment by almet** [comment]
Yep, this sounds cool!

**Comment by n1k0** [comment]
That'd be awesome to have if you ask me.

**Comment by gabisurita** [comment]
I would like to work on this issue.

Any problem in following the approach used on Json Patch (#859)?

**Comment by leplatrem** [comment]
Great!

You can indeed follow the approach you took in #859, but the algorithm to merge is a lot more challenging :) I suggest that you implement all 16 tests provided to make sure we behave as expected. 

> You can raise `ValueError` from the `utils` module, and then in `resource/__init__.py` transform them to `400` responses with `raise_invalid()`.

In a second time, we'll want to make sure that the provided «patch body» is valid against the RFC (eg. specified `op` cannot be `dance` etc).

Enjoy! Thanks for your enthusiasm!
