### ISSUE TITLE
How one handle orphans data on the next client sync when permissions are removed for a user.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#467]
From discussion with @chrismbeckett on IRC:

3) Orphaned data in the client db when permissions change.

So you sync a bunch of data based on current permissions, and then another user changes the permissions so that you no longer have rights to that data. However, it is still sitting in their client side IndexDB and never gets nor updated nor removed.

**Comment by leplatrem** [comment]
This is a client thing I guess. If one walks away with some data, what could do the server? Re-open if relevant :)
