### ISSUE TITLE
Metadata on Groups

### ISSUE THREAD

**Issue by chrismbeckett** [Kinto/kinto#469]
Similarily to how you can store extra properties (metadata) on a collection, it would be useful to be able to do this with groups.

In my applications, almost everything is dynamic. Users can create groups on the fly, rename them, etc., so I tend to use generated ID's for everything. It would be nice to be able to set a title and description on groups for UI presentation.

Right now I have to create a collection for storing group metadata separately from the actual group.

**Comment by leplatrem** [comment]
See an example of implementation (for buckets): https://github.com/Kinto/kinto/pull/462/files
