### ISSUE TITLE
Add the flush capability if enabled.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#487]
As for #270 we should also add the capability if flush is enabled.

**Comment by lavish205** [comment]
will solving #270 fix this?

**Comment by almet** [comment]
@lavish205 that's the same idea, but that's not the same code exactly: one will need to do the same work for exposing this "flush" capability.

**Comment by lavish205** [comment]
"flush" capability same as "schema" and "attachments" right?

**Comment by almet** [comment]
Yes !

**Comment by lavish205** [comment]
I am working on this bug.

**Comment by Natim** [comment]
```
config.add_api_capability("flush",
                          description="The __flush__ endpoint can be used to remove all data from all backends.",
                          url="http://kinto.readthedocs.org/en/latest/configuration/"
                              "settings.html#activating-the-flush-endpoint")
```

**Comment by almet** [comment]
I would be in favor of `flush_endpoint_enabled`, which I think conveys more meaning (flush could be just anything)

**Comment by Natim** [comment]
Implemented in https://github.com/Kinto/kinto/pull/496
