### ISSUE TITLE
POST with If-None-Match: * and provided id in body always return 412

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#489]
Detected using kinto-client v0.4.0 https://github.com/Kinto/kinto-client/blob/v0.4.0/src/requests.js#L188-L205

See https://github.com/mozilla-services/cliquet/issues/673

**Comment by n1k0** [comment]
Note: kinto-client v0.4.1 has been released with an appropriate client-side fix https://www.npmjs.com/package/kinto-client

**Comment by almet** [comment]
So I believe we should close this issue!

**Comment by n1k0** [comment]
Well, kinto-client now perform PUT requests only for creation because of this limitation, though there are stil llegit use cases for allowing POST methinks. This should be reopened, but I'm not 100% sure so pinging @leplatrem here.

**Comment by leplatrem** [comment]
The fix was merged in cliquet https://github.com/mozilla-services/cliquet/pull/675
