### ISSUE TITLE
kinto start takes too much time.

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#490]
It can sometimes take more than 2 seconds, as reported by @n1k0 on JS clients integration tests.

I investigated a bit and found out, that on my machine, loading the entrypoint takes more than 1 second already:
```
$ time python -c "from pkg_resources import load_entry_point; load_entry_point('kinto', 'console_scripts', 'kinto')"
python -c   0,96s user 0,16s system 99% cpu 1,132 total
```

In comparison, `pserve` takes 200msec: 
```
$ time python -c "from pkg_resources import load_entry_point; load_entry_point('pyramid', 'console_scripts', 'pcreate')"
python -c   0,18s user 0,09s system 98% cpu 0,272 total
```

I realized that moving `import requests` from `cliquet.initialization` imports [PR](https://github.com/mozilla-services/cliquet/pull/674), and remove `import pip` from `kinto.__main__` I could reduce by half:
```
$ time python -c "from pkg_resources import load_entry_point; load_entry_point('kinto', 'console_scripts', 'kinto')"
python -c   0,36s user 0,18s system 98% cpu 0,543 total
```

I knew this was not going to speed up the `kinto start` command too much. I tracked down and noticed the `__main__:main` was executed twice because of `--reload` argument.

**Comment by n1k0** [comment]
:+1: (please)
