### ISSUE TITLE
Use matrix.includes in travis.yml rather than BASH ifs

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#511]
Here : https://github.com/Kinto/kinto/blob/master/.travis.yml#L25-L30

We are doing some:

    if [[ $ACTION != loadtest_tutorial && $ACTION != loadtest_simulation ]]; then pip install tox; fi

We should rather use ``matrix.include`` to define the right thing for each tests.

See: https://github.com/mozilla-services/xml2kinto/blob/master/.travis.yml

**Comment by leplatrem** [comment]
Done in #519
