### ISSUE TITLE
It doesn't seems possible to configure Redis event listener from environment variables.

### ISSUE THREAD

**Issue by happy-tanuki** [Kinto/kinto#515]
I tried to [get-stated](http://kinto.readthedocs.org/en/latest/get-started.html#using-docker-compose) and It's fine. kinto is great. 

Next I want to use the redis listener in the [Notifications section](http://kinto.readthedocs.org/en/latest/configuration/settings.html#notifications).
The some lines were added to docker-compose.yml.

    redis:
        image: redis
    web:
        ....
        links:
            - db
            - redis
        ....
        environment:
            ....
            KINTO_EVENT_LISTENERS: redis
            KINTO_EVENT_LISTENERS_REDIS_USE: cliquet.events.redis
            KINTO_EVENT_LISTENERS_REDIS_URL: redis://redis:6379/0
            KINTO_EVENT_LISTENERS_REDIS_POOL_SIZE: 5
            KINTO_EVENT_LISTENERS_REDIS_LISTNAME: queue

When `docker-compose up`, the error occurred.

    web_1   | Traceback (most recent call last):
    web_1   |   File "/usr/local/lib/python3.5/dist-packages/cliquet/initialization.py", line 399, in setup_listeners
    web_1   |     listener = listener_mod.load_from_config(config, prefix)
    web_1   | AttributeError: module 'redis' has no attribute 'load_from_config'

When the value of `KINTO_EVENT_LISTENERS` was changed to `cliquet.listeners.redis`, kinto was launched. (`redis` or `cliquet.events.redis` in the document are wrong?).

When I update the value, the another error occurred.

    web_1   | 2016-03-25 02:01:13,648 ERROR [cliquet.initialization][waitress] "POST  /v1/buckets/.../records" 201 (11 ms) Unable to send the payload to Redis agent=curl/7.43.0 authn_type=basicauth collection_id=record collection_timestamp=1458871273636 errno=None exception=Traceback (most recent call last):
    ...
    web_1   |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 538, in send_packed_command
    web_1   |     self.connect()
    web_1   |   File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 442, in connect
    web_1   |     raise ConnectionError(self._error_message(e))
    web_1   | redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

If the value of `KINTO_EVENT_LISTENERS_REDIS_URL` was changed to any value, the same error occurred. Why this environment value was not only able to set?

My environment is:
* Docker version 1.10.3, build 20f81dd
* docker-compose version 1.6.2, build 4d72027
* OS X EI Captain 10.11.3

**Comment by Natim** [comment]
> Is ``cliquet.events.redis`` in the document wrong?

Yes probably, we need to change that, do you mind filing a pull-request to fix this?

**Comment by Natim** [comment]
> redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
> If the value of KINTO_EVENT_LISTENERS_REDIS_URL was changed to any value, the same error occurred. 

That's a good point.

According to the code, it should be: ```KINTO_EVENT_LISTENERS_REDIS_URL``` so you are right.
I will investigate why it doesn't work.

**Comment by Natim** [comment]
So using:

```
kinto.event_listeners = redis
kinto.event_listeners.redis.use = cliquet.listeners.redis
kinto.event_listeners.redis.url = redis://redis:6379/0
kinto.event_listeners.redis.pool_size = 5
kinto.event_listeners.redis.listname = queue
```

It seems to work.

**Comment by Natim** [comment]
Using ``KINTO_EVENT_LISTENERS_REDIS_URL=redis://redis:6739/0`` instead it doesn't.

**Comment by happy-tanuki** [comment]
Thank you for your investigation!

**Comment by leplatrem** [comment]
Is this fixed (as by #516) ?

**Comment by Natim** [comment]
No :)

**Comment by leplatrem** [comment]
Note: This also applies to authentication settings (e.g `multiauth.policy.ipauth1.use`)

**Comment by happy-tanuki** [comment]
@leplatrem according to the document, I could use the custom config file in `docker-compose.yml`. But it seems `kinto.event_listeners` parameter was not affected. (no messages in logger and the another redis client cannot subscribe.)

**Comment by happy-tanuki** [comment]
@leplatrem It's worked! I misunderstood a event-listener behavior which is not `PUBLISH` but `LPUSH`.
And by the redis' default, keyspace events notifications are disabled. http://redis.io/topics/notifications Thanks.

**Comment by leplatrem** [comment]
:+1: 

Regarding do you think it would be worth adding a mention in the documentation ?

**Comment by happy-tanuki** [comment]
No problem. I missed the usage of [redis listener](http://kinto.readthedocs.org/en/latest/tutorials/notifications-custom.html#run-asynchronous-code) in the documentation.
