### ISSUE TITLE
Batch documentation misses the "data" attributes in the requests

### ISSUE THREAD

**Issue by magopian** [Kinto/kinto#526]
In the [batch documentation](http://kinto.readthedocs.org/en/latest/api/1.x/cliquet/batch.html), the example request doesn't include the `data` attribute. It says:
```
...
"requests": [
    {
      "body" : {
        "title": "MoFo",
        "url" : "http://mozilla.org",
        "added_by": "FxOS",
      }
    },
...
```

While it should read:
```
...
"requests": [
    {
      "body": {
         "data" : {
         "title": "MoFo",
         "url" : "http://mozilla.org",
         "added_by": "FxOS"
        }
      }
    },
...
```

The document isn't very explicit regarding the `defaults` section either (with regards to the `path` attribute. Also, there's some trailing slashes that shouldn't be there.

**Comment by leplatrem** [comment]
Fixed http://kinto.readthedocs.org/en/latest/api/1.x/cliquet/batch.html
