### ISSUE TITLE
iOS/Android SDK?

### ISSUE THREAD

**Issue by TofPlay** [Kinto/kinto#528]
Do you have an SDK for iOS and Android?

**Comment by Natim** [comment]
Not yet but it is something we would like the community to help us make.

**Comment by almet** [comment]
Currently, [there is some Kinto-related Java code inside the Firefox tree](https://github.com/mozilla/gecko-dev/search?l=java&q=kinto&utf8=%E2%9C%93), but nothing has been put together as a library. 

@pocmo worked on this. Would you like to work on making this happen?

**Comment by TofPlay** [comment]
I can not help for Android. I'm just an iOS developer.
Work on the iOS part could be fun 😀
But unfortunately I have not the time for that. I'm already very busy with my job 😓

**Comment by leplatrem** [comment]
Related #327 #402

**Comment by leplatrem** [comment]
See Android client https://github.com/intesens/kinto-http-java :)
