### ISSUE TITLE
Create Collection event notification not fired for auto-create on default bucket

### ISSUE THREAD

**Issue by chrismbeckett** [Kinto/kinto#529]
I was hacking around with Redis event notifications today. I setup two separate listeners with filters:

```
kinto.event_listeners = redis1 redis2

kinto.event_listeners.redis1.use = cliquet.listeners.redis
kinto.event_listeners.redis1.url = <url>
kinto.event_listeners.redis1.pool_size = 5
kinto.event_listeners.redis1.listname = kinto:collection:create
kinto.event_listeners.redis1.actions = create
kinto.event_listeners.redis1.resources = collection

kinto.event_listeners.redis2.use = cliquet.listeners.redis
kinto.event_listeners.redis2.url = <url>
kinto.event_listeners.redis2.pool_size = 5
kinto.event_listeners.redis2.listname = kinto:record:create
kinto.event_listeners.redis2.actions = create
kinto.event_listeners.redis2.resources = record
```

To test, I was using the default bucket, and the inserting a sample record to a collection that did not yet exist. Although the collection was auto-created, and the record inserted, only the event for create record was logged to Redis. If I create the collection manually, then the create collection event is logged.

Summary: Auto-created collections on the default bucket are not firing event notifications.

**Comment by almet** [comment]
This is because the default bucket plugin [doesn't call](https://github.com/Kinto/kinto/blob/master/kinto/plugins/default_bucket/__init__.py#L77) the [postprocess method](https://github.com/mozilla-services/cliquet/blob/master/cliquet/resource/__init__.py#L625).

**Comment by leplatrem** [comment]
Oh, very nice catch!
