### ISSUE TITLE
kinto (postrgresql) dependencies aren't installed if pip is too old

### ISSUE THREAD

**Issue by magopian** [Kinto/kinto#530]
By default on some linux boxes pip is still in a very ancient version (eg 1.5.4). Using this version, `pip install kinto && kinto init` doesn't install the needed dependencies, resulting in issues like the following:
```
ImportWarning: PostgreSQL SQLAlchemy dependency missing. Refer to installation section in documentation.
```

**Comment by sunakshi96** [comment]
Hey 
So the solution is to upgrade pip right?

**Comment by leplatrem** [comment]
Yep
