### ISSUE TITLE
Several content type renderers? (rss, geojson, ...)

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#539]
Using Cornice it is possible to define several renderers per view. 

```python
@records.get(permission='get_records')
@records.get(accept='application/vnd.geo+json', renderer='geojson', permission='get_records')
def get_records(request):
    ....
    return [...]
```

The renderer will be chosen based on `Accept` request header.

Using Cornice/Cliquet resources, it does not seem obvious to define several views, since it is done during [resource registration](https://github.com/mozilla-services/cliquet/blob/3.1.1/cliquet/resource/__init__.py#L97-L98)

What would be the best way to have a plugin that renders a specific output (e.g. rss/geojson) on the GET records endpoint ?

/cc @almet

**Comment by leplatrem** [comment]
Something like would work (with a minimal piece of code in cliquet): 

```python
@resource.register(name='record',
                   collection_path=_parent_path + '/records',
                   record_path=_parent_path + '/records/{{id}}',
                   renderers=[('geojson', 'application/vnd.geo+json'), ('rss', 'application/rss+xml')])
```

But it is not pluggable. 

We could read them from settings though:

```ini
kinto.record_get_renderers = geojson:application/vnd.geo+json
                             rss:application/rss+xml
```

Thoughts?

**Comment by almet** [comment]
Maybe the plugin could inspect the list of resources defined (using `cornice.get_services`), and register a new view for the service with the specified renderer?

**Comment by leplatrem** [comment]
No concrete use-case right now, closing.

**Comment by Natim** [comment]
So far we used a plugin to add the specific route. ([blocklist XML for instance](http://github.com/mozilla-services/kinto-amo))
