### ISSUE TITLE
"Running in production" doesn't point to the app.wsgi file

### ISSUE THREAD

**Issue by magopian** [Kinto/kinto#543]
The [running in production with uwsgi doc](http://kinto.readthedocs.org/en/latest/configuration/production.html#running-with-uwsgi) talks about an `app.wsgi` which is provided, but
1/ it's not "there" in the project folder if kinto was installed using pip
2/ it's not in the pip package I think (it's not in https://github.com/Kinto/kinto/blob/master/MANIFEST.in)

So maybe the documentation should be modified to link to the app.wsgi in the repository? (like https://github.com/Kinto/kinto/blob/master/app.wsgi)

**Comment by leplatrem** [comment]
good catch!

I believe we can add it to the MANIFEST.in at least. But you're right the paths can be tedious to find within the pip site-packages folders...

Mentionning the file URL online also makes sense.

As a stretch goal, we could also run uwsgi in the Dockerfile to make sure the app.wsgi runs properly there
