### ISSUE TITLE
The documentation for running in production stores the kinto.sock in a tmpfs

### ISSUE THREAD

**Issue by magopian** [Kinto/kinto#545]
Following the configuration for [running in production with uwsgi](http://kinto.readthedocs.org/en/latest/configuration/production.html#running-with-uwsgi), it advises to store the `kinto.sock` file in `/var/run/uwsgi/kinto.sock` which, at least on some distributions, is a tmpfs (temporary filesystem).

This makes uwsgi complain: `bind(): Permission denied [core/socket.c line 185]`

See also http://stackoverflow.com/questions/12778646/uwsgi-socket-permissions

**Comment by Natim** [comment]
I don't think the tempfs is responsible for permission denied. Are you sure the user defined in the config have got the needed permission to write in this folder and that the folder actually exists?
