### ISSUE TITLE
Crash on records list endpoint when the collection is empty and readonly is true

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#558]
When the collection has no record and was never reached, a timestamp is stored.

This does not work if `readonly` is true because the user does not have the permission to insert into the timestamp table.

We should not try to bump the timestamp when `readonly` is true.

See:
* Kinto/kinto#433
* https://github.com/mozilla-services/cliquet/pull/649

**Comment by leplatrem** [comment]
'cuz of this: https://github.com/mozilla-services/cliquet/blob/3.1.2/cliquet/storage/postgresql/schema.sql#L154-L157

**Comment by Natim** [comment]
I believe this has been fixed with: https://github.com/mozilla-services/cliquet/pull/698

**Comment by Natim** [comment]
I might be wrong.

**Comment by Natim** [comment]
Is it possible to silently log the timestamp query error?
