### ISSUE TITLE
move permissions documentation to Cliquet

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#561]
Nothing in Kinto's permissions doc is specific to Kinto. Move it over to Cliquet and just link to it from here.

**Comment by Natim** [comment]
I am  a bit reluctant doing that. Kinto is a product and we would like its documentation to be as complete as possible without having to go in the cliquet library documentation.

However permissions in Kinto have a lot of specificities that cliquet doesn't have such as [inheritance](https://github.com/Kinto/kinto/blob/master/kinto/authorization.py#L24-L67).

So I would rather improve the Kinto documentation to make it more specific to Kinto permission handling.

**Comment by glasserc** [comment]
Re: "without having to go into the cliquet library documentation": I wrote my thoughts about that in #560.

I agree that the Kinto permissions app should cover anything specific to Kinto, such as inheritance. But of the current Kinto permissions documentation, most of it isn't specific to Kinto. The "formalism" section defines the set of possible permissions, and there should be something like it in Cliquet (but there isn't). "Get the current user ID" is true for any Cliquet app. "Retrieve/add/modify permissions" is all generic for any Cliquet app. Nothing covers inheritance. As with the rest of the Kinto documentation, I think this document would be more helpful if it provided a high-level summary and linked to Cliquet for details.

**Comment by Natim** [comment]
Ok

**Comment by glasserc** [comment]
This issue doesn't make sense any more since now all the documentation is grouped together automatically.
