### ISSUE TITLE
retitle javascript.rst "Guide to implementing a client"

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#562]
The `javascript.rst` tutorial in this documentation is basically a low-level guide to implementing a client. I don't think it's useful considering the `HTTPie` examples strewn throughout the documentation, but if we're going to keep it, we should make it extremely clear that this code is meant for library developers and NOT for JavaScript application developers.

**Comment by glasserc** [comment]
Another alternative is to move it into Kinto.js with a title like "How to add support for a new Kinto command to Kinto.js". What do you think @n1k0 ?

**Comment by n1k0** [comment]
To be entirely honest I didn't remember there was a js tutorial in these docs :)

Now I see it, it seems a little redundant with what [kinto-client](https://github.com/Kinto/kinto-client) offers in terms of HTTP API support. *kinto-client* probably covers most developer needs when it comes to consuming the Kinto HTTP API, and as it's itself a dependency of Kinto.js... we're pretty much safe here I think.

I'd probably add a link to kinto-client and start thinking about how could look more generic docs for implementing clients (maybe the existing docs are already good enough, I didn't check).

**Comment by glasserc** [comment]
OK, let's split this task into #578 (removing the JS tutorial that we have), which is easy, and #579 (coming up with a guide for implementors), which is future work.
