### ISSUE TITLE
ReadTheDocs links to "edit on github" are broken

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#573]
In the stable version, they point to version b19b46cbc11ef33305ea4ee7848eee830a07377d. I have no idea why.

**Comment by glasserc** [comment]
This appears to be related to https://github.com/rtfd/readthedocs.org/issues/1820.

**Comment by magopian** [comment]
Submitted a PR to address this issue: https://github.com/rtfd/readthedocs.org/pull/2428

**Comment by leplatrem** [comment]
Resolved upstream

**Comment by glasserc** [comment]
As far as I can tell, it hasn't yet been.

**Comment by Natim** [comment]
See https://github.com/rtfd/readthedocs.org/issues/1820

**Comment by leplatrem** [comment]
A new fix was proposed upstream https://github.com/rtfd/readthedocs.org/pull/3302

**Comment by leplatrem** [comment]
Bug still there ;)

**Comment by magopian** [comment]
Seems the fix in the above PR on readthedocs was reverted, and the current issue tracking it is https://github.com/rtfd/readthedocs.org/pull/3441 (some issue with the git version used on their servers if I understand correctly?)

**Comment by magopian** [comment]
This now seems fixed, see https://github.com/rtfd/readthedocs.org/issues/1820
