### ISSUE TITLE
Enabling the flush endpoint through env vars does not seem to work

### ISSUE THREAD

**Issue by honi** [Kinto/kinto#588]
I'm running Kinto + postgres with docker-compose (using the example docker-compose.yml in the repo). 

Adding ```KINTO_FLUSH_ENDPOINT_ENABLED``` to the environment section in docker-compose.yml does not enable the flush endpoint for me. I instead had to add ```kinto.flush_endpoint_enabled = true``` to a custom ini file, that worked.

Can the flush endpoint be enabled through an env var like this?

**Comment by Natim** [comment]
Let me try :)

**Comment by Natim** [comment]
I can confirm that adding ``KINTO_FLUSH_ENDPOINT_ENABLED`` env variable doesn't work.

**Comment by Natim** [comment]
Refs #515
