### ISSUE TITLE
Add the plugins versions

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#591]
It would be nice to have the versions of each plugin displayed on / in capabilities.

When deployed with kinto-dist I guess we can find them back, but that's extra work :)

**Comment by almet** [comment]
That's a good idea! For this, we would have to:

- Add a version parameter in the cliquet [`add_api_capability` method](https://github.com/mozilla-services/cliquet/blob/master/cliquet/__init__.py#L126)
- It would show up directly [in the hello view](https://github.com/mozilla-services/cliquet/blob/master/cliquet/views/hello.py#L48)
- Write some tests to test this works as expected

**Comment by Natim** [comment]
We need to add a global option to let OPS hide this version information because in production the version information can be used to detect vulnerable deployments if we were to have CVE in the future.

**Comment by almet** [comment]
That's the case with the current deployment anyway (the kinto version is present).

We should open another issue for this. I'm not sure hiding the version will gain us some security? I would love to have mozsec input on this!

**Comment by tarekziade** [comment]
@Natim That's orthogonal. If we want to avoid any leakage of information, we should firewall the access to those /__VIEWS   

That's why I've initially created the __ prefix standard

**Comment by Natim** [comment]
Yes then maybe do we need to add a /__versions__ view rather than adding them on the root endpoint (that doesn't contains any __ prefix)

**Comment by leplatrem** [comment]
>  If we want to avoid any leakage of information, we should firewall the access to those /__VIEWS 

Apparently this is not going to be the case: https://bugzilla.mozilla.org/show_bug.cgi?id=1268823#c2

**Comment by tarekziade** [comment]
Even though we're not hiding them I am skeptical about the fact that hiding the version numbers is a good practice - apache and nginx don't do it afaik.

Let's ask @ulfr

Also: let's not add yet another info page, this is getting overkill

**Comment by Natim** [comment]
It is usually a good practice to ask nginx to hide its version number: http://krischan.eu/index.php/2014/01/11/howto-hide-your-web-server-version-number-apache-lighttpd-nginx/

**Comment by jvehent** [comment]
We don't hide release versions today. I don't think we need to in the future.
```bash
$ curl https://shavar.services.mozilla.com/__version__
{
    "commit": "a92303b58b9c9cea0b74896a9b6e011e964e51b9",
    "source": "https://github.com/mozilla-services/shavar.git",
    "version": "0.6.9"
}
```

**Comment by Natim** [comment]
Ok let's make it simple, we can improve it later if need is :+1:

**Comment by Natim** [comment]
- [ ] [kinto-signer](https://github.com/Kinto/kinto-signer/pull/108)
