### ISSUE TITLE
Add an endpoint to list objects and permissions of current user 

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto#600]
Context: The kinto-admin where we need to render a tree of buckets and collections the authenticated user has access to.

If you don't have read permission to the bucket containing a collection you have read access for, you can't see that bucket listed anywhere it seems. In an ideal world, I'd expect that if I have access to `/buckets/buck/collections/coll`:

- I could query `/buckets` and see `buck` listed;
- I could query `/buckets/buck/collections` and see `coll` listed.

Silly thoughts: 

- Maybe we need a new `enumerate` permission type?
- Maybe we need a new endpoint (possibly through a plugin) allowing to retrieve the tree of available resources for a given authenticated user? eg.

```
$ http http://kinto/v1/access
{
  "buckets": [
    {
      id: "buck",
      permissions: {
        write: [...], read: [...]
      },
      collections: [
        {
          id: "coll",
          permissions: {
            write: [...], read: [...]
          }
        },
        ...
      ]
    },
    ...
  ]
}
```

If that's not possible for whatever reason, how should we retrieve the list of resources an authenticated user has access to?

Note that another possible answer might be that this is just matter of configuring all this manually, by setting permissions individually per resource in the tree; though that would mean giving read permission to containers we don't actually want to fully expose to the user.

**Comment by Natim** [comment]
This can probably be considered as a know bug. And we should fix it.

**Comment by leplatrem** [comment]
> considered as a know limitation/**bug**

I don't think it's a bug. A limitation yes. See #442 for a related discussion.

Indeed, with our current permission tree, if the client has not the permission to read the parent object, it cannot see its attributes. Although it can obtain a list of the children (full or partial) that it can read/write.

> Maybe we need a new enumerate permission type?

What would be the difference with read?

> allowing to retrieve the tree of available resources for a given authenticated user

That sounds acceptable and useful ! The only detail is that we would not be able to obtain attributes of parent object for which we have no read permission.


```
$ http http://kinto/v1/access
{
  "buckets": [
    {
      url: "/buckets/buck",
      data: {
          id: "buck",
      },
      permissions: {
        write: [...], read: [...]
      },
      collections: [],
   }, {
      url: "/buckets/buck",
      collections:  [{
          id: "coll",
          permissions: {
            write: [...], read: [...]
          }
        },
        ...
      ]
    },
    ...
  ]
}
```

**Comment by n1k0** [comment]
>> Maybe we need a new enumerate permission type?
>What would be the difference with read?

Basically allowing to list an entry id but not to access its data.

> allowing to retrieve the tree of available resources for a given authenticated user

That sounds acceptable and useful ! The only detail is that we would not be able to obtain attributes of parent object for which we have no read permission.

Well, couldn't we easily infer the nested structure here? If we know the url for a collection we have access to, we know the bucket name it's attached to; so we can build the tree. Am I missing smthg?

**Comment by leplatrem** [comment]
Actually an export of the permission backend will be useful: a tree of `{parentURI, URI, id}`

**Comment by leplatrem** [comment]
One idea: ``GET /permissions``

```js
{
    "buckets": [
        {
            id: "certificates",
            uri: "/buckets/certificates",
            permissions: ["read", "write"]
        },
        {
            id: "blog",
            uri: "/buckets/blog",
            permissions: []
            collections: [
                {
                    id: "articles",
                    uri: "/buckets/blog/collections/articles",
                    permissions: [],
                    records: [
                        {
                            id: "3c6cd52c-75ba-46da-8bf3-d658ddb204a0",
                            uri: "/buckets/blog/collections/articles/records/3c6cd52c-75ba-46da-8bf3-d658ddb204a0",
                            permissions: ["read"]
                        }
                    ]
                },
                {
                    id: "comment",
                    uri: "/buckets/blog/collections/comments",
                    permissions: ["record:create"],
                    records: [
                        {
                            id: "f6b4efaf-4cea-4fae-99b8-07fa876aee92",
                            uri: "/buckets/blog/collections/articles/records/f6b4efaf-4cea-4fae-99b8-07fa876aee92",
                            permissions: ["write"]
                        }
                    ]
                }
            ]
        }
    ]
}
```

Cons:
- Can dump millions of entries (Idea: strip children if permission on parent)
- Query to permission backend can be resource greedy

**Comment by n1k0** [comment]
Looks nice, though I'd limit this to buckets and collection, and maybe add an option for records with a big warning regarding perfs in the docs :)

**Comment by leplatrem** [comment]
After discussing with @n1k0, we realized that it would not very convenient to have it as a tree.

Something flat like this would do it:

```
GET /permissions

{
    "data": [
        {
            "uri": "/buckets/toto",
            "resource": "bucket",
            "bucket_id": "toto",
            "permissions": ["read", "write"]
        },
        {
            "uri": "/buckets/tata",
            "resource": "bucket",
            "bucket_id": "tata",
            "permissions": ["collection:create"]
        },
        {
            "uri": "/buckets/toto/collections/test",
            "resource": "collection",
            "bucket_id": "toto",
            "collection_id": "test",
            "permissions": ["record:create"]
        },
        {
            "uri": "/buckets/toto/collections/test/records/d5db6e57-2c10-43e2-96c8-56602ef01435",
            "resource": "record",
            "bucket_id": "toto",
            "collection_id": "test",
            "record_id": "d5db6e57-2c10-43e2-96c8-56602ef01435"
            "permissions": ["write"]
        }
    ]
}
```

In a second step, to reduce the load, it could even be filtrable:

- *For bucket and collection only* :  `/permissions?in_resource=bucket,collection`
- *Every writable record in this bucket*: `/permissions?bucket_id=test&permission=write&resource=record`

What do you think?

**Comment by n1k0** [comment]
I love it!

**Comment by Natim** [comment]
Yes it looks good to me.
