### ISSUE TITLE
Heartbeat max timeout

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#601]
Let's make sure the heartbeat times out before 30 seconds. Otherwise uWSGI hara kiris the web head and we don't have a chance to send back the result of the heartbeat where it tells us which backend fails.

I suggest 15 seconds max by defaut + an option.

**Comment by Natim** [comment]
I though it was already the case do you know for which backend it is not the case?

**Comment by tarekziade** [comment]
The signer blocks for 30s. This should be enforced by the whole heartbeat view, not delegated by each backend. Because 30s + 30s + 30s... :)
