### ISSUE TITLE
[cliquet] Split tests from kinto package

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#605]
original : https://github.com/mozilla-services/cliquet/issues/267

Should we have tests within the kinto package or outside ? that was discussed but I don't think a decision was made.

Another related question is not wether tests is in kinto/ or outside, but rather : do we ship tests when we release kinto ? some people strip them when they build the release.

**Comment by leplatrem** [comment]
I would be in favor of moving them outside (if possible), and let test helpers in something like `kinto.testing`.

I don't know if it could help us decide but we currently specify the test suite in `setup.py` https://github.com/Kinto/kinto/blob/master/setup.py#L105
