### ISSUE TITLE
[cliquet] Release the permission code as a separate library

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#606]
Original : https://github.com/mozilla-services/cliquet/issues/336

@Lothiraldan proposed to split permissions in its own package. 

I am -1 on this for the same reason I think it's great that cliquet came back in kinto/

@Lothiraldan do you have a project that uses kinto.permissions ?

**Comment by leplatrem** [comment]
The original issue is more than a year old, I close. Feel free to reopen if you think this is still relevant...
