### ISSUE TITLE
Add limit for cache size (especially memory)

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#610]
original: https://github.com/mozilla-services/cliquet/issues/406

That's an improvement so we control the cache size. Otherwise it's a free wheel that eventually crashes the server. 

Which makes me think: if I do a load test on stage today, is the kinto process growing indefinitely in memory ?

**Comment by leplatrem** [comment]
> into process growing indefinitely in memory ?

We use postgresql on stage AFAIK so no problem about crashing the web head I believe

**Comment by tarekziade** [comment]
what about other back-ends ? do we care ? or should we state explicitly in our docs they are not suited for production use ?

**Comment by Natim** [comment]
I think you are right we need to set cache limit somewhere. That's mandatory for cache right?
Then I have no idea of how we should handle a cache oversize? Should we raise ? Should we delete some old data? How?

**Comment by leplatrem** [comment]
Limiting cache size applies to every backend I think. Writing to cache could prune the oldest data until the total size is bigger than a limit.

**Comment by tarekziade** [comment]
> Should we raise ? 

No, caching should not impact the result of the web service calls. just speed it. So if the cache is full, it's up to the application to do whatever it wants to optimize it. 

Sorting by date is one option, another one could be by hits e.g. getting rid of the least called cached entries.

**Comment by leplatrem** [comment]
This requires:

* Generalize storage migration mecanism to cache backend
* Add a hits attribute to track calls to cached entries
* Add a created attribute to track insertion/refresh
* Compute size of value and denormalize total
* Before inserting: if total > max_size then sorte entries by hits+created and delete keys until total < max_size
