### ISSUE TITLE
[cliquet] Broken list in the ecosystem documentation

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#613]
original https://github.com/mozilla-services/cliquet/issues/688

broken link on "many available packages"
 
 http://kinto.readthedocs.io/en/stable/core/ecosystem.html

**Comment by glasserc** [comment]
I'll fix this as part of my documentation cleanup PR.

**Comment by tarekziade** [comment]
Fixed in https://github.com/Kinto/kinto/commit/0e3880710d4049e2e2fdc013d8d0b46cc7a5b88c
