### ISSUE TITLE
[cliquet] DELETE operation always returns 200 on success, while the spec suggests otherwise

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#629]
original: https://github.com/mozilla-services/cliquet/issues/682

@leplatrem said: "We must return 200 with the list of objects that were deleted."

**Comment by leplatrem** [comment]
Closing because I'm pretty sure the current behaviour is fine:
http://kinto.readthedocs.io/en/stable/api/1.x/buckets.html#delete-all-buckets

@n1k0 please reopen if you remember why we had opened that.

**Comment by n1k0** [comment]
AFAICR my issue back in the days was that we were receiving a 200 even if call to flush was not finished. tbh I never experienced  any trouble with the flush endpoint since I've been refactored the test setup strategy in kinto-node-test-server, so it's probably fine to mark this as obsolete.
