### ISSUE TITLE
Return the authenticated username on the hello page.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#641]
- Using basic auth we could return the user part.
- Using FxA the email address.

It will ease displaying the username on the kinto-admin.

**Comment by Natim** [comment]
See https://github.com/Kinto/kinto-admin/pull/80#issuecomment-221219579

**Comment by almet** [comment]
It is actually possible (and might be a better thing to have) to import the name of the user |by asking the profile server](https://github.com/mozilla/fxa-profile-server/blob/master/docs/API.md#get-v1display_name). It is also possible to [ask for the email address](https://github.com/mozilla/fxa-profile-server/blob/master/docs/API.md#get-v1email).

Also note that [the email address that's returned by the account server](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#get-v1accountprofile) needs the auth to have the proper token scope.

**Comment by Natim** [comment]
Yes we could try to get the email from the profile server if the profile:email scope is available.

**Comment by almet** [comment]
Well, my point was more that it's possible to get the full name of the user :)

**Comment by leplatrem** [comment]
> Using basic auth we could return the user part.

No. There is no *user part*. We have invited our users to use a `token:`!

**Comment by leplatrem** [comment]
Actually, I fear that this introduces some confusion with the user id to be used in permissions definitions...

We could let the client do these calls no? 

I put a -1 on the idea, but I may be wrong, please explain why it makes sense to do on the server side :)

**Comment by Natim** [comment]
> No. There is no user part. We have invited our users to use a token:!

Well does it makes sense with the admin too?

**Comment by tarekziade** [comment]
> It will ease displaying the username on the kinto-admin.

I am also confused because ISTM the dashobard has all the info. Can you describe the detailed use case in a user story ?

**Comment by Natim** [comment]
Yes: when people are connected on Kinto I want to display their username / email address in the header to inform them. (i.e Gmail header)

**Comment by leplatrem** [comment]
>> No. There is no user part. We have invited our users to use a token:!
>
> Well does it makes sense with the admin too?

In theory, the kinto-admin should adapt to the notions of the protocol. Even if it means replacing the username and password fields of basic auth by a single «token» field.
Maybe this is not possible in practice...

(Related  #297 and #395)

> I would like to find a way to do it that works regardless of the login method.

Yes, I think that is the main argument in favor of doing this on the server side.

**Comment by Natim** [comment]
I think what the doc propose with token:api-key is just a convention.

We never choose to prevent people from using username:api-key did we?

**Comment by leplatrem** [comment]
> We never choose to prevent people from using username:api-key did we?

Indeed :)

**Comment by almet** [comment]
But that is not the recommendation we're making i' the docs though (where we recommend using token:passwd). 

I believe it would be a good idea to make a decision on this and adapt the docs and admin accordingly (either use app token or something else but  we need to be consistent)

**Comment by leplatrem** [comment]
Closing...
Feel free to reopen if you have some opinion on this :)
