### ISSUE TITLE
Shall we speak about protocol or interface?

### ISSUE THREAD

**Issue by enguerran** [Kinto/kinto#664]
The documentation is a little bit confusing:

> __Kinto-Core Protocol__
    A system of rules that explains the way to interact with the HTTP API endpoints (utilities, synchronization, headers etc.), and how data is organized (JSON responses etc.).

In my opinion, there is no such protocol except the one used to transmit data from and to kinto: http.

Instead we may speak about a _meta REST API_ to manipulate the wanted REST API. For instance, if I want to create an REST API about pictures, I will use the _meta REST API_ to create a bucket, then to create the collection `pictures` then to add a schema to a record of `pictures`.

The protocol in my example is still __HTTP__ with the 5 classic verbs like **GET**, **POST**, **PUT**, **PATCH** and **DELETE**. But the way I control kinto is by using that protocol to perform actions through the correct route like `POST /buckets`.

What do you think?

**Comment by n1k0** [comment]
+1, too much confusion raised lately about what the *kinto protocol* precisely is. +1 for API.

**Comment by leplatrem** [comment]
+1 for API
