### ISSUE TITLE
404 on contributing and on documentation

### ISSUE THREAD

**Issue by enguerran** [Kinto/kinto#665]
I would like to read http://kinto.readthedocs.io/en/latest/contributing.html but it is a 404.

And when I try to "edit the doc" I still get a 404 but [on github](https://github.com/Kinto/kinto/blob/f675883ada5f086bffbc9fe328f130d64214742d/docs/core/reference/glossary.rst)
![screenshot from 2016-05-31 16-35-30](https://cloud.githubusercontent.com/assets/701648/15678188/a08ff212-274d-11e6-8223-51518e0af997.png)

**Comment by glasserc** [comment]
The "Edit on Github" link is a known issue. As far as I can tell, it's a bug in readthedocs. See https://github.com/Kinto/kinto/issues/573.

As for the URL that you sent, that page got folded into the "community" page. Where did you find that link? I opened #666 to try to fix the uses that I could find.

**Comment by Natim** [comment]
You can read it there: http://kinto.readthedocs.io/en/latest/community.html#how-to-contribute

**Comment by enguerran** [comment]
@glasserc the broken link to the "documentation contributing" comes from this page https://github.com/Kinto/kinto/blob/master/CONTRIBUTING.md

![screenshot from 2016-06-01 10-47-59](https://cloud.githubusercontent.com/assets/701648/15703541/26dd78ba-27e6-11e6-96a6-14d210f05323.png)

**Comment by enguerran** [comment]
As there already is #573 and #666, we should close this issue, right?
