### ISSUE TITLE
Hook to change the POSTed/PUTed json data

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#677]
For Fennec, we need to convert the file that's uploaded via the kinto-admin and add some info.

Specifically, the "original" key you see here https://github.com/pocmo/Fennec-DLC-Catalog/blob/master/create_catalog.py#L136 is added to keep track of the original file, and the file itself is zipped.

The goal is to let users upload fonts file in kinto admin and let Kinto take care of all the gzipping work

To do this, I propose the addition of a `kinto.core.events.BeforeResourceChanged` event, that will let us manipulate the json data right before it's turned into a SQL record and pushed in the database (and before the file is pushed in S3 via the kinto-attachment plugin)

**Comment by tarekziade** [comment]
Example of usage:

```python
from kinto.core.events import BeforeResourceChanged

def add_metadata(record):
    record['original'] = {
                'filename': record['filename'],
                'hash': sha256(record['filecontent']),
                'mimetype': record['mimetype'],
                'size': len(record['filecontent']),
            }
  

def on_before_resource_changed(event):
    for record in event.impacted_records:
        add_metadata(record)

config.add_subscriber(on_before_resource_changed, BeforeResourceChanged)
```

**Comment by Natim** [comment]
As far as I understand the use case it seems that you will also gzip the file on the server side isn't it?

**Comment by tarekziade** [comment]
This ended up being a core feature on kinto-attachment, so I am closing this bug
