### ISSUE TITLE
Unable to detect http port in config file

### ISSUE THREAD

**Issue by agentsimran** [Kinto/kinto#698]
![screenshot from 2016-07-04 20-28-08](https://cloud.githubusercontent.com/assets/13584124/16564610/0cdce31a-4226-11e6-8b62-cd8acae2b082.png)

**Comment by leplatrem** [comment]
Indeed, if you leave `%(http_port)s` it will be possible to specify the port from the command line with `kinto start --port 1234`.

Otherwise, you can set any forced value there.

**Comment by leplatrem** [comment]
Closing for lack of feedback :)
