### ISSUE TITLE
Set scheme to https by default in config

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#706]
Mainly because it's easy to forget during deployment. And kinto is very like to be deployed behind https:

See `url` in the root URL here:

![capture d ecran de 2016-07-06 15-24-57](https://cloud.githubusercontent.com/assets/546692/16619299/da075538-438d-11e6-987d-2df56a3ecc38.png)

/cc @almet

**Comment by Prashant-Surya** [comment]
Can I work on this issue?

**Comment by Natim** [comment]
The thing is in development (witch is a even more common use case) you need to have http by default.

My take would be to let http by default and add a warning if https is not turned on.

**Comment by leplatrem** [comment]
> The thing is in development (witch is a even more common use case) you need to have http by default.

What happens if you set `kinto.http_scheme` to `https` in development ?

**Comment by Natim** [comment]
It will redirect you from http://localhost to https://localhost and it will basically fail with a browser connection error.

**Comment by leplatrem** [comment]
@Prashant-Surya, let us follow natim advice and just make a `logger.warning()` if the setting was not set to `https`

**Comment by Prashant-Surya** [comment]
@leplatrem can you briefly describe how should I solve this?

**Comment by Natim** [comment]
Hello @Prashant-Surya you have an example of how to display warnings [in the code](https://github.com/Kinto/kinto/blob/master/kinto/core/initialization.py#L539).

What you need to do is the same things as when project_name is missing but when the http_scheme is http.

**Comment by Prashant-Surya** [comment]
@Natim okay

**Comment by leplatrem** [comment]
Hello @Prashant-Surya !

I saw that you committed a fix for this issue, do you mind opening a pull-request ?

Thanks a lot!
