### ISSUE TITLE
Rename core notions

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#710]
Now that `cliquet` is in `kinto.core`, some naming is confusing.

In the core, resources are called collections, and objects are called records.

But, in Kinto, collections and records are instantiation of resources!

I suggest some renaming in kinto.core: 
- `collection` to `resource`
- `record` to `object`
- `collection_id` to `resource_name`  ~~(or `object_type` ?)~~
- `record_id` to `object_id`

That represents quite some work, but reducing confusion is always worth it.

**Comment by leplatrem** [comment]
* `impacted_records` → `impacted_objects`

**Comment by leplatrem** [comment]
*  `Total-Records` -> `Total-Objects`

**Comment by almet** [comment]
This would allow a lot more readability, that's a good idea.

**Comment by mansimarkaur** [comment]
I'd love to work on this.

**Comment by mansimarkaur** [comment]
`object` is a global variable in Python. Should we be concerned about that when we move from `record` -> `object`?

**Comment by Natim** [comment]
>Should we be concerned about that when we move from `record` -> `object`?

Yes

**Comment by mansimarkaur** [comment]
So, what else should we name a record as if not object?

**Comment by Natim** [comment]
Cannot we be concerned and still use it?

**Comment by Natim** [comment]
To elaborate I think that most of the time we will use `object_id` and if we need to use `object` we can choose to use `obj` instead to not override the `object` Python global variable?

**Comment by mansimarkaur** [comment]
Yes, obj seems to be a good option. Thanks!

**Comment by leplatrem** [comment]
* `Collection endpoint` → `Plural endpoint`
* `Record endpoint` → `Object endpoint`

**Comment by leplatrem** [comment]
`with_deleted=False` → `with_tombstones=False`

**Comment by leplatrem** [comment]
`process_record()` → `process_object()`

**Comment by glasserc** [comment]
`collection_timestamp` -> ?? I don't like `resource_timestamp`. Maybe `plural_timestamp`, or `children_timestamp`?

**Comment by peterbe** [comment]
What about https://kinto.readthedocs.io/en/stable/api/1.x/records.html
We renamed the `Total-Records` header to `Total-Objects` (but kept both to be gentle). Should the `/records` (and its documentation) be redirects for `/objects` now?

**Comment by leplatrem** [comment]
Nope, because in this case `records` is not a «core notion». Now core has the notion of objects, and buckets, collections, groups, records and accounts leverage it.

Before it was confusing because there were the terms records and collections in kinto.core...
