### ISSUE TITLE
Overflow error with log and json.dumps

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#717]
```
OverflowError: Overlong 2 byte UTF-8 sequence detected when encoding string
(7 additional frame(s) were not displayed)
...
  File "structlog/stdlib.py", line 81, in error
    return self._proxy_to_logger('error', event, *args, **kw)
  File "structlog/stdlib.py", line 119, in _proxy_to_logger
    **event_kw)
  File "structlog/_base.py", line 176, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "structlog/_base.py", line 136, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "cliquet/logs.py", line 126, in __call__
    return utils.json.dumps(event_dict)
```

**Comment by magopian** [comment]
Is there a way to reproduce this issue? Do you have data or a list of steps?

As a preliminary investigation, I found out that it might be raised by this line of code in the ujson library: https://github.com/pydata/pandasjson/blob/adcad445673b274728957f20643eb4e0975e79c5/ujson/lib/ultrajsonenc.c#L287

**Comment by leplatrem** [comment]
We don't.

But it may be a remaining sequel of #740 ... 

Trying to find a URL path that matches `(ucs < 0x80)` with `ucs = ((in & 0x1f00) >> 2) | (in & 0x3f);` :)

I feel like I'm in front of this:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/73bdee965f9f7addd1f83c423bec53b4c01504de)

I know I could get it with a lot of efforts, but my brain gets on strike.

So I would vote to close now that we have #740 and see if it appears again.

**Comment by magopian** [comment]
Agreed, let's close this one, and reopen if needed (and then maybe do something like first safely encode to utf-8, and only then do the `json.dumps`).
