### ISSUE TITLE
Development backend (memory) should be transaction aware.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#754]
In order to switch from the memory to the postgresql backend to run tests, we need to work on:
- [ ] kinto/tests/core/resource/*
- [ ] kinto/tests/core/test_authentication.py
- [ ] kinto/tests/core/test_logging.py
- [ ] kinto/tests/core/test_deprecation.py
- [ ] kinto/tests/core/test_statsd.py
- [ ] kinto/tests/core/test_views_batch.py
- [ ] kinto/tests/core/test_views_errors.py
- [ ] kinto/tests/core/test_views_heartbeat.py
- [ ] kinto/tests/core/test_views_hello.py
- [ ] kinto/tests/test_config.py

**Comment by leplatrem** [comment]
Why would we want to switch from memory to postgresql to run tests ? There are gonna be slower ! 
What is the use case ?

**Comment by Natim** [comment]
The problem we have right now is that the memory backend is not transaction aware. You cannot run the quota plugin tests with the memory backend for instance.

Also I we were to make the memory backend to handle transaction, all the tests listed before would fail.

**Comment by leplatrem** [comment]
Making the memory backend transaction aware requires to implement the `transaction` managers (see https://github.com/zopefoundation/transaction/blob/master/transaction/tests/examples.py)

Do you think it is worth it?

**Comment by Natim** [comment]
I'd like us to be consistent for features based on transaction, so I guess it worth it but right now we don't need it.

**Comment by leplatrem** [comment]
Archiving old issues
