### ISSUE TITLE
pypy tests doesn't run anymore because the side_effect is not triggered.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#755]
In [this test](https://github.com/Kinto/kinto/blob/1abb2554dfa9a55b710fac206a516acca11421e9/tests/core/test_views_transaction.py#L167), we are doing a side effect on `pyramid_tm.transaction.manager.commit` but pypy doesn't raise anymore.

Apparently the `transaction` lib version didn't change, neither the `pyramid-tm` one.

**Comment by magopian** [comment]
For reference, the way to run a single test using tox (running pytest) is as follows:

```.venv/bin/tox -e pypy -- tests/core/test_views_transaction.py::TransactionEventsTest::test_resourcechanged_is_rolledback_with_transaction```
