### ISSUE TITLE
kinto.id_generator option doesn't work

### ISSUE THREAD

**Issue by doplumi** [Kinto/kinto#757]
#### Issue
As per the [docs](http://kinto.readthedocs.io/en/latest/configuration/settings.html?highlight=id_generator#feature-settings), we should be able to define a `kinto.id_generator` options that will work for records, but this is not the case in the current (3.4.0.dev0) implementation.

#### Easy workaround ####
As an easy fix, you can specify the `record` type as in `kinto.record_id_generator`.

**Comment by leplatrem** [comment]
Thanks for this feedback! It's a bug indeed, we should either support the former setting or make this breaking change explicit (would lead to kinto 4.0)
