### ISSUE TITLE
List user data in a shared collection

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#76]
```http GET https://kinto.dev.mozaws.net/v1/buckets/todo/collections/tasks/records         -v --auth 'bob:bobpassword'```

```
GET /v1/buckets/todo/collections/tasks/records HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic Ym9iOmJvYnBhc3N3b3Jk
Connection: keep-alive
Host: kinto.dev.mozaws.net
User-Agent: HTTPie/0.9.2

HTTP/1.1 403 Forbidden
Access-Control-Expose-Headers: Backoff, Retry-After, Alert, Next-Page, Total-Records, Last-Modified, ETag
Connection: keep-alive
Content-Length: 95
Content-Type: application/json; charset=UTF-8
Date: Thu, 18 Jun 2015 16:45:11 GMT
Server: nginx/1.4.6 (Ubuntu)

{
    "code": 403, 
    "errno": 121, 
    "error": "Forbidden", 
    "message": "This user cannot access this resource."
}
```

We should have a list of bob's tasks

**Comment by leplatrem** [comment]
That is something we had in mind for cliquet 2.1 indeed. But it implies several complex points:

* Introduce notions of principals in the storage backend
* For collections, let the policy authorize users even if no obvious permission to read ?
* If no record belongs to Bob in the shared collection, then raise 403 inside the resource view ?

**Comment by Natim** [comment]
- [ ] Introduce notions of principals in the storage backend

For the two other point, if the user have the create permission to add thing in the list, we can deduce that he might have created things, and then return an empty list.

**Comment by leplatrem** [comment]
It is not only a matter of having the ``create`` permission.

For example, for the payment tracking use-case:

* Seller has no right to create receipts
* Payments creates receipts records with ``read`` permission for its seller
* Seller can list all receipts where it has ``read`` permission

**Comment by Natim** [comment]
Yes but in case they have the create permission we want to display an empty list rather than a 403

**Comment by leplatrem** [comment]
Since the implementation happens in *Cliquet*, I created a dedicated issue there https://github.com/mozilla-services/cliquet/issues/354

Since there might be some efforts of integration into Kinto (ex. write perm implies read), let's keep this issue opened it is released upstream and available here.
