### ISSUE TITLE
documentation: set of error codes not found

### ISSUE THREAD

**Issue by elelay** [Kinto/kinto#766]
At the end of http://kinto.readthedocs.io/en/stable/api/1.x/errors.html#protocol-description, there is a reference `ref:set of errors codes <errors>` that doesn't work.

I've used [core/errors.py](https://github.com/Kinto/kinto/blob/915390dfd3229eea1e36048ee8fcd5b4c4cf11b8/kinto
/core/errors.py) to know what each errno means, but I can't find the information elsewhere in the documentation and don't know how these `ref` instructions work.

So I don't know how to fix this myself...

**Comment by Natim** [comment]
Indeed this https://github.com/Kinto/kinto/blob/master/kinto/core/errors.py#L31-L74 is supposed to be present there: http://kinto.readthedocs.io/en/latest/core/errors.html

**Comment by Natim** [comment]
@leplatrem fixed it, thanks for reporting it :)
