### ISSUE TITLE
Adding system.Authenticated to a group does not make any user belong to it

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#776]
* Create a group with `"members": ["system.Authenticated"]`
* Add `write` perm to object for `/buckets/test/group/friends`
* Any authenticated user should be allowed to write

**Comment by Natim** [comment]
I am not  sure it is a bug rather than a feature. We were considering ``system.Authenticated`` to be a group in itselve and you cannot add a group to a group.

**Comment by leplatrem** [comment]
We might want to raise a 400 when it's put in the members of a group then.

**Comment by Natim** [comment]
We might, but we need to be able to detect that the principal we've got is not the user_id.
One way to do so is to check that a ``:`` is present in the member we add.

**Comment by Natim** [comment]
But maybe system.Authenticated and system.Everyone should be acceptable because they act as wildcard userid

**Comment by Natim** [comment]
Refs #794

**Comment by leplatrem** [comment]
This bug is still valid as far as I understand, as #794 only applies to group URLs and system.Everyone
