### ISSUE TITLE
Support for filtering records based on a text search

### ISSUE THREAD

**Issue by mvalipour** [Kinto/kinto#791]
As discussed originally [here](http://kinto.readthedocs.io/en/stable/api/1.x/filtering.html#comment-2858589565), I believe there needs to be some basic support for filtering based on text search on a string field. -- something like `?in_myStringField=foo` matching any records where `myStringField` is `LIKE '%foo%'`

I understand that one, can add elastic-search plugin to benefit from full-text search plus many other things it supports, but that sounds like a long way to go if all you need is to build a simple CRUD application with standard text search.

**Comment by leplatrem** [comment]
Thanks for opening the issue! 

The `in_` operator is already used for multiple values filtering (eg. `in_status=closed,opened`), we have to come up with a new one I guess (e.g. `contains_`). 

Also maybe we should accept patterns like (`contains_url=http(s?)`).

**Comment by leplatrem** [comment]
Oh, I forgot to ask : would be willing to work on this feature (we can help) ?

**Comment by mvalipour** [comment]
Sure, I'd love to.

in regards to the name, surely we could detect the fact that the field following `in_` is a string field and not an array, therefore interpret it differently?
