### ISSUE TITLE
Return 400 if a group contains system.Everyone or a group URL

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#794]
Unless I'm mistaken:

* We don't support groups for anonymous requests
* We don't support recursivity in groups definitions

So we should reject with `400` if such groups definitons are created

**Comment by lavish205** [comment]
Hi @leplatrem this seems easy, but can you provide little more information regarding where we need to add this check and raise 400?

**Comment by leplatrem** [comment]
You have to add à custom validator on the group schema members field, and everything will be taken care of by kinto.core

I advise you to start by writing a group view test that will fail at first, and then make the changes so that the validator comes in the game :)
