### ISSUE TITLE
Cornice 2 is not compatible anymore : 'Errors' object has no attribute 'request'

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#800]
Since request have been removed from request.errors we have a lot of this kind of error each time the validator fails.

**Comment by Natim** [comment]
Refs https://github.com/mozilla-services/cornice/pull/372

**Comment by leplatrem** [comment]
I don't think this is a bug.

It's a matter of compability with cornice master / v2 AFAIK

**Comment by leplatrem** [comment]
Closing as Cornice 2 was not released yet, and #790 will cover the changes.
