### ISSUE TITLE
Move the StorageTest class to kinto.core.storage.testing

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#801]
The way https://github.com/Kinto/kinto/pull/771 have been done doesn't allow community backend to import generic backends tests.

**Comment by leplatrem** [comment]
Duplicating the test file accross repos may not be a problem... otherwise we could have something like `kinto.core.storage.testing`

**Comment by leplatrem** [comment]
Move `CacheTest` to `kinto.core.cache.testing`, and move `PermissionTest` to `kinto.core.permission.testing`.

But I would leave their inherited implementations  `MemoryStorageTest`, `PostgreSQLStorageTest` in `tests/core/test_storage`
