### ISSUE TITLE
Link to the FAQ from the index of the doc is broken.

### ISSUE THREAD

**Issue by almet** [Kinto/kinto#802]
It redirects to the overview page whereas the faq now has its own page.

**Comment by sahildua2305** [comment]
@almet Do you mean the link given in sidebar of http://kinto.readthedocs.io/en/latest/index.html? It works for me. Am I taking it wrong?

**Comment by Natim** [comment]
No he means the link in the home page in the Overview section here: http://kinto.readthedocs.io/en/latest/overview.html#faq
