### ISSUE TITLE
deadlock on __heartbeat__

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#804]
If I set up the same postgresql database/user for the storage, cache and permission connectors, I get a thread deadlock on the second call to __heartbeat__, leading to a blocking call, that makes the HB fails.

Looks like a DB connector race condition issue

**Comment by leplatrem** [comment]
Is that as easy as described to reproduce ?

**Comment by tarekziade** [comment]
I tried to write a test to reproduce it but I can't. But if you run a server it can be reproduced.

**Comment by leplatrem** [comment]
I could reproduce on Travis with kinto-dist https://travis-ci.org/mozilla-services/kinto-dist/jobs/158134738

**Comment by tarekziade** [comment]
@leplatrem  Good job! you beat me to it :)
