### ISSUE TITLE
Disparity between memory and postgresql when filtering with missing values

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#815]
Once #814 will be merged, there is another minor bug to tackle:

when filtering with `?max_field=10`, the memory backend returns records which don't have `field` defined, and postgresql does not.

**Comment by magopian** [comment]
Let's follow what Postgresql does on that one.

**Comment by magopian** [comment]
As a side note, [this test](https://github.com/Kinto/kinto/blob/54572a2d9aa4a56fdf49cf463324dd2dee8260a3/kinto/core/storage/testing.py#L341) doesn't fail for the memory backend because there's a `min` constraint that "fixes" the issue.
