### ISSUE TITLE
Add an "export to CSV" feature

### ISSUE THREAD

**Issue by almet** [Kinto/kinto#817]
It should be possible to request the records in a CSV or TSV format (rather than JSON). It could be as easy as specifying a `.csv` at the end of the resource URI, or by changing the `Accept` header.

Pyramid supports [custom renderers](http://docs.pylonsproject.org/projects/pyramid_cookbook/en/latest/templates/customrenderers.html) in order to do this.

**Comment by Natim** [comment]
Right now we used to generate the CSV file on the client side which is not optimal...

**Comment by leplatrem** [comment]
Related #539 

> on the client side which is not optimal

Converting from JSON to CSV in the client-side is not problematic IMO.

The main concern are the columns. Doing the union of every existing fields in the records can be costly, and might lead to some disparities from one page to another.

**Comment by almet** [comment]
It is not problematic thats true, but doing so in the backend means less code to maintain. (also, note that the argument for the cost is true on the server and client approach)

**Comment by leplatrem** [comment]
> in the backend means less code to maintain.

Why ?

----

My main concern is the list of columns.

The client can agregate every pages and build the list of columns from the whole list of records.

On the server we don't fetch the whole list of records from the storage backend, thus we might fall in a situation where two pages have different columns. What about headers? Should they be repeated on every page?

Footnote: I wouldn't say it's an easy pick :)

**Comment by almet** [comment]
Because we have one backend and many frontends :) doing it in the backend simplifies the life of clients.

**Comment by almet** [comment]
I would only return the complete list (probably no pagination). We could propose this feature only if the correction has a schema associated, which would remove the problem you mentioned)

**Comment by anna-liao** [comment]
Is anyone working on this issue? I would like to give it a try for my outreachy contribution.  Thanks!

**Comment by almet** [comment]
In case that helps: https://gist.github.com/almet/04a151035de8a082770b6eaff4060621

**Comment by Natim** [comment]
Should we add a title row? How do you know that rows are in the correct order since items are dicts?

**Comment by almet** [comment]
I've updated it to reflect your remarks. Thanks.

**Comment by leplatrem** [comment]
Archiving old issuesArchiving old issues
