### ISSUE TITLE
Add details attribute to 404 errors

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#818]
Something like `{"details": {"id": "abc", "resource_name": collection}}`

It should be feasible to just raise custom error responses now that we have #748

**Comment by lavish205** [comment]
need more information to work on this bug.

**Comment by leplatrem** [comment]
We must improve the way we raise 404 errors
Here https://github.com/Kinto/kinto/blob/2f0ba5e/kinto/views/__init__.py#L24-L32
And https://github.com/Kinto/kinto/blob/2f0ba5e/kinto/core/resource/__init__.py#L664-L679
in order to provide some additional details in the 404 response JSON body.

See also what was done in #748 

Don't hesitate to ask questions if something does not seem feasible or unclear!

**Comment by mansimarkaur** [comment]
@lavish205 Are you still working on this issue? If not, can I please work on this?

**Comment by lavish205** [comment]
@mansimarkaur No. You can take this issue.

**Comment by mansimarkaur** [comment]
Do we want all 404 errors to contain the details attribute in the response or do we want just the 404 errors raised by `_get_record_or_404` and `_object_exists_or_not` to contain it?
