### ISSUE TITLE
Kinto postgresql connection not released

### ISSUE THREAD

**Issue by amalleIntesens** [Kinto/kinto#819]
I deployed kinto on heroku using this base https://github.com/Kinto/kinto-heroku
My app using kinto is working.
Then I added some monitoring using the ```__heartbeat__``` endpoint.
After a few minutes all the (20) connection of my heroku postgresql (free) instance where taken.
I've tried the ```*_pool_size``` settings but when all the pool connections where taken kinto is again unable to work it out (pool timeout errors).
It seams that kinto is not releasing the connexions created with the heartbeat endpoint...

Can you give me some suggestion ?

**Comment by Natim** [comment]
Yes are correct, this is a bug we fixed last week: https://github.com/Kinto/kinto/issues/804

I am going to release a new version of Kinto so that you can grab a version with the bugfix.

**Comment by Natim** [comment]
Refs https://github.com/Kinto/kinto/pull/820

**Comment by Natim** [comment]
Here you go: https://github.com/Kinto/kinto/releases/tag/4.2.0

to update your kinto-heroku deploy, you can follow [these instructions](https://github.com/Kinto/kinto-heroku#how-to-upgrade--change-configuration-)
