### ISSUE TITLE
Move kinto_admin plugin as a built-in plugin in Kinto.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#831]
[kinto-admin](https://github.com/Kinto/kinto-admin) interface can be served by a kinto service using the [kinto_admin plugin](https://github.com/mozilla-services/kinto-dist/tree/master/kinto_admin).

@leplatrem and I think that it can be a good idea to make it a built-in plugin.

Btw: This means that each release of the Kinto-Admin will update the statics of the kinto admin in Kinto. It doesn't means that Kinto will be released at the same time but it will help keep the plugin up-to-date with the last release.

* [x] Move the folder `kinto_admin` of the kinto-dist repo to `kinto/plugins/kinto_admin`
* [x] Move the `update_kinto_admin` of kinto-dist Makefile into the Makefile of Kinto
* [x] Mention it (commented line) in the configuration template file
* [x] Add a little bit of documentation on how to enable the plugin. Maybe update the overview docs to mention that the admin dashboard is a built-in plugin
* [ ]  Add a paragraph in the releasing documentation to mention that we must run `make update_kinto_admin`

**Comment by Natim** [comment]
@n1k0 any thoughts about it?

**Comment by Natim** [comment]
This will help people to use an hosted version of the kinto admin available at http://localhost:8888/v1/admin/

**Comment by n1k0** [comment]
I think it's a very good idea 👍

**Comment by VarnaSuresh** [comment]
Can I work on this?

**Comment by Natim** [comment]
@VarnaSuresh yes please do 👍

**Comment by Natim** [comment]
Fixed with https://github.com/Kinto/kinto/commit/a0ce6b45083fdfbdf70b89bb2a50ca0abf6d7a79
