### ISSUE TITLE
StatsD backend keys contain twice backend type

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#857]
![capture d ecran de 2016-10-10 10-26-46](https://cloud.githubusercontent.com/assets/546692/19230297/216fae70-8ed4-11e6-90f6-b73fd694a9d2.png)

`kinto.storage.storage.get` instead of `kinto.storage.get` or `kinto.storage.call.get`

**Comment by d1ndra** [comment]
@leplatrem I'd like to work on this. How should I go about it?

**Comment by leplatrem** [comment]
Great!

As you can see here: https://github.com/Kinto/kinto/blob/4.3.1/kinto/core/statsd.py#L19-L28, we already use the classname (here `storage`) so there is no need to specify the `prefix` like we do during initialization: https://github.com/Kinto/kinto/blob/4.3.1/kinto/core/initialization.py#L247-L249

I believe we'd want to keep the current approach, just that the prefix could just be `backend` so that we have `kinto.backend.storage.get` and `kinto.backend.cache.get` for example

**Comment by d1ndra** [comment]
Should I just be changing the prefixes in [initialization.py](https://github.com/Kinto/kinto/blob/4.3.1/kinto/core/initialization.py#L247-L249)? Did that, but running `make tests` gave 3 errors all referring to the 3 (cache, storage, `permission).

**Comment by Natim** [comment]
@d1ndra yes It is possible that you need to change the three tests you are talking aobut.
