### ISSUE TITLE
Document built-in plugin for kinto-admin

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#858]
- Create a new page
- Explain how to enable it
- Add a screenshot
- Link from overview page
- Mention it in settings

**Comment by sunakshi96** [comment]
Hey 
I would like to work on this issue :-)

**Comment by sunakshi96** [comment]
Hey 
I want to ask that the third step:"Link from overview page" mentioned above ,does it refer to the main KintoAdmin Page

**Comment by glasserc** [comment]
I think it means the overview page of the Kinto server project, i.e. http://kinto.readthedocs.io/en/stable/overview.html .
