### ISSUE TITLE
Switch from colander to jsonschema?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#872]
Now that Cornice 2.0 supports any kind of validation, we could switch from colander to jsonschema, since it's already a dependency.

Pros: 
- remove a dependency
- schemas would be simple dicts, easy to manipulate
- may simplify #631 

Cons:
- jsonschema are verbose
- Lib may not be as solid as colander?
- Validation errors may not be as clear?
- Would break API of `kinto.core`

Related #790

**Comment by Natim** [comment]
I am not against using JSONSchema for that but rather a bit reluctant.
How would it looks like in terms of code separation? Will we create JSON files with the JSONSchema for each kind? (bucket, collection, group, permission, record, history, webpush) and load the file from the Python code?

As you said the biggest impact would be the error messages that would be hard to configure.

I am not sure it worth it to be honest.

**Comment by leplatrem** [comment]
> How would it looks like in terms of code separation? 

Instead of having Colander classes, we would have simple dicts in the source code (not JSON files)

> I am not sure it worth it to be honest.

+1
