### ISSUE TITLE
Error views seem to happen after the pyramid-tm tween

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#877]
See mozilla-services/kinto-fxa#33. We're hacking around this for now but it would be good to have a real fix.

**Comment by leplatrem** [comment]
Shouldn't this be reported to pyramid-tm instead?

Or couldn't we prevent to do smart stuff in the 403 view? Like why are we transforming a 403 into a 401 anyway?

**Comment by Natim** [comment]
> Why are we transforming a 403 into a 401 anyway?

That's to be consistent with the Kinto protocol. If you are not authenticated you should have a 401 and not a 403.

**Comment by glasserc** [comment]
I'm not sure if it's a problem with `pyramid-tm` or if we're using it wrong.

**Comment by leplatrem** [comment]
Tracked upstream: https://github.com/Pylons/pyramid_tm/issues/40

**Comment by leplatrem** [comment]
I suggest that we close this, and make sure the code we put in those error views do not hit the backends
