### ISSUE TITLE
Should the cache backend even use transactions?

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#879]
mozilla-services/kinto-fxa#33 seems to be related to the fact that we're opening a transaction to consult the authentication cache. Is this really necessary? It seems like for a cache, we don't need any of the ACID properties. /cc @leplatrem

**Comment by leplatrem** [comment]
AFAIK there's always a transaction (isolation) for every operation. Nevertheless, a transaction does not necessary last more than one instruction.

So yes, I agree the cache operations could be decorrelated from the transactions managed along the request cycle!

**Comment by leplatrem** [comment]
As @Natim noted, it would also allow to use the cache in `AfterResourceChanged` hooks, that are executed once the request transaction is committed.
