### ISSUE TITLE
Backoff a percentage of clients

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#890]
Add a _percentage_ setting for backoff. If specified, then send backoff header only if `random number < percentage`.

**Comment by noisedispatch** [comment]
Hi @leplatrem, I would like to work on it but this is my first timer PR, do you think I'm qualified? Thanks a lot!

**Comment by leplatrem** [comment]
Hi @noisedispatch! 
I'm very glad you chose Kinto for your first PR! 

The amount of code to write for the feature itself is very small, so you'll probably have to be prepared for other kinds of obstacles like handling Git and writing a test that controls the expected behaviour.

But don't worry, we can help you!

Enjoy! ...and thanks again for proposing your help!

**Comment by noisedispatch** [comment]
Hi @leplatrem ! Thanks for your approval and encouragement! A quick question, when I followed the tutorial to install kinto from source, I found an error here:

```
noisedispatch:~/workspace (master) $ make serve
.venv/bin/kinto --ini config/kinto.ini init
Traceback (most recent call last):
  File ".venv/bin/kinto", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntu/workspace/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/home/ubuntu/workspace/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
import platform
    f(*args, **kwargs)
  File "/home/ubuntu/workspace/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ubuntu/workspace/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/ubuntu/workspace/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/ubuntu/workspace/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'transaction<2' distribution was not found and is required by kinto
```

I checked the release note of [transaction](https://pypi.python.org/pypi/transaction) and make a change: https://github.com/noisedispatch/kinto/blob/master/setup.py#L29. After which I can run kinto locally.

**Comment by Natim** [comment]
I guess your fork is outdated: https://github.com/Kinto/kinto/blob/master/setup.py#L29

**Comment by leplatrem** [comment]
Yeah Python dependencies and cache can be tricky when incompatible version ranges are modified. Let us know if you could get back on tracks!

**Comment by rmorris1218** [comment]
Happy to help with this. For clarity, would it be a setting to only send backoff header under heavy load if, say, random.random()*100 < backoff.percentage?

**Comment by leplatrem** [comment]
The setting would be set by an administrator. Then in the Python code, we generate a random number, if it is below the percentage, we set the header, otherwise we don't. If we consider that the random number distribution is linear, then we know we'll have a certain percentage of hits to receive the header.

**Comment by jvce92** [comment]
Hi @leplatrem, is this issue still available? This is my first attempt on contributing to a project. Just to make sure I understand what needs to be done, in case backoff is not none in (https://github.com/Kinto/kinto/blob/cad62f33cd668857a53820b2818c22ddd8602ce8/kinto/core/initialization.py#L134-L135) a random number is generated and the backoff header is sent only if random() < backoff percentage, right?
Also, we'd need a new field on the configuration file (e.g. kinto.backoff_percentage), right?

**Comment by leplatrem** [comment]
Hi @jvce92 !

Thanks for your interested in the project! welcome on board!

Indeed, you'll have to introduce a new settings like `kinto.backoff_percentage` and if it is defined, then put the header only if random is below the specified value (which is could also be understood as «backoff probability» ;))

**Comment by jvce92** [comment]
Do you have any idea how this could be tested?

**Comment by leplatrem** [comment]
Sorry for the delay, your message got lost in my pile of notifications :(

You would use a library called `mock` that could force the value of `random` :)

Something like that`(untested code):

```py
# initialization.py
import random

...
if random.random() > setting:
    response.headers["Backoff"] = ...
```

```py
# tests.py
with mock.patch('kinto.core.initialization.random.random', return_value=0.6):
    resp = self.app.get("/")
    self.assertIn("Backoff", resp.headers())
```
