### ISSUE TITLE
Improve default configuration template

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#895]
The configuration template does not contain every option as commented lines (e.g permission endpoint or permissions principals per resource)

I propose that we take some of what we've done here:
https://github.com/mozilla-services/kinto-dist/blob/3d17efb2c370822e3db1cc4b5a932684c5e42a4e/config/kinto.ini

And also add a task in the pull-request template to mention that the configuration template should be updated if a new setting was introduced.

**Comment by sahildua2305** [comment]
@leplatrem did you mean to include the options commented out in [`/config/kinto.ini`](https://github.com/mozilla-services/kinto-dist/blob/3d17efb2c370822e3db1cc4b5a932684c5e42a4e/config/kinto.ini) to [`kinto.tpl`](https://github.com/Kinto/kinto/blob/master/kinto/config/kinto.tpl)?

**Comment by leplatrem** [comment]
Yes, I think it's beneficial to have every options «exposed» in the config file (commented out, with nice sectioning etc.)

**Comment by jkieberk** [comment]
Hey @leplatrem, first time attempting to contribute to an open source project, so not sure how much  changing around the structure of a file is acceptable in this instance where I'm new to a project.
 
Would you like to keep the general layout of the kinto.tpl file? For example, my plan was to go through the [configuration file](https://kinto.readthedocs.io/en/latest/configuration/settings.html) and copy the general structure of that to try and make the configuration layout consistent across files. 

What I'm hung up on is that I see someone has added a "Production settings" section to [kinto.tpl](https://github.com/Kinto/kinto/blob/master/kinto/config/kinto.tpl) (Line 85), that has the setting kinto.http_host which is also in the [Scheme, Host, and Port](https://kinto.readthedocs.io/en/latest/configuration/settings.html#scheme-host-and-port) section.

In situations like this, should I move the settings to their own sections (kinto.http_host and kinto.http_scheme for example) or keep them where they are?

Thanks!

**Comment by leplatrem** [comment]
> how much changing around the structure of a file is acceptable in this instance where I'm new to a project.

The sky is the limit! As long as you find it better than the current one ;) Don't spend too much time on it before submitting a first version, so that we can give you feedback ASAP

>  my plan was to go through the configuration file and copy the general structure of that to try and [...]

That sounds like a good idea!

> In situations like this, should I move the settings to their own sections (kinto.http_host and kinto.http_scheme for example) or keep them where they are?

I don't understand this... If you refer to INI sections (like `[production]`) unfortunately we can't do that easily (see #220), that's why we stick to these ascii art sections :D

**Comment by jkieberk** [comment]
Sounds good! :)

One more question, is there a style guide somewhere? Haven't been able to find one looking through the docs.

**Comment by glasserc** [comment]
We use `flake8` to enforce consistent style on Python code. I don't think we have any style guide for other files (and certainly not for `.tpl` files).

**Comment by heron182** [comment]
Hey all!  That seems like a good first PR for me 😄 , is it still up for grabs ?

**Comment by leplatrem** [comment]
Hi @heron182 ! Yes, you can! Thanks for your interest!
