### ISSUE TITLE
Expose inherited resource permissions 

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto#907]
Context: https://github.com/Kinto/kinto-admin/issues/311

At this moment clients are expected to retrieve the parent resource permissions tree to compute the actual permissions set for a given resource.

Eg. if 

- User A has `write` permission on bucket `buck`
- We query record information for `/buckets/buck/collections/coll/records/123`
- If the record has no explicit `write` permission set for user A, you have to crawl permissions for collection `coll` and bucket `buck` to know that user A has inherited `write` permission for this record from the bucket.

This is kinda tricky, and could probably be directly exposed by the server at the resource level. This would solve the issue of possibly performing lots of queries from the client, and would make super explicit what the current permissions for a given resource are, contextually to the current authenticated session.

This might have some impact on performances, as well as adding a bunch of complexity to the permission layer codebase on the server; on the other hand, this could quite heavily simplify usage for clients and application developers.

**Comment by leplatrem** [comment]
I think this is covered by the permissions endpoint :) Please re-open if I'm wrong!
