### ISSUE TITLE
Separate the README and the actual documentation

### ISSUE THREAD

**Issue by ametaireau** [Kinto/kinto#92]
Currently, the documentation uses the README file and as such displays a link to the documentation, which isn't useful when we're already on the documentation page (because you already know where the documentation is).

Removing the links from the readme (as was attempted previously) also removes them from the github repository, where it's actually valuable. I believe the best way to proceed would be to actually have the readme as a different resource than the actual documentation.

**Comment by Natim** [comment]
I see this link more as an ID of the official URI of the current resource.

I don't understand why it bothers you that much but if you really want to remove this link the way forward is to remove the inclusion of the readme in the documentation index. Note that we may have duplicates between the README and the home page.

**Comment by ametaireau** [comment]
Let's just remove the inclusion of the readme then. It doesn't bothers me *that* much, it's just that it's getting in the way of having an easier to follow documentation, that's all.
