### ISSUE TITLE
Cannot select multiple fields in sub tree: parent.subparent.field

### ISSUE THREAD

**Issue by pocmo** [Kinto/kinto#920]
We noticed a problem with the 'fields' filtering in recently deployed versions.

Works: Just show attachment.original.filename field
https://firefox.settings.services.mozilla.com/v1/buckets/fennec/collections/catalog/records?_fields=attachment.original.filename

Works: Just show the attachment.original.filename.hash field
https://firefox.settings.services.mozilla.com/v1/buckets/fennec/collections/catalog/records?_fields=attachment.original.hash

Does **NOT** work: Just show the attachment.original.filename and attachment.original.filename.hash fields (Only returns hash):
https://firefox.settings.services.mozilla.com/v1/buckets/fennec/collections/catalog/records?_fields=attachment.original.filename,attachment.original.hash

Does work: Just show the attachment.original.filename and attachment.location fields:
https://firefox.settings.services.mozilla.com/v1/buckets/fennec/collections/catalog/records?_fields=attachment.original.filename,attachment.location

It seems like as soon as we select more than one field in attachment.original.* just one field is returned.

**Comment by leplatrem** [comment]
Thanks for reporting!

I confirm :|

```
➜  kinto-dist git:(master) http :8888/v1/buckets/default/collections/test/records?_fields=a.b.c1,a.b.c2 --auth user:pass
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Content-Length, Expires, Alert, Retry-After, Last-Modified, Total-Records, ETag, Pragma, Cache-Control, Backoff, Next-Page
Cache-Control: no-cache, no-store
Content-Length: 105
Content-Type: application/json; charset=UTF-8
Date: Thu, 17 Nov 2016 10:12:34 GMT
Etag: "1479377486159"
Last-Modified: Thu, 17 Nov 2016 10:11:26 GMT
Server: waitress
Total-Records: 1

{
    "data": [
        {
            "a": {
                "b": {
                    "c2": 2
                }
            }, 
            "id": "26ca2cc8-1cff-4d73-88a8-5cde5da05546", 
            "last_modified": 1479377486159
        }
    ]
}
```

```
➜  kinto-dist git:(master) http :8888/v1/buckets/default/collections/test/records?_fields=a.b.c1,a.b.c2 --auth user:pass
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Content-Length, Expires, Alert, Retry-After, Last-Modified, Total-Records, ETag, Pragma, Cache-Control, Backoff, Next-Page
Cache-Control: no-cache, no-store
Content-Length: 105
Content-Type: application/json; charset=UTF-8
Date: Thu, 17 Nov 2016 10:13:01 GMT
Etag: "1479377486159"
Last-Modified: Thu, 17 Nov 2016 10:11:26 GMT
Server: waitress
Total-Records: 1

{
    "data": [
        {
            "a": {
                "b": {
                    "c2": 2
                }
            }, 
            "id": "26ca2cc8-1cff-4d73-88a8-5cde5da05546", 
            "last_modified": 1479377486159
        }
    ]
}
```

But do you think the behaviour changed in recent versions? How critical is it?

**Comment by pocmo** [comment]
Wenn have been using this in Fennec, so I guess this has worked before. We will need to ship an update that just selects attachment.original and therefore all fields. Or we deploy a fix to the Limit server soon. :)

**Comment by leplatrem** [comment]
I submitted a PR with the fix. If everything goes extremely fast, we could tag, QA and release this afternoon, but tomorrow or monday would be more realistic I suppose.
