### ISSUE TITLE
Expose a dedicated capability when basicauth is enabled

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto#934]
Refs https://github.com/Kinto/kinto-admin/issues/331

We need to know if the basicauth authentication method is available on a given server. We could detect if the server is configured with basicauth enabled and expose a dedicated capability in the hello endpoint; wdyt?

**Comment by leplatrem** [comment]
As @Natim said somewhere: everything that can be (un)plugged from settings should be mentionned as a capability
