### ISSUE TITLE
Plug OpenID Connect authentication policy.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#939]
- LDAP is going to be replaced by auth.mozilla.auth0.com
- FxA is now supporting OpenId Connect too.

It looks like a standard for OpenID providers and it would make it configurable for a wide range of identity providers.

**Comment by Natim** [comment]
[Image](https://mana.mozilla.org/wiki/download/thumbnails/63933165/Screenshot_20161110_091720.png?version=1&modificationDate=1478798274293&api=v2&effects=drop-shadow)

**Comment by adngdb** [comment]
Support for Github authentication would be nice to have, especially if this makes it easier to install / use than using a home-made plugin like proposed on the tutorial. :)

**Comment by leplatrem** [comment]
Related: #508
