### ISSUE TITLE
GET on /v1/admin returns 404

### ISSUE THREAD

**Issue by gabisurita** [Kinto/kinto#951]
The expected address for built-in admin plugin is `/v1/admin/`. But if you forget the trailing slash and type `/v1/admin` you get a 404. I think it would be better to raise a 307.

Related to #112 and #858.

```
> http get localhost:8888/v1/admin/
HTTP/1.1 200 OK
(...)

> http get localhost:8888/v1/admin
HTTP/1.1 404 Not Found
(...)
```

**Comment by Natim** [comment]
I totally agree :)
