### ISSUE TITLE
Add a configuration of collections that the history plugin needs to keep track on

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#964]
Today the history plugin applies to all the collection but most of them don't need it.
For instance with the kinto-signer plugin we don't want to track history of changes in the preview and signed collection.
The same goes with the kinto-changes plugin when we don't want to track monitor changes modifications.

The same way we can configure the kinto-signer resources we want to track, we should be able to configure the list of collections we want the history plugin to track.

**Comment by leplatrem** [comment]
I'd rather go with exclude on this one.

If I start a new project, I don't want to ask an administrator to change the server configuration to enable something...

For the signer plugin we could have:
```ini
kinto.history.exclude_resources = /buckets/blocklists-preview /buckets/blocklists
```

And I don't think the kinto-changes generates any event, so it might not be tracked in the history. We can also consider getting it of the resourcechanged events in the  kinto-signer if that makes sense.

**Comment by Natim** [comment]
Yes exclude works too 👍
