### ISSUE TITLE
JSON Merge Patch deserialization is broken 

### ISSUE THREAD

**Issue by gabisurita** [Kinto/kinto#979]
Merge-patch operations are broken. It looks like a deserialization problem, which may have been introduced with  #790.  Also, we should definitely include some view tests for this content-type. My bad :/ 
  
```
echo '{"data": {"aaa": "bbb"}}' | http patch localhost:8888/v1/buckets/b1 Content-Type:application/merge-patch+json -a aaa:
HTTP/1.1 400 Bad Request
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 331
Content-Type: application/json; charset=UTF-8
Date: Sun, 11 Dec 2016 23:47:26 GMT
Server: waitress

{
    "code": 400,
    "details": [
        {
            "description": "\"{\"data\": {\"aaa\": \"bbb\"}}\n\" is not a mapping type: Does not implement dict-like functionality.",
            "location": "body",
            "name": ""
        }
    ],
    "errno": 107,
    "error": "Invalid parameters",
    "message": "\"{\"data\": {\"aaa\": \"bbb\"}}\n\" is not a mapping type: Does not implement dict-like functionality."
}
```

**Comment by leplatrem** [comment]
Thanks for reporting! 

It is strange that no test was broken oO

**Comment by gabisurita** [comment]
Yes. It is.
I guess it's because the `record` tests in the core scope override the `validated` field, thus skipping deserialization and validation.
https://github.com/Kinto/kinto/blob/master/tests/core/resource/test_record.py

**Comment by gabisurita** [comment]
Yes. It is.
I guess it's because the `record` tests in the core scope override the `validated` field, thus skipping deserialization and validation.
https://github.com/Kinto/kinto/blob/master/tests/core/resource/test_record.py
