### ISSUE TITLE
Delete is not affected by limit query

### ISSUE THREAD

**Issue by gabisurita** [Kinto/kinto#987]
The [current documentation](https://kinto.readthedocs.io/en/latest/api/1.x/pagination.html) says:

> Plural endpoints support limiting the number of elements returned. For example, you can retrieve a fixed number of records in a collection. To do this, provide a `_limit` query parameter specifying the number of records to return.
(...)
Pagination works on any plural endpoint.

It doesn't work on delete endpoints and I'm not sure if it should. I guess the behavior in this case might be a bit dubious. Would it limit the number of deleted entries or the number of returned deleted entries? 

An example:
```json
$ http delete localhost:8888/v1/buckets?_limit=1 -a a:HTTP/1.1 200 OK
Access-Control-Expose-Headers: Retry-After, Content-Length, Alert, Backoff
Content-Length: 181
Content-Type: application/json; charset=UTF-8
Date: Sun, 18 Dec 2016 18:53:46 GMT
Server: waitress
X-Content-Type-Options: nosniff

{
    "data": [
        {
            "deleted": true,
            "id": "b1",
            "last_modified": 1482087226574
        },
        {
            "deleted": true,
            "id": "b2",
            "last_modified": 1482087226575
        },
        {
            "deleted": true,
            "id": "b3",
            "last_modified": 1482087226576
        }
    ]
}


```

**Comment by leplatrem** [comment]
I suppose that the returned entries should match the deleted objects.

For consistency, we can consider that `_limit` should limit the number of objects to delete.
