### ISSUE TITLE
Add aggregation

### ISSUE THREAD

**Issue by magopian** [Kinto/kinto#989]
It would be pretty convenient to have some aggregation capabilities (on top of the already existing `max` and `min`), like:
- `avg`
- `sum`
- `median`
- `count` ([which can already be retrieved](http://kinto.readthedocs.io/en/stable/api/1.x/pagination.html?highlight=count#counting))
- `mode`

See the [wikipedia page](https://en.wikipedia.org/wiki/Aggregate_function)

**Comment by leplatrem** [comment]
I don't understand how would that be used? As filters? 

My first reaction would be to avoid having those in core since ElasticSearch provides those features already, and the tutorial makes it easy for someone to start implementing it :)

**Comment by leplatrem** [comment]
I'm tented to close it, since we currently don't have the notion of *operation* on the data, only filters for returning partial data.

Feel free to reopen if you have a clear view on how it would look like :)
